### ISSUE TITLE
Opening executable that requires elevated privileges to run might invoke UAC multiple times

### ISSUE THREAD

**Issue by Kaedin** [files-community/files-uwp#1000]
**Describe the bug**
Opening executable that requires elevated privileges to run might invoke UAC multiple times

**To Reproduce**
1. Locate an executable (.exe) that requires elevated privileges
2. Select "Open" or double click on the file
3. When "User Account Control" dialog is invoked, select "No"
4. UAC dialog opens multiple times again

**Expected behavior**
One dialog should be enough as per normal Windows behavior.

**Screenshots**
Cannot record UAC prompts that easily on this physical system. Trying to reproduce on virtual environment.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Version 2004 (OS Build 19041.329)
 - App version: [v0.9.2.0]

**Comment by Kaedin** [comment]
Attached a recording where it can be seen how multiple UAC dialogs are invoked when starting certain executables.
![06-54-24_Trim2](https://user-images.githubusercontent.com/26382655/85820727-8ea30780-b77f-11ea-852a-687b5134e9a2.gif)

**Comment by yaichenbaum** [comment]
@Kaedin The items in the recent list only need to be clicked once to launch the file. The cause for two UAC dialogs is because you are double clicking on the items.

**Comment by ilepn** [comment]
> @Kaedin The items in the recent list only need to be clicked once to launch the file. The cause for two UAC dialogs is because you are double clicking on the items.

@yair100 Actually, this issue occurs either when I'm trying to open the executable from Recents or via browsing into the actual folder where it resides. In later case, a double click is required to run the executable and the UAC dialog is invoked multiple times. Sometimes there's also more than 2 dialogs invoked when launching using the double click so the behavior is not bound the number of mouse clicks.
