### ISSUE TITLE
 Home page Recent Items (almost) always empty

### ISSUE THREAD

**Issue by andyfmidd** [files-community/files-uwp#1007]
Home page "Recent items" list is always empty - I can't add to to it, unless I open a file.
Select a directory/file. Add it to Sidebar.
Goto Home: no items.
Access the directory via sidebar.
Goto Home: no items.

Find a file, (I chose a .png) open it. It now shows up on Home. Navigate somewhere else, then back to home. The item has gone.

Additional: how many recent items can appear, in theory? Need vertical scroll bar?

0.9.2 on Windows Insider 19645.

**Comment by duke7553** [comment]
This behavior of only showing files is by design for now.

Do you have a better experience we can look into in mind?

**Comment by yaichenbaum** [comment]
@andyfmidd The recent item list is limited to showing recent files only, if you have feedback about this or if you would like to see more features on the home screen, make sure to let us know in #366.
