### ISSUE TITLE
Selecting 'Open in new tab' option in preferences causes a crash

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#1008]
**Describe the bug**
Selecting 'Open in new tab' option in preferences could cause a crash if it isn't selected already.

**To Reproduce**
1. Go to Settings>Preference
2. Select 'Open a specific page'
3. Now select 'Open a new tab'
4. App will crash

**Expected behavior**
App shouldn't crash and it should select the option.

**Screenshots**

![2020-06-11 18-10-04_Trim](https://user-images.githubusercontent.com/45227503/84387591-e33b7400-ac10-11ea-9c7b-41c98b6ebc86.gif)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 20H1
 - App version: v0.9.2

**Comment by XPoppyX** [comment]
#932
