### ISSUE TITLE
You shouldn't be able to pin library folders

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#1009]
**Describe the bug**
Currently, pin to sidebar option is shown for all folders including library folders such as Pictures, Documents etc.. This causes duplicate entries in the sidebar.

**Expected behavior**
This option should not be shown as these folders are already pinned and can't be unpinned.

**Comment by yaichenbaum** [comment]
Duplicates are already handled, it's necessary to allow pinning libraries since they can be unpinned as well.
