### ISSUE TITLE
Drives (system and external) do not appear in sidebar

### ISSUE THREAD

**Issue by megalofauna** [files-community/files-uwp#1010]
**Describe the bug**
My drives are not shown/available in the sidebar, e.g., `C:\` (my system drive) and `E:\` (an external drive).

**To Reproduce**
1. Open Files UWP
2. Observe sidebar

**Expected behavior**
I would expect that Files UWP would recognize and display my system and external drives. 

**Screenshots**
![Annotation 2020-06-11 081325](https://user-images.githubusercontent.com/8394554/84389439-a42f0380-abbb-11ea-853e-4334f77a7903.png)

**Versions**
 - OS Version: 10.0.19041 Build 19041
 - App version: v0.9.2.0

**Does this problem occur again after restarting the app?**
Yes.

**Comment by Jaiganeshkumaran** [comment]
Duplicate of #488.

**Comment by megalofauna** [comment]
Dup as noted above.
