### ISSUE TITLE
Per-Folder Layout Mode

### ISSUE THREAD

**Issue by sumanth-vs** [files-community/files-uwp#1016]
Looks and Performs really well!

**Unexpected Behaviour : **
One expected behaviour is - different folders should be able to have different Layout Modes. For example, my I want my Pictures folder to have Grid Layout, but my Documents folder to have List View Layout.

Currently, however, layout modes seem to apply everywhere. If I change the layout in Pictures, it changes the layout throughout the app.

**Comment by XPoppyX** [comment]
Duplicate: #530

**Comment by yaichenbaum** [comment]
Merging with #530.
