### ISSUE TITLE
Here's everything I really want to see from this that isn't there yet

### ISSUE THREAD

**Issue by KirbyCrafter** [files-community/files-uwp#1017]
**Is your feature request related to a problem? Please describe.**
1. There is no graphic display for how much space you have left on a drive, only a number, which means I can't just glance at it and know roughly how much space I have left on my drive. (I know this makes me sound illiterate but I'm asking for a convenience feature ok?)
2. custom icons don't display, and I like to use custom icons to more easily distinguish my folders at a glance.
3. (this one isn't in the windows file explorer either) a way for a user to hide specific files would be nice, as in separate from the built-in way to hide files in windows, because with that, you can download files that are hidden and get viruses and all that unfortunate stuff.
4. There is no separation for download dates in the downloads folder, a feature I've come to like quite a lot with the windows file explorer.
5. the only way to deselect files seems to be to click outside the window.
6. The only way to download Files UWP is through the Microsoft store, which sucks because fewer people will find it in the first place if it's not available somewhere else, and also people who do find it, might be less inclined to install and use it.
**Describe the solution you'd like**
1. it would be nice if we could get a similar display that maybe pops out of the side of your drive when you hover over it in the drives section.
2. I don't know anything about software development or how file explorers work behind the scenes, but the way that the default windows file explorer does it seems pretty damn good, so if there's a way to mimic that then that'd be great.
3. (this one isn't in the windows file explorer either) a way for a user to hide specific files would be nice, as in separate from the built-in way to hide files in windows, because with that, you can download files that are hidden and get viruses and all that unfortunate stuff. would be purely cosmetic, and if you're wondering what the use case is here, I use a couple of invisible ico files with no name on my desktop to block files from appearing in certain spots for organization reasons, so it would be nice if they didn't show up in file explorer.
4. Add date grouping, so anything in the last week would be categorized as "last 7 days" then "last month", "last three months", etc.
5. adding a click and drag function would solve this, just drag over nothing to deselect everything. would also make it a lot easier to select multiple files. just clicking out of the file area, like to the right of where it shows the size of the file, could probably work too.
6. Make an installer for it, so anyone can download it without the use of the Microsoft store.

**Describe alternatives you've considered**
1. alternatively, adding a percentage of space remaining on a drive would accomplish the same thing, but without the need for a visual reference. Maybe the percentage text could change color starting at green and then slowly going to yellow then red as the drive fills up?
6. Put it on steam or something, I would by far prefer to have a DRM free version of the software, but if making an installer is too difficult I would certainly rather get it through steam.

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Jaiganeshkumaran** [comment]
@KirbyCrafter If you don't like using Microsoft Store, you can download the latest version from the releases tab in GitHub.

**Comment by yaichenbaum** [comment]
> The only way to download Files UWP is through the Microsoft store, which sucks because fewer people will find it in the first place if it's not available somewhere else, and also people who do find it, might be less inclined to install and use it.
Describe the solution you'd like

You can install Files UWP from command line using the command `WinGet install FilesUWP`

**Comment by duke7553** [comment]
Thank you for taking the time to open this feedback item. In order to best address this in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one. 

Closing this now.
