### ISSUE TITLE
A "Don't ask again" option for file deletion.

### ISSUE THREAD

**Issue by AqilCont** [files-community/files-uwp#1020]
### Is your feature request related to a problem? Please describe.
So, making files and deleting them is a daily routine thing for me, and a big pop-up window asking me if I want to delete them is a slight inconvenience.

## Describe the solution you'd like
So, the first time you delete a file, you should be greeted with the normal pop-up that asks you if you want to delete the file, if you want to delete it permanently, etc. There should be an additional ticker that says, "Don't ask again" that disables permanent deletion while ticked(basically all files go to recycling bin) and simply stops prompting you to approve the deletion of the file. There should obviously be a section in Settings if you change your mind someday.
![image](https://user-images.githubusercontent.com/32044067/84447337-b6d62680-ac15-11ea-8058-818d46f18f71.png)

**Describe alternatives you've considered**
~~switching back to File Explorer~~

**Comment by duke7553** [comment]
![image](https://user-images.githubusercontent.com/20365014/84838914-b79dfc80-b009-11ea-8ab3-ee8cd0c351fe.png)
