### ISSUE TITLE
App or Customized Context Menu

### ISSUE THREAD

**Issue by fralyx** [files-community/files-uwp#1024]
App's context menus for me is the big part of my daily routine on using file explorer, and I also hate the fact that this is UWP as the `WindowsApps` directory is inaccessible and I want the executable version as well.

![cm](https://user-images.githubusercontent.com/8995187/84455860-a27f4180-ac88-11ea-93cb-1ad6cdbbba47.png)

**Comment by Jaiganeshkumaran** [comment]
See #699

**Comment by lampenlampen** [comment]
@fralyx Why do you need the exe?

The exe is located at `%localappdata\Microsoft\WindowsApps\files.exe`

**Comment by fralyx** [comment]
@lampenlampen It's just me wanting to customize my windows even further. Somehow my WindowsApps folder is locked

**Comment by fralyx** [comment]
@Jaiganeshkumaran ah ok, i see it was done on yesterday there
https://github.com/files-community/files-uwp/pull/699#issuecomment-643569715

Thanks for pointing out

**Comment by Jaiganeshkumaran** [comment]
> It's just me wanting to customize my windows even further. Somehow my WindowsApps folder is locked

It's locked by default for everyone however you can mess around the permission to get access however it's not recommended.

**Comment by lampenlampen** [comment]
You can even create you own shortcut and let it point to `files`. That will also open Files-UWP. Then you can customize the shortcut.

**Comment by lampenlampen** [comment]
You can also let the shortcut point to `files -Directory "C:\Users"`, to open a specific folder.

**Comment by yaichenbaum** [comment]
Merging with #174.

**Comment by yaichenbaum** [comment]
This has been implemented with #1754.
