### ISSUE TITLE
One click to navigate

### ISSUE THREAD

**Issue by kyddox** [files-community/files-uwp#1025]
Hi, firt, thank you for your work, i want to ask you to include one click to open files and archives option

Thanks

**Comment by Jaiganeshkumaran** [comment]
Duplicate of #261

**Comment by yaichenbaum** [comment]
An option to open archives would be interesting, can you let us know why you think offering it built in will lead to a better experience than integrating with 7zip or other similar software?

**Comment by kyddox** [comment]
I dont mean to open zip archives, the feature i think will be good is the
option to do just one click on the mouse to open files and folders, i have
using this configurations on the desktop and file explorer since windows xp
and tho need to do double click  is annoying me

*Ing. José Antonio Rovira Puig*
Cel.  04455 1951 7402


Considera el medio ambiente antes de imprimir este correo

**Comment by yaichenbaum** [comment]
@kyddox In that case we will be merging this issue with an existing one #261.
