### ISSUE TITLE
Allow integration with power rename

### ISSUE THREAD

**Issue by chuchanpr** [files-community/files-uwp#1028]
**Is your feature request related to a problem? Please describe.**
Allow integration with power rename

**Describe the solution you'd like**
Allow integration with power rename with a right click or menu

**Describe alternatives you've considered**
Explorer allows this option

**Additional context**
Sample menu
![image](https://user-images.githubusercontent.com/4193718/84470584-48d74100-aca1-11ea-92a9-0b8b0fb04b30.png)

**Comment by Jaiganeshkumaran** [comment]
The app doesn't support custom context menu items yet. See #699.

**Comment by yaichenbaum** [comment]
Merging with #174.

**Comment by yaichenbaum** [comment]
This has been implemented in #1754.
