### ISSUE TITLE
Can't right-click to select open mode

### ISSUE THREAD

**Issue by hakulihanzo** [files-community/files-uwp#1029]
I want to right click on the file and I can choose to open it, like right click on the image file, and I can choose to open it in Photoshop or ACDsee

Thanks

**Comment by Jaiganeshkumaran** [comment]
The latest preview has the open with option. You can download it from https://github.com/files-community/files-uwp/releases.

**Comment by yaichenbaum** [comment]
We are working on adding an "open with" menu. There is not ETA but you can track the progress here #174.
