### ISSUE TITLE
Provide msixbundle at github or offlinedownload at Businessstore

### ISSUE THREAD

**Issue by drfuture** [files-community/files-uwp#1030]
Hi,
this tool looks very promising. as the MS-Store is disabled on my pc (i`m the admin who disabled it but wouldn`t a exctra config for me) i tryed to download the appxbundle by MS Business Store.
Unfortunality this is not posible. Maybe there is a option to allow / disallow this on publishing?
Thx second reason is - i need the appx file to maybe install the software remote.

So please provide the appxbundle files here on github at the release-section or on MS Business Store.

**Comment by yaichenbaum** [comment]
@drfuture Files UWP is already available on WinGet, we try to upload the packages to the GitHub releases as well but that usually takes some time. I will take a look at putting it on the Microsoft Business Store.

**Comment by yaichenbaum** [comment]
@drfuture Files UWP will soon be available on the Microsoft Store.

**Comment by drfuture** [comment]
super thx 👍
