### ISSUE TITLE
Add an option to choose the default text editor

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/files-uwp#1032]
Like in File Explorer, we should have an "edit" option when right clicking on text files. We can have a similar configuration setup that we do for terminal applications to let the user choose which text editor to open by default.

**Comment by jaigak** [comment]
@yair100 I don't really think that this option is really useful. I do use this option occasionally but not for text files.

**Comment by MarcAnt01** [comment]
Hello @yair100 is it possible to extend this enhancement to every type of file?

**Comment by yaichenbaum** [comment]
@MarcAnt01 We might end up just implementing this as part of the "Open With" sub menu in the right click context menu.

**Comment by MarcAnt01** [comment]
Wow, that could be a good idea, as well

**Comment by yaichenbaum** [comment]
Closing this issue in favor of using the "Open With" menu.
