### ISSUE TITLE
Provide option to intergrate with some media manages or include some media manager

### ISSUE THREAD

**Issue by chuchanpr** [files-community/files-uwp#1035]
**Is your feature request related to a problem? Please describe.**
Provide option to intergrate with some media manages or include some media manager

**Describe the solution you'd like**
Provide option to intergrate with some media manages or include some media manager

**Describe alternatives you've considered**
Use a customer MMM via Explorer to manage media (movies and tv shows) and rename files

**Additional context**

**Comment by yaichenbaum** [comment]
Merging with #174.
