### ISSUE TITLE
High cpu and ram usage when calculating the size of folders containing a large number of files

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#1043]
**UPDATE:** After more tests, it only happened the first time, then the use of cpu and ram is not that high anymore, but it is still a bit high, and it takes too long to show the size.
I also realized that it is not so much for the size, but for the amount of file.

while doing the calculation:
![Captura de pantalla (22)](https://user-images.githubusercontent.com/61259627/84553863-57dee300-ace3-11ea-8330-2cfd3db9f392.png)

after finishing the calculation (after a few seconds it returns to normal):
![Captura de pantalla (23)](https://user-images.githubusercontent.com/61259627/84553803-2108cd00-ace3-11ea-8acb-410e5550bd87.png)

**Comment by duke7553** [comment]
Thank you for creating this feedback item. A solution for it is currently being reviewed as a PR (pull request) to our active development branch. We'll let you know once it's merged.
