### ISSUE TITLE
Ask for password when opening bit locked drive for the first time

### ISSUE THREAD

**Issue by chuchanpr** [files-community/files-uwp#1047]
**Describe the bug**
Ask for password when opening bit locked drive for the first time. Now the app crashes

**To Reproduce**
1. Go to 'Files UWP'
2. Click on a drive that is bit locked (first time and it is locked)
3. App crashes

**Expected behavior**
Password should be prompted

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004]
 - App version: [v0.10.1]

**Comment by gave92** [comment]
I can't reproduce this. If I try to browse a drive encrypted with Bitlocker I get an empty drive until I insert the password from windows explorer. I get no crash.
Could you post the contents of `C:\Users\Marco\AppData\Local\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState\debug.txt` after you get a crash?

**Comment by chuchanpr** [comment]
I am not longer able to reproduce crashes, but, I now get an empty drive until i insert the password from windows explorer. I am now one App version 0.10.2.0

Would like to see files requesting for Bitlocker PIN/Password
