### ISSUE TITLE
Possibility to drag and drop files into the sidebar

### ISSUE THREAD

**Issue by dcalderonlo** [files-community/files-uwp#1049]
App version 0.9.2.0

**Comment by Jaiganeshkumaran** [comment]
You can currently drag and drop a file to an another folder in Files UWP. However, you can drag and drop it outside Files UWP.

**Comment by dcalderonlo** [comment]
It's concealer, sorry, I didn't know you had to select the item first, and then you could drag it, either way, you can't drag the files to the items in the left bar.

![image](https://user-images.githubusercontent.com/22837226/84572863-f4989380-ad6a-11ea-8f28-f3eb0bbd8fb1.png)

**Comment by Reged50** [comment]
The same thing happens if you try to drag a file to another open tab. It shows the 'no entry' sign and won't do it. Yet it works fine dragging to an app outside fwp

**Comment by dcalderonlo** [comment]
It's true.
