### ISSUE TITLE
Most Degraded Box Properties

### ISSUE THREAD

**Issue by dcalderonlo** [files-community/files-uwp#1050]
A further degrade can cause the window box properties to not be lost in view with the rest of the application.

If the box were a little more transparent, the view would be less confused.

App version: [v0.9.2]

![image](https://user-images.githubusercontent.com/22837226/84572699-d7af9080-ad69-11ea-983e-3b77162d66cb.png)

**Comment by duke7553** [comment]
Hi. You can already enable Acrylic for this Window in the app settings.

**Comment by duke7553** [comment]
Is this what you had in mind?

**Comment by dcalderonlo** [comment]
I understand, but I haven't been able to see the option in the settings, where is it?

**Comment by dcalderonlo** [comment]
I understand, but I haven't been able to see the option in the settings, where is it?

I have version 0.10.2.0

**Comment by duke7553** [comment]
@dcalderonlo 
![image](https://user-images.githubusercontent.com/20365014/84937603-0a2ef580-b0aa-11ea-807d-1b58cf488d42.png)

**Comment by yaichenbaum** [comment]
@dcalderonlo Thank you for your feedback, I recommend trying the option @duke7553 shared in order to turn off acrylic.
