### ISSUE TITLE
play multiselected mp3s

### ISSUE THREAD

**Issue by B3HI13** [files-community/files-uwp#1057]
**Describe the bug**
when i want to play multiselected mp3s, only the last selected music plays. even i highlighted 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
Windows 10 1909
 - App version: [v0.5.0]
0.9.2.0
**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by yaichenbaum** [comment]
Changes to address this have been implemented with #1062, make sure to subscribe to the releases to be notified when updates are released.
