### ISSUE TITLE
Let's get compatible with QuickLook!

### ISSUE THREAD

**Issue by seriaati** [files-community/files-uwp#1058]
**Is your feature request related to a problem? Please describe.**
So the quicklook website you put in the "about" page of your app actually leads me to an amazing app somebody developed! However, it is not compatible with files UWP.

**Describe the solution you'd like**
Then since you two sort of know each other, why not put quick look straight into files UWP? It would be an amazing feature!

**Describe alternatives you've considered**
The only alternative I've considered is the native windows file explorer, which is what I don't really like xD. I hate the fact that they don't have fluent design.

**Additional context**
I LOVE YOUR APPS! I ALSO USE YOUR QUICKPAD APP! IT IS AMAZING! KEEP UP YOUR GOOD WORK! ♥

**Comment by Jaiganeshkumaran** [comment]
QuickLook is supported by Files UWP and that's why it's listed in the about page however because of a known bug it's no longer working. (#969)

**Comment by seriaati** [comment]
> QuickLook is supported by Files UWP and that's why it's listed in the about page however because of a known bug it's no longer working. (#969)

So it is currently not working.

**Comment by yaichenbaum** [comment]
This issue has been fixed with #1061 and will roll out to users when v0.11 is released.
