### ISSUE TITLE
It's so good!!!! but right click is not power. 这个软件太棒了！但是右键和一些快捷键支持还不是很好，作者加油！

### ISSUE THREAD

**Issue by Yeba** [files-community/files-uwp#1060]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Jaiganeshkumaran** [comment]
Thanks for your appreciation. What options would you like to see in the right-click menu?

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
