### ISSUE TITLE
建议支持网络共享访问，如\\172.18.0.186

### ISSUE THREAD

**Issue by tqgiub** [files-community/files-uwp#1068]
通过系统自带的资源管理器可以打开网络位置，通过files-community不能打开
[https://s1.ax1x.com/2020/06/15/NpILKf.png](url)

**Comment by Jaiganeshkumaran** [comment]
It's a known bug that network folders appear empty, see #642.

**Comment by Jaiganeshkumaran** [comment]
网络文件夹显示为空是一个已知的错误，请参阅＃642。

Translated using [Google Translate](https://translate.google.com/).

**Comment by duke7553** [comment]
Duplicate of #642
