### ISSUE TITLE
can't save my settings

### ISSUE THREAD

**Issue by SoleFreakee** [files-community/files-uwp#1071]
can't save my settings in the setting bar

my language is simplified Chinese, I go to settings bar and have some changes, like pin onedrive to the sidebar,etc. but my changes can't be saved, hope it could be fixed,thank you.
 - OS Version: [e.g. Windows 10 1909 18363.900]
 - App version: [v0.9.2.0]

**Comment by XPoppyX** [comment]
a fix for this will be available in the next version of the app

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our stable branch and should be available from the Microsoft Store. Please subscribe to our releases to be notified when fixes like this are available.
