### ISSUE TITLE
using single click to open file

### ISSUE THREAD

**Issue by dentistfrankchen** [files-community/files-uwp#1073]
Hi i'm a big fun of your product! This is surely a great app, but it still should add some feature. I always use the old explorer, since i can just click on a certain file for on time(instead of double click)to open my files. This feature won't be hard to accomplish. Hope you can make this come true. Thank you in advance.

**Comment by Jaiganeshkumaran** [comment]
Duplicate of #261

**Comment by dentistfrankchen** [comment]
well it's good to see your update but i cannot download the newest version From store...

**Comment by dentistfrankchen** [comment]
Do you need us to compile manually with v0.10?

**Comment by Jaiganeshkumaran** [comment]
> Do you need us to compile manually with v0.10?

We have not implement #261 yet. I just mentioned to let you know that we're working on it.

**Comment by dentistfrankchen** [comment]
ok. thanks.

**Comment by yaichenbaum** [comment]
Merging with #261.
