### ISSUE TITLE
more contact with microsoft company

### ISSUE THREAD

**Issue by dentistfrankchen** [files-community/files-uwp#1074]
Well this team has already improved the explorer a great deal...However, to make this project more perfect, I think your team should make more contacts with microsoft. Maybe they can help you to perfect your design or at least sponsor your team to some extent. 
Your app is very good, and the idea behind your app should be integrated to the new windows 10. It will make it to be a better system.
In short, I don't want this project to become to be something like trans...TB. I DO NOT WANT TO PAY MONEY FOR A PRO VERSION. You should consider write a letter to the powertoy team.

**Comment by Jaiganeshkumaran** [comment]
I don't think Microsoft would replace File Explorer with Files UWP or any other file manager. The real reason why Microsoft hasn't updated File Explorer for years is that Explorer is not just a file manager. It's deeply tied with the operating system and replacing it means Microsoft should make a new shell for Windows 10 as Explorer currently serves as the shell. They can also hide the exisiting File Explorer and make Files UWP the default launcher for folders.

**Comment by mdtauk** [comment]
Windows 10X will be getting a new Shell, and the new Files app will be important for those devices (even if the old file explorer is still there for the Win32 app container and common shell dialogs)

**Comment by Jaiganeshkumaran** [comment]
@mdtauk We don't really know whether Windows 10 will use the new Shell that's coming in Windows 10X. Also, Files UWP doesn't currently work in Windows 10X.

**Comment by dentistfrankchen** [comment]
i think there's some misunderstanding here... there's a hidden uwp file explorer inside win10, however it sucks...You should really cooperate with microsoft and i believe they might accept your idea in the next version of win10.
you can tell them: we are not using it to replace file explorer, we are providing a new tool for customers to manage their files! why we need to be tied with explorer?

**Comment by dentistfrankchen** [comment]
although win has search in file explorer, customers wants easier search, So they developed powertoys run. you can pursuade microsoft to sponsor this program!!

**Comment by lampenlampen** [comment]
I think this is very unlikely to happen.
Microsoft cannot rely on some third party file-manager. Microsoft will not accept the risk of us breaking something in files. Why sponsoring a project, if you have to build the same?

I think the best we can hope for is, that with Windows 10X and the (maybe) new modern file explorer, the file-apis improve and you maybe can choose a default one.

**Comment by yaichenbaum** [comment]
Hi, while Microsoft will not use our app since it's third party, we shared the concept with them a couple months ago and they are helping us in different areas, as time goes on we hope Files will be able to replace File Explorer for most users but at this point the app still needs a lot of work to get there.

**Comment by dentistfrankchen** [comment]
happy to see this.(≧∇≦)/
