### ISSUE TITLE
双击文件，文件闪退

### ISSUE THREAD

**Issue by orrzz** [files-community/files-uwp#1075]
**双击打开文件闪退**

新版双击打开文件闪退，

**Desktop (please complete the following information):**
 - 版     本：Windows10企业版
   版本号 ：2004     操作系统版本：19041.264
 - App version: [v0.9.2.0]

**Comment by hez2010** [comment]
Sorry but I cannot repro your issue. Could you please provide more details?

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
