### ISSUE TITLE
Search Text Box missing

### ISSUE THREAD

**Issue by gamboalx** [files-community/files-uwp#1080]
**Describe the bug**
The search Text Box is not available, only the magnifying glass icon is shown but as inactive icon.

**To Reproduce**
1. Open the explorer
2. Check out  for the Text Box
3. it is not present
4. this is the error

**Expected behavior**
It is expected to have a fillable Text Box to write down the name of the file you want to search for
**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1909 18363.900
 - App version: V0.9.2.0

![UWP ISSUE](https://user-images.githubusercontent.com/66921038/84714896-fc0f9680-af3c-11ea-8a1a-56b265488987.png)

**Comment by yaichenbaum** [comment]
Thank you for your feedback, search is not yet implemented and is therefore disabled.

**Comment by gamboalx** [comment]
*Alright, thank you,I will continue using the explorer anyway. Luis
Gamboa+58 412 6084220*

**Comment by yaichenbaum** [comment]
Merging with #333.
