### ISSUE TITLE
Acrylic sidebar for settings page

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#1083]

**Comment by yaichenbaum** [comment]
Acrylic on the settings page will distract from the UI, if you have a concept in mind that wouldn't lead to this issue, please feel free to share it with us.

**Comment by Jaiganeshkumaran** [comment]
Why not use the less transparent one used in InstanceTabView Sidebar?

**Comment by generalguy41** [comment]
I disagree that it would be distracting. I don't see any issue with the way Windows Settings has it. Besides, it's not like users will be spending tons of time there anyway.

**Comment by yaichenbaum** [comment]
The settings app has a different layout for the sidebar that would make it a little harder to implement this. Additionally the Fluent guidelines specify that areas like the NavigationMenu should not get acrylic as they can cause a distraction. You brought up a good point that users don't spend so much time in settings so at the moment, it doesn't make sense to adjust the settings page to accommodate a setting that won't have a big impact on regular use and that would go against the Fluent guidelines.
That being said, the settings UI does need some work such as a separation between the sidebar and main view and it's something I will try to work on for a future release.

**Comment by Jaiganeshkumaran** [comment]
Technically, the sidebar also uses NavigationView control. Why do you have the acrylic sidebar option when Fluent design guidelines specifies that NavigationView shouldn’t have background acrylic?

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Because the original versions of the app had acrylic on the sidebar, and when we switched, we had **many** users who wanted the option so we included it. However, the settings page isn't a commonly accessed UI, in fact, based off the telemetry, very few users open the settings page.

**Comment by yaichenbaum** [comment]
I have an idea to improve the UI, and it might even work with acrylic. I will share the results after playing around.

**Comment by Jaiganeshkumaran** [comment]
At least consider using a gray background in the Settings NavigationView instead of having everything white with a divider.

**Comment by duke7553** [comment]
@yaichenbaum @Jaiganeshkumaran I've always wanted the settings area to have a more appealing design because it is a core area for feature engagement. The design we have now works great, but what if we made it more welcoming?
I'll do some research in this area.

**Comment by yaichenbaum** [comment]
This has been implemented and will roll out with the next release.
