### ISSUE TITLE
The basic file (and loading placeholder) icon should probably be colourful, like all other file icons

### ISSUE THREAD

**Issue by lorisobi** [files-community/files-uwp#1085]
The placeholder icon at the moment:

![At the moment](https://user-images.githubusercontent.com/28399150/84749918-e80a7a00-afba-11ea-9d76-b807379b52ab.png)
 

The blank file icon in Windows Explorer and old uwp explorer:

![image](https://user-images.githubusercontent.com/28399150/84750757-fdcc6f00-afbb-11ea-908a-1074b026b06b.png)

**Comment by yaichenbaum** [comment]
The placeholder should remain an outline as it gets replaced as soon as the real icon loads. We have updated the visuals to be a little more fluent.
