### ISSUE TITLE
Add a drop shadow to the Start Menu tile and splash screen to match official Fluent icons

### ISSUE THREAD

**Issue by Spyromaniac31** [files-community/files-uwp#1101]
**Describe the solution you'd like**
The Files UWP Start Menu tile should have a drop shadow that matches the other Fluent icons. This drop shadow would also be on the app splash screen, which the official Fluent icons also have.

**Additional context**
I have attached an assets folder with the drop shadow added, as well as a picture of how the shadow would look on the Start Menu
[Assets.zip](https://github.com/files-community/files-uwp/files/4795573/Assets.zip)
![Example](https://user-images.githubusercontent.com/55723056/84962182-766a2300-b0c3-11ea-9ec3-27bd23cad48e.png)

**Comment by yaichenbaum** [comment]
Merging with #1173.

**Comment by aldonsantoas** [comment]
its awesome
