### ISSUE TITLE
作者，您好。我遇到一个问题，无论使用quicklook的哪一个版本，我都无法预览files uwp中的任何文件（我安装所有的插件，且在资源管理器中预览没有问题），真心希望得到您的回复和帮助，祝好

### ISSUE THREAD

**Issue by Iuyitim** [files-community/files-uwp#1104]
**Describe the bug**
A clear and concise description of what the bug is and why it is more urgent than other issue reports. Can't answer this? Please return to the previous page and file a regular bug/feature report.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Comment by Jaiganeshkumaran** [comment]
This issue has been fixed with #1061 and will roll out to users when v0.11 is released.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
