### ISSUE TITLE
7-zip support

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/files-uwp#1105]
**Is your feature request related to a problem? Please describe.**
I often use 7-zip to create zip archives, because I can do everything in few clicks

**Describe the solution you'd like**
Add an integration in the context menu.

**Describe alternatives you've considered**
Adding the feature to create archives can be an alternative for someone, but not for me.

**Additional context**
![image](https://user-images.githubusercontent.com/43090263/85033129-e25e9100-b180-11ea-8404-109a35340fa3.png)

**Comment by yaichenbaum** [comment]
Merging with #174.

**Comment by yaichenbaum** [comment]
This has been implemented with #1754.
