### ISSUE TITLE
Translate language to Brazilian Portuguese

### ISSUE THREAD

**Issue by MichelEngel** [files-community/files-uwp#1106]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by MichelEngel** [comment]
Translate all language of Files UWP-Preview to Brazilian Portuguese

**Comment by XPoppyX** [comment]
Currently there is no one who can translate into Portuguese, if you can help it would be great.

**Comment by yaichenbaum** [comment]
@MichelEngel See this [page ](https://github.com/files-community/files-uwp/blob/master/Translator.md)for instructions for translating the app.
