### ISSUE TITLE
Open in Terminal + wt.exe + pwsh fails if path ends with backslash

### ISSUE THREAD

**Issue by cocoon** [files-community/files-uwp#1107]
**Describe the bug**
There is a bug with "Open in Terminal" when opening  for example "C:\\" in wt.exe that causes the following error:

```
[error 0x8007010b when launching powershell.exe']
```

It is tracked as issue here:
https://github.com/microsoft/terminal/issues/4571

The problem here is the backslash at the end in CurrentInstance.ViewModel.WorkingDirectory.

**To Reproduce**
1. Install and set "Windows Terminal" as fedault
2. Navigate to 'C:\' by clicking the drive on the left pane
2. Try to use "Open in Terminal"
3. See error

**Expected behavior**
The terminal should start with the selected path.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909
 - App version: v0.10.2.0
 - WT Version: 1.0.1401.0

**Additional context**
-

**Comment by hez2010** [comment]
Will be fixed via 37f6b73

**Comment by yaichenbaum** [comment]
This issue has been resolved with #1136 and will roll out with the next release.
