### ISSUE TITLE
can not use Quicklook in files-uwp

### ISSUE THREAD

**Issue by yhybulider** [files-community/files-uwp#1157]
i can not use Quicklook in files-uwp.
Hold down the space bar it doesn't react
![image](https://user-images.githubusercontent.com/48554508/85193660-3ee6bb00-b2fd-11ea-9313-0d8ea63b2e4c.png)

**Comment by Jaiganeshkumaran** [comment]
This issue has been fixed with #1061 and will roll out to users when v0.11 is released.
