### ISSUE TITLE
A bug when starting the exe file

### ISSUE THREAD

**Issue by mg-class** [files-community/files-uwp#1158]
when I start an exe file, files uwp is not responding.

**Comment by Jaiganeshkumaran** [comment]
Which version of Windows are you running?

**Comment by mg-class** [comment]
> 您正在运行哪个版本的Windows？

WIndows 10

**Comment by Jaiganeshkumaran** [comment]
By version, I mean the version number of Windows, not the name. You can view the version number by typing winver in the search box.

**Comment by mg-class** [comment]
1903 18362.657

**Comment by mg-class** [comment]
> By version, I mean the version number of Windows, not the name. You can view the version number by typing winver in the search box.

version 1903 (OS 18362.657)

**Comment by Jaiganeshkumaran** [comment]
Could you post the log file? I can't reproduce this issue.

**Comment by mg-class** [comment]
> By version, I mean the version number of Windows, not the name. You can view the version number by typing winver in the search box.

some exe files I can start, but some I can't

**Comment by mg-class** [comment]
> Could you post the log file? I can't reproduce this issue.

Oh, some permissions are not open, so this bug appears, sorry

**Comment by yaichenbaum** [comment]
@mg-class Have you given Files UWP permission to access the file system?
