### ISSUE TITLE
Shortcut for renaming files

### ISSUE THREAD

**Issue by thetek42** [files-community/files-uwp#1162]
**Is your feature request related to a problem? Please describe.**
In Windows Explorer, you can easily rename files by pressing "F2".

**Describe the solution you'd like**
When I press "F2", I should be able to rename the file

**Comment by XPoppyX** [comment]
renaming with F2 actually works in the app
![rename](https://user-images.githubusercontent.com/61259627/85202603-7ccfe900-b2d5-11ea-970e-01543a4f66d7.gif)

**Comment by thetek42** [comment]
It doesn't work when the "double tap to rename" feature is off. When it is on, it does.

**Comment by XPoppyX** [comment]
there's already an issue posted about that: #651

**Comment by yaichenbaum** [comment]
Merging with #651.
