### ISSUE TITLE
quicklook支持问题

### ISSUE THREAD

**Issue by hc981111** [files-community/files-uwp#1163]
在系统从windows专业版1909升级到2004时，此文件管理器无法使用quicklook，但在windows自带管理器中可以正常使用quicklook

**Comment by Jaiganeshkumaran** [comment]
This issue has been fixed with #1061 and will roll out to users when v0.11 is released.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
