### ISSUE TITLE
UI improvement for file properties in list view / tile view

### ISSUE THREAD

**Issue by jayasio** [files-community/files-uwp#1170]
**Is your feature request related to a problem? Please describe.**

When a user browses through the files in a file explorer, they try to identify the file based on two things:
1. Name of the file
2. Icon/thumbnail of the file

In the current app, all the properties shown are of the same importance (name, size, file type...)
While yes, the information is helpful and is displayed at all times, they are only necessary when the user wants to know it.

**Describe the solution you'd like**

Except for the name, other properties can be of a lesser opacity, so that the name and icon/thumbnail stand out better.

![Current](https://user-images.githubusercontent.com/34701149/85215248-6720f900-b393-11ea-9bfe-f53e2de33d92.png)
Current implementation

![Proposed](https://user-images.githubusercontent.com/34701149/85215249-72742480-b393-11ea-9524-6287c1310952.png)
Proposed implementation

While the exact color values are up for further discussion, I immediately notice that there is a huge improvement in the visual quality of the screen.

![Current](https://user-images.githubusercontent.com/34701149/85215281-ee6e6c80-b393-11ea-9217-b668ad80bfad.png)
Current implementation

![Proposed](https://user-images.githubusercontent.com/34701149/85215282-f5957a80-b393-11ea-8dec-2627f9f29d86.png)
Proposed implementation

The same applies to the light theme as well, though the difference it makes seems lesser compared to the dark theme. 

![Image 2](https://user-images.githubusercontent.com/34701149/85215403-bbc57380-b395-11ea-8d62-f97f83c47b5b.png)
Current implementation

![Group 5](https://user-images.githubusercontent.com/34701149/85215402-b405cf00-b395-11ea-8363-f88cb19f666d.png)
Proposed implementation

**Describe alternatives you've considered**

This is a generic UI improvement and there are no alternatives I could think of.
Instead of making secondary information less prominent (reducing opacity/grey out), the primary information can be made more prominent (by making the name bolder/bigger) but that doesn't seem visually elegant and results in unnecessarily complicated UI.

**Comment by XPoppyX** [comment]
I had already tested with a darker color, the problem was that depending on the accent color, when selecting a file it did not look very good:
![Captura de pantalla (224)](https://user-images.githubusercontent.com/61259627/85215632-a0347b80-b349-11ea-98de-555ffe791e30.png)
but if anyone can solve that it would be great

**Comment by jayasio** [comment]
I think this issue is because the text is just 'grey'. If you change the opacity (transparency) instead, the background color bleeds through the text and gives a pinkish tint instead.

![Group 8](https://user-images.githubusercontent.com/34701149/85215730-51fb9880-b39a-11ea-994b-40a8c419aeab.png)

This is an approximate recreation, and the opacity percentage is up for discussion and accessibility tests.

Again, I don't know if the code implementation allows for this, but this is a very common UI pattern.

**Comment by XPoppyX** [comment]
Test
![Anotación 2020-06-21 081919](https://user-images.githubusercontent.com/61259627/85224374-01833b80-b398-11ea-991d-5eef58298b78.png)
![Anotación 2020-06-21 081948](https://user-images.githubusercontent.com/61259627/85224377-034cff00-b398-11ea-9c77-494a6235c1e4.png)

**Comment by jayasio** [comment]
LGTM :)

**Comment by XPoppyX** [comment]
after more testing:

**White 50%** looks good in dark mode

**Black 50%** looks good in light mode

**Comment by jayasio** [comment]
So, I ran some rough accessibility tests with given percentages and the app's colors. Slight change to 54% or 55% opacity for white passes WCAG AA requirements.. since white is too bright on a screen, the text opacity needs to be a bit higher. I think 54% for both dark and light modes is good.

**Comment by yaichenbaum** [comment]
I am now working on this issue, instead of changing opacity or color I am looking at changing the font weight.

**Comment by yaichenbaum** [comment]
After spending some time on this and testing changes to the font weight, I have come to the conclusion that changing the font weight is not the correct path here.

**Comment by mdtauk** [comment]
I would suggest using a 60% opacity to try to improve the Color Contrast for accessibility
