### ISSUE TITLE
Refining the app icon

### ISSUE THREAD

**Issue by jayasio** [files-community/files-uwp#1173]
**Is your feature request related to a problem? Please describe.**
Following the new Fluent design icon redesigns, the Files UWP icon has been redesigned. Most icons have some sort of gradient rectangles. 

<img width="135" alt="apps 26471 13649428968955623 1f70e565-3554-409e-981d-f74330bee560" src="https://user-images.githubusercontent.com/34701149/85217977-95aecc00-b3b3-11ea-9b93-3296bfd4f1ab.png">
This is the current icon and the colors range from light yellow to light ochre-ish brown. The colors vary only in their intensity and they look **muddy.** One of the common techniques used by illustrators in these situations is to also shift the hue of the colors to the warmer side as it gets darker.

--

**Describe the solution you'd like**

I propose a slight change in the icon colors following the above technique.
![Group 18](https://user-images.githubusercontent.com/34701149/85218055-208fc680-b3b4-11ea-883b-085dab92baf2.png)
The newer gradient is much more harmonious. 

![Group 19](https://user-images.githubusercontent.com/34701149/85218105-85e3b780-b3b4-11ea-9ed4-e7bcd8d9495c.png)
The change is very subtle but the icon feels brighter than before. The difference becomes apparent when zoomed in and both versions are compared together.

My technical proposal ends here. Following are opinionated improvements:

One more issue I have is that the lines between colors are too strong. A transparent overlay smoothens out the color and provides some character to the icon.
![c](https://user-images.githubusercontent.com/34701149/85218388-83369180-b3b7-11ea-8edb-6da7ec6a442e.png)

Icon B is opinionated and I hope some discussion happens.

--

![Group 22](https://user-images.githubusercontent.com/34701149/85218475-4d45dd00-b3b8-11ea-8ab6-0b80fd2c28b1.png)
Proposed Icon A

![Group 23](https://user-images.githubusercontent.com/34701149/85218480-53d45480-b3b8-11ea-8b55-f0b9e15ea198.png)
Proposed Icon B

Also, these are approximate versions of the icon. If required I can make the final icons, if someone could point me to the original file. :)

**Comment by jayasio** [comment]
#1101 is a related issue. :)

**Comment by yaichenbaum** [comment]
This is great feedback, I will share it with a designer for some feedback before updating this issue.

**Comment by yaichenbaum** [comment]
@jayasio Do you have any concepts that include the blue holder like the current icon has? https://github.com/files-community/files-uwp/blob/master/Files.Package/Assets/Files%20UWP%20Icon.png

**Comment by jayasio** [comment]
@yair100 I didn't know the blue holder version existed; I'm using the beta version.
I've added the blue holder in the proposed icons. I just shifted the colors subtly so that the blues are less "greener".

![Group 37](https://user-images.githubusercontent.com/34701149/85239560-e37a1180-b451-11ea-812f-ae5b8394170a.png)
The above three are in the current icon and below three are proposed.

I've also rounded the corners a bit more to match the corners of the folder part of the icon.

![Group 45](https://user-images.githubusercontent.com/34701149/85242080-a4e95480-b45b-11ea-9400-fd1e9357eee4.png)
![Group 49](https://user-images.githubusercontent.com/34701149/85242087-a9157200-b45b-11ea-8f6a-4bb2957367a3.png)
With shadows

On blue background
![Group 48](https://user-images.githubusercontent.com/34701149/85242085-a7e44500-b45b-11ea-9174-799e3c7f2efa.png)
![Group 50](https://user-images.githubusercontent.com/34701149/85242091-ac106280-b45b-11ea-889d-0e02cdf06eef.png)
With shadows

Also, I find the blue holder to be a bit much in small sizes; but that's another issue (can be addressed when someone proposes a redesign).

**Comment by yaichenbaum** [comment]
@jayasio Great work! It looks like the round corners on the right of the tab is missing, was the on purpose?

**Comment by jayasio** [comment]
Oh right, no. The above icons were made roughly, the proportions are also a bit different from previous design. I was hoping someone could point me to the original file so that changes could be made right there. 

I'll change it in the above design nonetheless.

**Comment by jayasio** [comment]
@yair100 what do you think? A or B? Maybe people could vote? 
Also, are specifications available for app icons so that I could contribute?

**Comment by yaichenbaum** [comment]
@jayasio We are definitely going for something closer to A. Reviewing these icons and making sure they are pixel perfect will take some time.

**Comment by XPoppyX** [comment]
![concept1](https://user-images.githubusercontent.com/61259627/85731172-48d73800-b6c8-11ea-9bb9-b3831f5ada49.png)
![concept2](https://user-images.githubusercontent.com/61259627/85731177-496fce80-b6c8-11ea-8da2-cf41cb29759a.png)

**Comment by yaichenbaum** [comment]
@XPoppyX Unfortunately we can't use that icon as it's too close to the File Explorer icon.

**Comment by yaichenbaum** [comment]
@jayasio We really like the work you did with proposal A, do you have a Figma file with the icon that you can share?

**Comment by jayasio** [comment]
The Figma file is in this .zip folder :)

[Logo.zip](https://github.com/files-community/files-uwp/files/4835041/Logo.zip)

**Comment by yaichenbaum** [comment]
@jayasio Thank you! We are looking forward to using the new icon when the app leaves become generally available.

**Comment by lukeblevins** [comment]
@yair100 This is complete now in our active development branch, right?
