### ISSUE TITLE
Unused usb ports in Windows show up under 'Drives' in the left column and cause problems with permissions

### ISSUE THREAD

**Issue by joshl8n** [files-community/files-uwp#1178]
The unused ports in my sdcard reader are greyed out in Windows

![Annotation 2020-06-21 025355](https://user-images.githubusercontent.com/18693995/85220742-66746c80-b36b-11ea-8348-a8d150e5df00.png)

In files-uwp, these show up in the left column under 'Drives' . When you click on them you receive a prompt asking you to grant permissions to display the files. The program already has permissions of course, there are just no files to access in an empty drive. 

![image](https://user-images.githubusercontent.com/18693995/85220815-f1556700-b36b-11ea-8bbe-c804552541c6.png)

**Comment by yaichenbaum** [comment]
@joshl8n Can you still reproduce this issue with v0.11?

**Comment by duke7553** [comment]
@joshl8n This may be fixed in v0.11
