### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by TopApex** [files-community/files-uwp#1179]
通过Microsoft Store升级到开发版的最新版时，打开文件的时候很容易卡退

**Comment by yaichenbaum** [comment]
@TopApex What version of the app are you using?

**Comment by TopApex** [comment]
> @TopApex您正在使用哪个版本的应用程序？

0.10.2.0

**Comment by yaichenbaum** [comment]
@TopApex Can you still reproduce this issue in the latest version from the Microsoft Store?
