### ISSUE TITLE
the app doesn't launch at all.

### ISSUE THREAD

**Issue by Badr-Zh** [files-community/files-uwp#1182]
as the title suggests, the app never launches. I've had this problem since earlier versions. I had the app store version before and I just uninstalled it today and installed the latest version from Github but I sill have the same problem. I click on launch, the logo appears then crashes immediately.
app version: 0.10.2.0
windows version: 2004 os build 19041.329

**Comment by hez2010** [comment]
Could you please paste your logs which located in %localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState ?
There're log files debug.log and debug_fulltrust.txt which could help us investigate this problem.

**Comment by Jaiganeshkumaran** [comment]
@Badr-Zh I was having the same issue. I fixed it by changing the Build Action for the file "Files\Assets\terminal\terminal.json" from "None" to "Content" in my local branch (plus reinstalling the app afterwards).

**Comment by Kaedin** [comment]
Same issue here with app version 0.10.4.0.

**Comment by Badr-Zh** [comment]
I've fixed the issue. My issue was a Microsoft store issue, all Microsoft store apps suffered the same problem. now the app works fine. here is how I fixed it, I just typed these two commands:
 CMD: wsreset
 and in PowerShell I typed this:  
 Get-AppXPackage | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

**Comment by Kaedin** [comment]
> I've fixed the issue. My issue was a Microsoft store issue, all Microsoft store apps suffered the same problem. now the app works fine. here is how I fixed it, I just typed these two commands:
> CMD: wsreset
> and in PowerShell I typed this:
> Get-AppXPackage | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

Tried the same and 'Files UWP - Preview' main UI opened for 2 seconds but then closed immediately. And subsequent tries forcibly close again before reaching the main UI.

[
[debug.txt](https://github.com/files-community/files-uwp/files/4817142/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/4817143/debug_fulltrust.txt)

](url)

**Comment by chuchanpr** [comment]
Same issue with 0.10.4.0. #1201 

[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/4821259/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/files-uwp/files/4821260/debug.txt)

**Comment by yaichenbaum** [comment]
@chuchanpr Do you have an Android device connected to your computer?

**Comment by Kaedin** [comment]
After the recent update to version: 0.10.6.0, the application starts properly at least in my case.

**Comment by duke7553** [comment]
Sorry! I understand how frustrating it can be to see the app refuse to launch. Luckily, this issue is now resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
