### ISSUE TITLE
"Open", "Open with", "open in new tab / window" and "pin to sidebar" no longer appear in the item context menu

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#1185]
Only these options appear:
- share
- cut
- copy
- delete
- rename
- properties

**Comment by BuraChuhadar** [comment]
I will take a look at this please assign it to me.

**Comment by XPoppyX** [comment]
@yaichenbaum

**Comment by BuraChuhadar** [comment]
https://github.com/files-community/files-uwp/pull/1186

**Comment by yaichenbaum** [comment]
This issue should be resolved with #1186.

**Comment by XPoppyX** [comment]
now it crashes every time I open the app, and these exceptions occur:

![Anotación 2020-06-21 173119](https://user-images.githubusercontent.com/61259627/85236448-05d94400-b3ec-11ea-887c-283562a001be.png)
----------------------------------------------------------
![Anotación 2020-06-21 181228](https://user-images.githubusercontent.com/61259627/85236449-070a7100-b3ec-11ea-89ae-ebc5a85a7a85.png)
-----------------------------------------------------------
![Anotación 2020-06-21 181859](https://user-images.githubusercontent.com/61259627/85236451-08d43480-b3ec-11ea-8c2e-0288bb02fc76.png)

I don't know if it's just my visual studio being problematic
