### ISSUE TITLE
"Recycle bin" no longer appears translated

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#1191]
It no longer appears translated in my language in:
- Sidebar
- Tab header
- Path

![Anotación 2020-06-21 222045](https://user-images.githubusercontent.com/61259627/85243031-a4769c80-b40e-11ea-8176-456266543e68.png)

**Comment by gave92** [comment]
@XPoppyX thanks for the report.
Do you mind trying the following?
- Uninstall File Dev
- Install version from here: #1137
- Open the app *at least twice*
Is the issue gone? Thanks!

**Comment by XPoppyX** [comment]
after reinstalling testing other things, now I realize that it appears correctly
