### ISSUE TITLE
Quick Access Toolbar

### ISSUE THREAD

**Issue by JavaAppleJr** [files-community/files-uwp#1202]
**Is your feature request related to a problem? Please describe.**
**Personally I think it's a problem. I was disappointed to see that there was no quick access toolbar. This is one of the key features of (the stock) File Explorer. I would love to see it added**

**Describe the solution you'd like**
**I would like to see the Quick Access Toolbar with all of it's features such as: Home, Share, View, etc.**
**Describe alternatives you've considered**
**I don't have an answer for this.**
**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?
**Nothing...**

**Comment by Jaiganeshkumaran** [comment]
Files UWP originally had a quick access toolbar however, they removed it for the new design.

**Comment by JavaAppleJr** [comment]
Was it replaced?

**Comment by Jaiganeshkumaran** [comment]
No. Currently the only way to access the options is to right-click the file. However, there’s a proposal to add right click options in the menu. See #1004.

**Comment by yaichenbaum** [comment]
Merging with #1004.
