### ISSUE TITLE
Entering a URI that's not a path should use the system launcher

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#1205]
**Is your feature request related to a problem? Please describe.**
Not really. In File Explorer, when you enter any URI that's not a path, it will launch it using the system launcher. That doesn't work in FIles UWP.

**Describe the solution you'd like**
When FIles UWP can't navigate to the given string, it should try to use the system launcher to launch it.

**Comment by tsvietOK** [comment]
@Jaiganeshkumaran What exact string you are trying to launch?

**Comment by Jaiganeshkumaran** [comment]
I was actually trying open a website since in Explorer it works.
