### ISSUE TITLE
Icon not shown for custom context menu items

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#1210]

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Can you please provide more details such as the app version and the context menu you are referring to here?

**Comment by Jaiganeshkumaran** [comment]
I'm referring to the custom context added by applications. I am running the latest version of Files UWP cloned from GitHub (0.10.2).

**Files UWP:**
![திரைப்பிடிப்பு (1)](https://user-images.githubusercontent.com/45227503/85418749-cac34600-b58e-11ea-9b31-172289fc28aa.png)

**File Explorer:**
![திரைப்பிடிப்பு (3)](https://user-images.githubusercontent.com/45227503/85419695-07dc0800-b590-11ea-98cc-c7b20529b63a.png)

**Comment by yaichenbaum** [comment]
This has not been implemented yet, merging with #174.

**Comment by yaichenbaum** [comment]
This has been implemented with #1754.
