### ISSUE TITLE
Pinning folder to the sidebar makes app crash

### ISSUE THREAD

**Issue by yarikv8601** [files-community/files-uwp#1216]
**Describe the bug**
Pinning folder to the sidebar makes app crash even after resetting app settings and reinstalling it.

**To Reproduce**
1. Open Files UWP.
2. Right click on the folder with media files (folder with music files in my case).
3. Choose 'Pin to sidebar'.

**Expected behavior**
No crash.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 19041.329
 - App version: 0.10.4.0

**Comment by yaichenbaum** [comment]
This has been fixed in `master` and will roll out with the next beta build.
