### ISSUE TITLE
Suggestion For Files UWP - Preview

### ISSUE THREAD

**Issue by AngerZeur** [files-community/files-uwp#1220]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by AngerZeur** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/60907149/85540716-b95d5680-b5ed-11ea-8b4d-4cbbb1271881.png)
Put all this information in the Application Properties For the Files UWP - Preview

**Comment by XPoppyX** [comment]
any specific info? these are the ones already shown:
![Anotación 2020-06-24 075708](https://user-images.githubusercontent.com/61259627/85551773-54573000-b5f0-11ea-9f30-18c52c237bcd.png)

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
