### ISSUE TITLE
Crash on pinning Recycle Bin to sidebar

### ISSUE THREAD

**Issue by TailyFair** [files-community/files-uwp#1230]
**Describe the bug**
When pinning recycle bin to sidebar, program crashes. And app needs to be reinstalled afterwards.

**To Reproduce**
1. Enable Recycle bin
2. Open Recycle bin folder
3. Open context menu and press "Pin directory to sidebar"

**Expected behavior**
I don't think this option should be available for recycle bin or at least nothing should happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/27275873/85737494-1a794d00-b708-11ea-85e8-938aa750d540.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909
 - App version: v0.10.6.0

**Comment by yaichenbaum** [comment]
Merging with #1089.
