### ISSUE TITLE
Discontinuous sidebar shadow

### ISSUE THREAD

**Issue by Elttob** [files-community/files-uwp#1236]
There's a spot in the corner of the UI where the shadow cuts out, where the main area and tab bar meet:

![image](https://user-images.githubusercontent.com/11815374/85804875-b0ca6480-b742-11ea-8cb6-b8ae6e82ca62.png)

Tested on light theme, unsure if it's there on dark theme.

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, unfortunately fixing this will be pretty difficult. If anyone wants to help, let us know so we can assign you the issue.

**Comment by soumyamahunt** [comment]
After the tab ui change this doesn't seem to exist anymore.
