### ISSUE TITLE
Add recently opened directories to the taskbar jumplist

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/files-uwp#1238]

**Comment by Jaiganeshkumaran** [comment]
@duke7553 Could you assign me on this issue.

**Comment by Jaiganeshkumaran** [comment]
Although File Explorer only pins quick access folders and recent folders to the taskbar jumplist, we can also pin drives as well.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran I don't think we need to pin items to the taskbar jumplist. I think adding them will be enough.

**Comment by Jaiganeshkumaran** [comment]
Sorry, I meant by adding not pinning.

**Comment by Jaiganeshkumaran** [comment]
Should we only add recent folders are should we also add folders in the sidebar?

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran I think we should start by only adding recent folders.

**Comment by Jaiganeshkumaran** [comment]
For the icons, should we show to monochrome icons of the color icons?

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Color icons will probably work best.
