### ISSUE TITLE
After canceling a permanent deletion, if you press "shift + del" again in the same file, "permanently delete" is no longer checked again

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#1253]
Now the keyboard shortcuts work fine of course, the problem is when you cancel the permanent delete dialog, and you press "shift + del" again on the same file **without** deselecting and selecting again.

Sometimes it can be rechecked correctly.

**In the gif it looks more as if it were unchecked immediately**

![check](https://user-images.githubusercontent.com/61259627/85910723-98178880-b7ee-11ea-831a-a9aac4d77ae4.gif)

**Comment by duke7553** [comment]
@XPoppyX Thanks for catching this. 

Are the keyboard accelerators any better for you in v0.11?

**Comment by XPoppyX** [comment]
yes they work correctly now :) , this issue I added is the only problem

**Comment by XPoppyX** [comment]
fixed with #1349
