### ISSUE TITLE
Show hidden files, and show drive letters options re greyed out

### ISSUE THREAD

**Issue by fizify** [files-community/files-uwp#1261]
**Describe the bug**
Show hidden files, Show drive letters in the Files and Folders menu of options are greyed out and 'untogglable'

**To Reproduce**
1. Go to Settings
2. Click on Files and Folders item
3. See Show hidden files option and Show drive letters option greyed out

**Expected behavior**
The options should have been togglable
**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 19042.330] (20H2)
 - App version: [v0.11.0]

![image](https://user-images.githubusercontent.com/42074408/85916194-dc953980-b86b-11ea-99c1-db7c7e395dee.png)

**Comment by Jaiganeshkumaran** [comment]
They are grayed out because they aren't implemented yet.

**Comment by fizify** [comment]
okay jaiganeshkumaran good to know and sorry for the inconvenience!
