### ISSUE TITLE
Properties window not working for recycle bin

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#1263]
**Describe the bug**
Properties option isn't working for the recycle bin. This only occurs for the folder itself and not deleted files on it.

**To Reproduce**
1. Enable recycle bin support
2. Navigate to recycle bin
3. Right-click and hit navigate
4. Files UWP will crash 

**Expected behavior**
It should show the properties of the recycle bin.

**Desktop:**
 - OS Version: Windows 10 Insider Preview Build 20152.1000
 - App version: v0.11.0

**Comment by gave92** [comment]
@Jaiganeshkumaran if you're experiencing a crash when opening recycle bin properties, could you post the contents of debug.txt and debug_fulltrust.txt? (possibly right after the problem occours)
Thanks!

**Comment by Jaiganeshkumaran** [comment]
Here you go.

[debug.txt](https://github.com/files-community/files-uwp/files/4841523/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/4841524/debug_fulltrust.txt)
