### ISSUE TITLE
Only shows 6 of 11 drives. Missing some internal, some external USB drives; the 6 are also a mix. "This PC" listing all drives and space would be a nice feature to retain

### ISSUE THREAD

**Issue by wireloose** [files-community/files-uwp#1268]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by yaichenbaum** [comment]
@wireloose Thank you for opening this issue, we usually expect users to fill out the issue template with more details. Please reopen this issue when you have filled out the template to the best of your ability.
