### ISSUE TITLE
An app with potential - saving tab sets would be a winnter

### ISSUE THREAD

**Issue by jlnwcic** [files-community/files-uwp#1275]
**Describe the solution you'd like**
Been using tabbed-based file managers since Windows 3.  I use 3 currently, each with pluses. This app would be a great replacement if once you had a set of tabbed folders open, you could save the set.  Ie:  Work Files, Financial, Pictures, Media, etc.

**Describe alternatives you've considered**
I use Directory Opus heavily, Groupy by Stardock, FreeCommander. Directory Opus is memory heavy, Groupy is simple but lacks features, and FreeCommander is nice but limited.

**Comment by yaichenbaum** [comment]
Merging with #381.
