### ISSUE TITLE
UI Broken

### ISSUE THREAD

**Issue by handoi987654** [files-community/files-uwp#1278]
![Capture](https://user-images.githubusercontent.com/40176363/85942042-fc525d80-b950-11ea-8199-5c29b0af5476.PNG)

**Comment by yaichenbaum** [comment]
@handoi987654 Do you have steps to reproduce this issue?

**Comment by Jaiganeshkumaran** [comment]
@handoi987654 Which version of Windows are you running? I've seen such issues in other UWP apps before especially with Groove Music.

**Comment by yaichenbaum** [comment]
We are working on some changes to the tab interface which will solve this issue when it rolls out.
