### ISSUE TITLE
view contents of *multiple* sub-folders

### ISSUE THREAD

**Issue by mgkai** [files-community/files-uwp#1279]
Problem (of any Windows file manager I know) : to view /manage content of a sub-folder, you have to go inside of the sub-folder.
If you then realize you need to view content of another sub-folder, you have to leave the sub-folder / go up again to previous level, for there switch over to next subfolder. Is a lot of going back and forth. Or wrestle with multiple windows.
Solution, cf Mac file manager, since minimum OS 7: Sub-folders are displayed with triangles to their left, and from these, sub-folders and display of their content can be expanded and collapsed (there is even a keyboard shortcut!), for quick overview / file management across various subfolders.

**Comment by yaichenbaum** [comment]
While we are not planning on adding an option to view subfolders in the sidebar, we can explore adding an option to see sub folders by clicking on the arrows on the navigation bar.

**Comment by yaichenbaum** [comment]
The next update will include breadcrumbs in the navigation bar, this will allow you to easily move to another directory with greater speed.
