### ISSUE TITLE
Selection moves up when deleting files

### ISSUE THREAD

**Issue by ZoroNasr** [files-community/files-uwp#1280]
Back to the top of the page when item is deleted

1. Go to any folder containing multiple files
2. delete one item from the middle of the folder
3. the selection moves directly to the top of the folder

I would prefer for the selection to move to the next file, not to the top where I have to move down again.

 - OS Version: [10.0.19041 Build 19041]
 - App version: [v0.10.2.0]

**Comment by XPoppyX** [comment]
I suppose it happens when you confirm the deletion with "enter" and in grid view

**Comment by ZoroNasr** [comment]
It happens when i confirm with "Enter", but i am in Tiles view. Is there a way to fix it ?, it doesn't go up when i use the mouse to confirm

**Comment by yaichenbaum** [comment]
@ZoroNasr Is this still an issue in v0.13.1?

**Comment by ZoroNasr** [comment]
no, not anymore :)
On 8/26/2020 1:34:50 AM, Yair Aichenbaum <notifications@github.com> wrote:
@ZoroNasr [https://github.com/ZoroNasr] Is this still an issue in v0.13.1?
