### ISSUE TITLE
Recycle bin menu opens for current tab(not recycle bin) if Recycle bin is opened in another tab

### ISSUE THREAD

**Issue by tsvietOK** [files-community/files-uwp#1283]
**To Reproduce**
1. Open any folder in one tab
2. Open Recycle bin in another tab
3. Right click on empty space in Recycle bin tab
4. Right click on empty space in first tab in regular folder
5. Recycle bin context menu appears

**Expected behavior**
Expected to be opened normal context menu for folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/20501502/85949214-3413d200-b95e-11ea-9a97-3ee1783ff1a5.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.329]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by gave92** [comment]
Am I doing the steps correctly?
![ezgif com-optimize](https://user-images.githubusercontent.com/9673091/86043834-854cc000-ba49-11ea-8e1c-b758dd542445.gif)

**Comment by tsvietOK** [comment]
@gave92 yes, bug still exists for me.
