### ISSUE TITLE
No network drives

### ISSUE THREAD

**Issue by PaPaTheGMan** [files-community/files-uwp#1290]
**Describe the bug**
**My network drives aren't listed and even if I type in the drive letter, no files are found.**

**To Reproduce**
1. Go to '...' - **open app**
2. Click on '....' **drive letter area**
3. Scroll down to '....' **no scroll, just type in a valid network drive letter and press Enter**
4. See error - **list shows "This folder is empty"**

**Expected behavior**
**I'm expecting to see a list of files, the same as when I type in C;\.  See attached Windows Explorer image.  This is the list of files that should show.**

**Screenshots**
**UWP Image:**
![image](https://user-images.githubusercontent.com/57098412/85953593-87c2f300-b93f-11ea-9b17-18c1d3595709.png)
**Windows Explorer Image:**
![image](https://user-images.githubusercontent.com/57098412/85953624-c3f65380-b93f-11ea-87f2-a0ad9ccaa6ea.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175] - **Microsoft Windows 10 Professional (x64) Build 19041.329 (2004/May 2020 Update)**
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
**Problem occurs every time app is run**

**Comment by yaichenbaum** [comment]
Merging with #642.
