### ISSUE TITLE
Windows Terminal Access Doesn't Work

### ISSUE THREAD

**Issue by PaPaTheGMan** [files-community/files-uwp#1291]
**Describe the bug**
**When I attempt to 'OPen In Terminal' an error screen comes up.**

**To Reproduce**
1. Go to '...' - **open app**
2. Click on '....' **any drive, then the '...' on the right.**
3. Scroll down to '....' **"Open in Terminal..." and click.**
4. See error - **A terminal windows pops up with a "[error 0x8007010b when launching `cmd.exe']" error.**

**Expected behavior**
**I'm expecting to have a new Termiknal windows anchored at hte Drive/Folder chosen..**

**Screenshots**
**Error screen**
![image](https://user-images.githubusercontent.com/57098412/85953992-4b44c680-b942-11ea-9258-08c3cfb8c4f6.png)

**Current Settings**
![image](https://user-images.githubusercontent.com/57098412/85953979-31a37f00-b942-11ea-80a3-5159a92beed0.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175] - **Microsoft Windows 10 Professional (x64) Build 19041.329 (2004/May 2020 Update)**
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
**I notice that the error refers to 'cmd.exe' when I'm actually configured to open Windows Terminal (wt.ete).**

**Comment by duke7553** [comment]
@PaPaTheGMan Can you please post your terminal configuration?

**Comment by PaPaTheGMan** [comment]
Please close, the issue is fixed.  Thanks.
