### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by stuartcamposg** [files-community/files-uwp#1296]
**Is your feature request related to a problem? Please describe.**

When exploring files, text is too big (or at least bigger than the size we're used to in the built-in files explorer)

**Describe the solution you'd like**

You may consider having a "text size" slider and maybe an additional "separation between items" slider in the settings.

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

I'm using a desktop, Windows 10, FHD screen.
![Files UWP feedback](https://user-images.githubusercontent.com/67567905/85966377-3178a300-b985-11ea-8070-3ca4847043aa.png)

**Comment by duke7553** [comment]
@stuartcamposg We have some tweaks coming to the default text sizing soon for the DataGrid. I'll keep the slider idea in mind
![image](https://user-images.githubusercontent.com/20365014/86302689-6bd97e80-bbd7-11ea-8f59-dd61f7479ab0.png)

**Comment by yaichenbaum** [comment]
This issue should be solved with the latest version in the Microsoft Store.
