### ISSUE TITLE
Some disks are not visible.

### ISSUE THREAD

**Issue by JettFlat** [files-community/files-uwp#1299]
Some disks are not visible.
![Снимок экрана (4)](https://user-images.githubusercontent.com/45435662/86009134-80284a80-ba22-11ea-9157-052ee3446582.png)

Windows 10 [2004 19041.331]
App version: [v0.10.2.0]

**Comment by Jaiganeshkumaran** [comment]
The issue has been fixed with version 0.11 and will roll out to users soon.
