### ISSUE TITLE
Powertoys

### ISSUE THREAD

**Issue by RDavidN** [files-community/files-uwp#1300]
I do a lot of batch image resizing but powertoys doesn't seem to be linking to Files UWP. 
Maybe I'm missing something, but it's a feature I'd dearly like to see in this very svelt app.
Cheers

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

I ACKNOWLEDGE THE FOLLOWING BEFORE PROCEEDING:
1. If I delete this entire template and go my own path, the core team may close my issue without further explanation or engagement.
2. If I list multiple bugs/concerns in this one issue, the core team may close my issue without further explanation or engagement.
3. If I write an issue that has many duplicates, the core team may close my issue without further explanation or engagement (and without necessarily spending time to find the exact duplicate ID number).
4. If I leave the title incomplete when filing the issue, the core team may close my issue without further explanation or engagement.
5. If I file something completely blank in the body, the core team may close my issue without further explanation or engagement.

All good? Then proceed!
-->

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Jaiganeshkumaran** [comment]
Related to #1304

**Comment by yaichenbaum** [comment]
@RDavidN Thank you for opening this pull request. PowerToys will be available when #174 is implemented.

**Comment by yaichenbaum** [comment]
This has been implemented with #1754.
