### ISSUE TITLE
[INFO] - Opinions on Files UWP

### ISSUE THREAD

**Issue by gave92** [files-community/files-uwp#1302]
In case you haven't seen it, at the following link there's an article by [Windows Central on Files UWP](https://www.windowscentral.com/files-uwp-preview-stunning-start-uwp-file-explorer).
Comments might be useful.

**Comment by lampenlampen** [comment]
A german article about files on [WindowsUnited.de](https://windowsunited.de/files-uwp-moderner-datei-explorer-fuer-windows-10/)

**Comment by yaichenbaum** [comment]
Thank you for sharing these links! We will keep listening to user feedback to improve the app.
