### ISSUE TITLE
Recycle bin bugs

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#1305]
- Sometimes right-clicking an item will show menu items for a regular folder
- Deleting files doesn't work always
- After unpinning the recycle bin from the sidebar, you can no longer access the recycle bin by entering Shell:RecycleBinFolder in the path box since it turns off recycle bin support. Unpinning shouldn't disable recycle bin support.

**Comment by yaichenbaum** [comment]
Merging with #1089.
