### ISSUE TITLE
Right-clicking on drives shows "Empty recycle bin" button after right-clicking on recycle bin

### ISSUE THREAD

**Issue by jayasio** [files-community/files-uwp#1307]
**Describe the bug**
The context menu for the drives on the sidebar is the same as the recycle bin's context menu after right-clicking on recycle bin

**To Reproduce**
0. Open Files UWP preview from Microsoft store
1. Right-click on recycle bin
2. Now right-click on drive button on the sidebar
3. The context menu has the "Empty recycle bin" button

**Expected behavior**
The context menu shouldn't have the button.

**Screenshots**
![Screenshot (50)](https://user-images.githubusercontent.com/34701149/86099968-cb4f6580-bad5-11ea-885e-a56a4a7c59fe.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19042.330]
 - App version: [v0.11.0.0]

**Comment by XPoppyX** [comment]
Does the bug persist after #1286?

**Comment by tsvietOK** [comment]
Fixed in #1286 and fix will be available with the next release.
