### ISSUE TITLE
Files uwp is not good at transferring files

### ISSUE THREAD

**Issue by battenmufang** [files-community/files-uwp#1312]
Cannot drag directly into the folder, can only be transferred through Ctrl + C or Ctrl + X

**Comment by Dylan-Osborne** [comment]
Drag and drop is supported, you just have to select the files before dragging them

**Comment by battenmufang** [comment]
![)KQ4(1`CSJ`E5INC1U5S{9C](https://user-images.githubusercontent.com/67583271/86125744-bbed0e00-bb0f-11ea-8f2d-7ee172e51669.png)
NO,It didn't work.

**Comment by Talisman39ar** [comment]
Drag and drop isn't working for me between Files UWP windows or tabs (see screenshot)

I can drag and drop things to Desktop or File Explorer windows, however upon mouse release a pop-up menu appears asking if I want to move, copy or cancel, which isn't what I would expect (maybe nice as an option, but shouldn't be default behavior IMO)

![files uwp drag drop](https://user-images.githubusercontent.com/61295915/86614760-7b631980-bf81-11ea-9f9d-3aa419d86665.jpg)

**Comment by Jaiganeshkumaran** [comment]
Currently, you can only drag a file/folder to a subfolder and not to the sidebar.

**Comment by Talisman39ar** [comment]
> Currently, you can only drag a file/folder to a subfolder and not to the sidebar. My mouse cursor was where the Stop symbol is.

I was dragging it to the main area, not to the side bar (I probably cropped the screenshot too tight)

**Comment by yaichenbaum** [comment]
Drag and drop should be implemented in the latest version of Files UWP.
