### ISSUE TITLE
way to show shortcuts in folders

### ISSUE THREAD

**Issue by RevRock97** [files-community/files-uwp#1313]
Good morning,
Is there or am I missing a way to show shortcuts in folders? Files UWP doesn't help me if they won't display in the folder as I have a couple folders that are document shortcuts. That would make Files UWP something that would make this the Explorer replacement for me. 
Thanks!

**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Jaiganeshkumaran** [comment]
Shortcuts aren't supported yet.

**Comment by yaichenbaum** [comment]
Merging with #177.
