### ISSUE TITLE
add the option to open more than one specific page at once on startup

### ISSUE THREAD

**Issue by rayyesboulous** [files-community/files-uwp#1316]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by ChihweiLHBird** [comment]
Working on it. ^_^

**Comment by yaichenbaum** [comment]
This has been implemented with #1443.

**Comment by rayyesboulous** [comment]
Thanks a lot for the update. I'm really enjoying the app. I had a question to... There is any way to add a shortcut on the jeitos to open the app? I do use a litte win + e to open the default file explorer and it's very convenient

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yaichenbaum** [comment]
@rayyesboulous You can pin it to be the first app on the task bar and launch it using `win + 1`.

**Comment by rayyesboulous** [comment]
Thanks a lot I'll try that tomorrow

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yaichenbaum** [comment]
This has been implemented with the v0.12.1 beta release.
