### ISSUE TITLE
The process has no package identity.

### ISSUE THREAD

**Issue by mohammadsj** [files-community/files-uwp#1317]
Cloned the code and compiled successfully. 
When running the app inside VS 2019, I get exception: 

System.InvalidOperationException
  HResult=0x80073D54
  Message=The process has no package identity. (Exception from HRESULT: 0x80073D54)
  Source=Windows.Storage
  StackTrace:
   at Windows.Storage.ApplicationData.get_Current()
   at FilesFullTrust.Program.Main(String[] args) in C:\Users\Jay\source\repos\files-uwp\Files.Launcher\Program.cs:line 29

![image](https://user-images.githubusercontent.com/8251288/86197754-eb4d4c00-bb0a-11ea-9d44-eb7ee9c93aab.png)

**Comment by duke7553** [comment]
@mohammadsj You'll need to select Files.Package in Visual Studio.

**Comment by liudonghua123** [comment]
I have the same problems around `The process has no package identityAt` when I upgrade flutter.

```shell
C:\Users\Liu.D.H>flutter upgrade
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine bd539267b42051b0da3d16ffa8f48949dce8aa8f...
Expanding downloaded archive...
Program '7z.exe' failed to run: The process has no package identityAt D:\apps\flutter\bin\internal\update_dart_sdk.ps1:
77 char:5
+     & 7z x $dartSdkZip "-o$cachePath" -bd | Out-Null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At D:\apps\flutter\bin\internal\update_dart_sdk.ps1:77 char:5
+     & 7z x $dartSdkZip "-o$cachePath" -bd | Out-Null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : NativeCommandFailed

Error: Unable to update Dart SDK. Retrying...
```

<img width="629" alt="image" src="https://user-images.githubusercontent.com/2276718/158713233-266be457-00e4-465e-898c-6c296e71ea89.png">

And I found the 7z is located in `C:\Users\Liu.D.H\AppData\Local\Microsoft\WindowsApps\7z.exe` which is an app execution alias. After I removed it, then it works as expected.

```shell
C:\Users\Liu.D.H>where 7z
C:\Users\Liu.D.H\AppData\Local\Microsoft\WindowsApps\7z.exe

C:\Users\Liu.D.H>7z --help
The system cannot execute the specified program.

C:\Users\Liu.D.H>7z
The system cannot execute the specified program.

C:\Users\Liu.D.H>rm C:\Users\Liu.D.H\AppData\Local\Microsoft\WindowsApps\7z.exe

C:\Users\Liu.D.H>where 7z
INFO: Could not find files for the given pattern(s).

C:\Users\Liu.D.H>
```
