### ISSUE TITLE
Pressing 'Space' to activate QuickLook only works in List View

### ISSUE THREAD

**Issue by generalguy41** [files-community/files-uwp#1322]
**Describe the bug**
Pressing 'Space' to activate QuickLook only works in List View, not Tile or Grid view (of any size).

**To Reproduce**
1. Go to a folder
2. Click on a file
3. Press 'Space' in List View
   a. See that it works
4. Press 'Space' in Tile or Grid View
   a. Doesn't work

**Expected behavior**
QuickLook should work in all views.

**Screenshots**
![ezgif-4-0e134ca30722](https://user-images.githubusercontent.com/8879244/86273830-d15d4900-bb9e-11ea-91b2-c199818e655b.gif)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 20152.1000
 - App version: v0.11.0.0 (Store Version)

**Comment by lampenlampen** [comment]
I have still version 0.10.2.0 and it works there.

**Comment by gave92** [comment]
Could be related to this change 35679a189eb1bb0b0d58695a779bd4c653dd5e87?
The keyboard accelerator for Space key is not firing, instead it seems the GridView is "swallowing" it

**Comment by Talisman39ar** [comment]
This is now working for me (using Quicklook v3.6.9 and the v 0.12.0.0 of Files UWP

**Comment by generalguy41** [comment]
Yea, this was fixed in #1349. Closing now.
