### ISSUE TITLE
2 functions

### ISSUE THREAD

**Issue by osnielta** [files-community/files-uwp#1326]
Hello, I would like to include 2 functions to the application so that it continues to improve, the 1st would be if it is possible for the browser to open by using the WIN + E key combination, and the 2nd that when copying a file from one side to the other, show a progress bar of how the copy is going, greetings and continue developing this magnificent application

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
@osnielta You can follow the guide in the wiki to replace File Explorer with Files UWP. We are are also working on a status center that will display the progress of  the file transfer #114.

**Comment by osnielta** [comment]
ok, and when will the version with the progress bars be available?

> @osnielta You can follow the guide in the wiki to replace File Explorer with Files UWP. We are are also working on a status center that will display the progress of the file transfer #114.

**Comment by yaichenbaum** [comment]
We haven't committed to a timeline on this feature, perhaps @duke7553 can fill in with more details.

**Comment by osnielta** [comment]
I have a problem, I followed all the steps with the registry changes to replace it with the classic browser and it does not work with WIN + E it keeps opening the classic
