### ISSUE TITLE
Sorting always reset on app close

### ISSUE THREAD

**Issue by valentimlh** [files-community/files-uwp#1327]
**Describe the bug**
Sorting always reset when app closes/opens

**To Reproduce**
1. OPen UWP File explorer
2. Right click > Sort > Choose any
3. Close UWP File explorer
4. Open UWP File explorer again
5. Right click > sort
6. The sort selected before, is gone

**Expected behavior**
When I choose a specific sort, every time I access that folder, the sorting must be the one I selected.

**Desktop**
 - OS Version: Windows 10 2004 19041.84
 - App version: 0.11.0

**Comment by yaichenbaum** [comment]
This has been fixed with the v0.12.1 beta release.
