### ISSUE TITLE
Title tab keeps showing "OneDrive"

### ISSUE THREAD

**Issue by guilhermebera** [files-community/files-uwp#1328]
**Is your feature request related to a problem? Please describe.**
When navigating through Onedrive's folders the tab's title remaining as "OneDrive".

**Describe the solution you'd like**
Tab could show the folder's name and not jus "OneDrive".

**Describe alternatives you've considered**
none

**Additional context**
Windows 1903. Files UWP 0.10.2

**Comment by yaichenbaum** [comment]
@guilhermebera This issue has been fixed with v0.11.
