### ISSUE TITLE
请问这个下载下来没有EXE可执行文件要怎么安装啊？

### ISSUE THREAD

**Issue by wfyihai** [files-community/files-uwp#1329]
请问这个下载下来没有EXE可执行文件要怎么安装啊？
github如何将下载下来的原件安装到电脑上呀。我是非程序专业。求大神指点一下。微软的应用商店打开又要看运气。所以这个怎么安装使用呀。。。求指教。

**Comment by Jaiganeshkumaran** [comment]
If you want to install from GitHub, you've to build it yourself and deploy the Files.Package project. Alternatively, you can download the latest version from the Microsoft Store: https://www.microsoft.com/store/apps/9NGHP3DX8HDX
