### ISSUE TITLE
Show progress on the taskbar

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#1344]
**Is your feature request related to a problem? Please describe.**
Not really. In File Explorer, it will show the progress of current primary operation in the taskbar. It'd be great to have such a feature in Files UWP so that I don't need to switch to Files UWP to see the progress of an operation.

**Describe the solution you'd like**
UWP doesn't support this feature yet however I've opened a proposal in the Project Reunions repository. See [https://github.com/microsoft/ProjectReunion/issues/68](https://github.com/microsoft/ProjectReunion/issues/68).

**Describe alternatives you've considered**
None.

**Comment by saint4eva** [comment]
Files UWP should be able to have a progress bar or status box that shows the progress of transferring files/ folders from one directory to the another directory opened in Files UWP

**Comment by Jaiganeshkumaran** [comment]
It has been already implemented in the latest version.

**Comment by saint4eva** [comment]
> It has been already implemented in the latest version.

Yes, I am running the latest version. Isn't version **0.11.0.0** the latest?

**Comment by Jaiganeshkumaran** [comment]
0.11.0 is the latest version on the Store. Note that progress is only shown when you copy/move/delete a large file or large files.

**Comment by duke7553** [comment]
@Jaiganeshkumaran @saint4eva This hasn't been implemented and is still not available to users.

**Comment by duke7553** [comment]
I don't think we should have progress on the taskbar as it is distracting for users. There's a reason why it wasn't implemented in WinRT APIs to begin with.

**Comment by saint4eva** [comment]
> @Jaiganeshkumaran @saint4eva This hasn't been implemented and is still not available to users.

Thank you for the information.

**Comment by saint4eva** [comment]
> I don't think we should have progress on the taskbar as it is distracting for users. There's a reason why it wasn't implemented in WinRT APIs to begin with.

What about progress on the dialog box?

**Comment by minecraftchest1** [comment]
I like the progress bar on the taskbar. It's the flashing that annoys users.

**Comment by Jaiganeshkumaran** [comment]
> I don't think we should have progress on the taskbar as it is distracting for users. There's a reason why it wasn't implemented in WinRT APIs to begin with.

That's not the real reason. Windows 8 didn't show Metro apps in the taskbar and Windows 8.1 did but apps were running in full screen so showing progress on the taskbar would not make sense. Now with Windows 10, all apps are windowed so it's useful.

**Comment by minecraftchest1** [comment]
I love the progress bar on the taskbar, because I may have a file transfer or download but not always have the applications window open in the foreground. With the progress on the taskbar, it allows me to just take a quick look and see how it is going.
A word from a user.

Sent from my T-Mobile 4G LTE Device

________________________________
