### ISSUE TITLE
Support for other cloud storage drives

### ISSUE THREAD

**Issue by RetailPleb** [files-community/files-uwp#1357]
In addition to OneDrive, I also use Adobe Creative Cloud, and that folder does not show up in Files UWP. I'd like to make the switch exclusively to this app, but without access to all of my files I can't; and using two different apps to do the same thing is a bit disjointed.

**Comment by yaichenbaum** [comment]
Can you try pinning the creative cloud folder to the sidebar?

**Comment by RetailPleb** [comment]
> Can you try pinning the creative cloud folder to the sidebar?

Well now I feel embarrassed for not thinking of that... Yes that did work. Thank you so much!
