### ISSUE TITLE
An "Open with..." feature

### ISSUE THREAD

**Issue by HoraceHuang-ui** [files-community/files-uwp#1363]
"**Open with...**" is a super handy and frequently-used feature to many users. It's absolutely essential for an explorer app. Once this feature is added, I may use the regedit method on wiki to change my default explorer. Thanks!

**Comment by XPoppyX** [comment]
The app already has the "**open with**" feature

**Comment by Jaiganeshkumaran** [comment]
Which version of the app are you using? The latest version has the "open with" option.

**Comment by yaichenbaum** [comment]
@HoraceHuang-ui Files UWP already includes an "Open with" feature. Make sure to update to v0.11 if you are not seeing this option.
