### ISSUE TITLE
close recently accessed files

### ISSUE THREAD

**Issue by 610418514** [files-community/files-uwp#1364]
Can I close the recently accessed files on the home page？

**Comment by Jaiganeshkumaran** [comment]
You can right-click a recently accessed file and remove the file or clear the entire list.

**Comment by 610418514** [comment]
> You can right-click a recently accessed file and remove the file or clear the entire list.

 I know, but I'd like to turn this off completely, hopefully in a later version, after all, I do n' t want anyone else to see what I've been watching lately when I' m using my compute

**Comment by yaichenbaum** [comment]
Merging with #366.
