### ISSUE TITLE
Polish language

### ISSUE THREAD

**Issue by Raflen100** [files-community/files-uwp#1371]
Hi! I'm Polish and I very want to your very nice app have my language.

**Comment by Jaiganeshkumaran** [comment]
Could you help us translate into your language?

**Comment by yaichenbaum** [comment]
@Raflen100 Thank you for your feedback, Files UWP is a community project and new languages are usually added by users themselves, you can check out the wiki for information on how to translate the app https://github.com/files-community/files-uwp/wiki/Translating-Files-UWP-into-your-language.
