### ISSUE TITLE
Can you please add the feature to see shortcuts and the feature to empty and restore things from the recycle bin?

### ISSUE THREAD

**Issue by Yng-Ducky09** [files-community/files-uwp#1372]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Jaiganeshkumaran** [comment]
You can already restore and empty things from the recycle bin.
