### ISSUE TITLE
Opening, and viewing properties of any file and folder on the Recycle Bin minimizes and crashes the app

### ISSUE THREAD

**Issue by marrraimund** [files-community/files-uwp#1377]
### (7/11/2020) BIG UPDATE TO THIS ISSUE: ###   
**The issue occurs all the time in ALL file or folder both inside and outside the Recycle Bin**

Refer also to **issue #973**. It is actually the same.

### THE MAIN ISSUE HERE: ###
When you open or view the properties of any file and folder inside and outside the Recycle Bin **the app simply minimizes but it cannot be maximized/restored and then the app simply crashed with app still being running in an inaccesible state until closed or killed in any way.**

### EXPECTATION WHEN IT IS FINALLY RELEASED AND OUT OF BETA: ###
I'm expecting that **the File and Folder properties dialog would normally close without crashing the app.**

### OS AND APP WITH THAT ISSUE INFORMATION: ###
 - OS Version: Windows 10 (20h1) version 2004 build 19041.331
                       Other release codename: "vb_release"
 - App version: **v0.11.0**

### WHEN DOES THE PROBLEM/ISSUE OCCUR? ###
The problem occurs **every time when I open the app and try to view file properties or open the file or folder inside and outside the Recycle Bin.**

### OTHER FEEDBACK ###
_The recycle bin feature is a cool feature though. Hopefully it would be better than how Windows 10 opens and handles the recycle bin._

**Comment by gave92** [comment]
Might be the same as #973?

**Comment by marrraimund** [comment]
> Thanks for the feedback. Might be the same as #973? Does the issue occur when you open or upon closing the file property window?

Yes.

**Comment by marrraimund** [comment]
> Thanks for the feedback. Might be the same as #973? Does the issue occur when you open or upon closing the file property window?

Yes.

**Comment by yaichenbaum** [comment]
Merging with #973.
