### ISSUE TITLE
Inability to search any local and cloud file and folder

### ISSUE THREAD

**Issue by marrraimund** [files-community/files-uwp#1378]
**Description of the Bug**
The most crucial and most required feature in a file manager is the ability to search files and folders isn't working.

The search button as of now is grayed out which means that we can't any local and cloud file and folder. Please put local and cloud search functionality soon. It should be at least stable and more responsive than the new Windows Search that since Windows 10 (19h2) version 1909 build 18363.

**Expected behavior**
This must search not just local files and folders but also cloud files and folders as well like OneDrive and Google Drive.

 - OS: Windows 10 (20h1) version 2004 build 19041.331
          Other release codename: "vb_release"
 - App version: **v0.11.0**

**Comment by Jaiganeshkumaran** [comment]
Search has not been implemented yet. We're tracking this issue in #333.

**Comment by yaichenbaum** [comment]
Merging with #333.
