### ISSUE TITLE
There is no progressbar while copying files

### ISSUE THREAD

**Issue by jlhuang1224** [files-community/files-uwp#1380]
**Describe the bug**
When I am copying files from one folder to another folder, I can't see a progressbar like Windows Explorer. So I don't know whether the process is finished or not.

**To Reproduce**
1.Select some files then hit Ctrl+C.
2.Open another folder then Paste them.
3.You can't see a progressbar that indicate the progress.

**Expected behavior**
A windows with progressbar like Windows Explorer.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]
 - OS Version: [Windows 10 2004 19555.1001]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
Restart and reinstall did no help.

**Comment by yaichenbaum** [comment]
Merging with #114.
