### ISSUE TITLE
希望能动态调节缩略图大小

### ISSUE THREAD

**Issue by alialix2** [files-community/files-uwp#1386]
希望能动态调节缩略图大小，或者能整个区域平均分布，不然最大缩略图和中等缩略图右边留有一块空白，强迫症太难受啦

**Comment by XPoppyX** [comment]
您可以使用“ Ctrl +鼠标滚轮向上或向下”来逐渐增加大小

**Comment by duke7553** [comment]
@alialix2 你的问题现在解决了吗？
