### ISSUE TITLE
Ability to restart automatically when changing language

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#1387]
Currently changing Files UWP's language requires me to manually restart. Would it not be better if it automatically restarts for you?

**Comment by yaichenbaum** [comment]
We wouldn't want to restart without asking the user, what we could do is, add a button with the option to restart that shows after they change the language. When the app restarts, it should restore any directories they had open before.

**Comment by Jaiganeshkumaran** [comment]
We can show a dialog box when changing the language whether they want to restart the app or not.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran What about something similar to Microsoft Edge?
![image](https://user-images.githubusercontent.com/39923744/87237554-a4423f00-c3c5-11ea-9bc1-1478f1fd7ab4.png)

**Comment by jaigak** [comment]
@yair100 Great!

**Comment by Thomas1664** [comment]
I can take it.

**Comment by Thomas1664** [comment]
@yair100 How do I add new translation keys without markup?

**Comment by Jaiganeshkumaran** [comment]
@Thomas1664 Just add them in the resource file and load the string at runtime using Files UWP's static ResourceController class.

**Comment by Thomas1664** [comment]
@yair100 I think the approach with a bar in the bottom of the page like edge isn't the best choice since it is not that appealing. For this reason, I suggest either using a dialog or the way VS Code handles in-app notifications (I don't mean the messages in the right corner on the bottom) using [this control](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/inappnotification)

**Comment by Jaiganeshkumaran** [comment]
@Thomas1664 Do that then. Showing a notification near the action center is not suitable.

**Comment by Thomas1664** [comment]
@Jaiganeshkumaran can cou specify which approach you actually refer to with "that"?
I suggested 2 options:
- dialog
- VS Code like in-app notification

**Comment by Jaiganeshkumaran** [comment]
@Thomas1664 VS Code like in-app popup notification would be better.

**Comment by yaichenbaum** [comment]
@Thomas1664 An in app notification seems like the best idea.
