### ISSUE TITLE
App 0.11.3 will not start

### ISSUE THREAD

**Issue by jpparametrics** [files-community/files-uwp#1389]
**Describe the bug**
I click the icon on the taskbar and it opens  up to what you see in the ayyached screenshot and then exits out
[debug.txt](https://github.com/files-community/files-uwp/files/4905065/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/4905066/debug_fulltrust.txt)

**To Reproduce**
1. Click on the icon in the start menu or the taskbar
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Pro 20161.200627-1754]
 - App version: [v0.11.3]

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?
![filesuwp-after-click](https://user-images.githubusercontent.com/3137489/87192185-f438dd00-c2c3-11ea-8438-8640cc0883c5.png)

**Comment by jpparametrics** [comment]
I did uninstall and reinstall the app

**Comment by duke7553** [comment]
@jpparametrics Thank you for reporting this. 

Did you notice this was an issue on older releases, or just v0.11.3?

**Comment by jpparametrics** [comment]
This is the first time it has happened

**Comment by jpparametrics** [comment]
![Untitled](https://user-images.githubusercontent.com/3137489/87210005-03c71e80-c2e2-11ea-9ad2-ddebd119a7e0.png)
 The odd thing about that window is that I do not have a folder by the name that you see on this notebook. There is that very same one on a notebook that a friend of mine is using however. Interesting...

**Comment by jpparametrics** [comment]
Well, for whatever reason the Dev version 0.11.3 is working for now...

Luke assisted me with getting her up and running in VS. After that I noticed that both the DEV and preview versions were installed. The both of them have never been installed at the same time. Mine always showed as the preview. Just an FYI.

I am assuming it is my system...

JP

**Comment by Jaiganeshkumaran** [comment]
> Well, for whatever reason the Dev version 0.11.3 is working for now...
> 
> Luke assisted me with getting her up and running in VS. After that I noticed that both the DEV and preview versions were installed. The both of them have never been installed at the same time. Mine always showed as the preview. Just an FYI.
> 
> I am assuming it is my system...
> 
> JP

The preview version is the Store version and the dev version is the version on GitHub.
