### ISSUE TITLE
Mapped drives content not visible

### ISSUE THREAD

**Issue by pi3c3** [files-community/files-uwp#1393]
**Describe the bug**
Mapped drives are not visible, for example you cannot reach your files on a mapped NAS drive

**To Reproduce**
1. Start File UWP
2. Click on a Mapped drive
3. No files listed.

**Expected behavior**
A mapped drives should browsable. 

**Screenshots**
![image](https://user-images.githubusercontent.com/66777453/87218838-b89b2300-c356-11ea-91e6-89a67bd4a9b8.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.900]
 - App version: [v0.11.0]

**Comment by Jaiganeshkumaran** [comment]
This issue will be fixed in the next version.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our stable branch and should be available from the Microsoft Store. Please subscribe to our releases to be notified when fixes like this are available.
