### ISSUE TITLE
iCloud support

### ISSUE THREAD

**Issue by p0risonpupu** [files-community/files-uwp#1399]
Hi Guys, 
The beta is beautifully designed and I would love to switch, but is there no Icloud drive support?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by yaichenbaum** [comment]
@p0risonpupu Have you tried navigating to iCloud and pinning the location to the sidebar?

**Comment by Jaiganeshkumaran** [comment]
Duplicate of #242.

**Comment by yaichenbaum** [comment]
Merging with #242.
