### ISSUE TITLE
cuting (Ctrl + X) a bundle of files crashed the app (windows store version)

### ISSUE THREAD

**Issue by gauss182** [files-community/files-uwp#1400]
**Describe the bug**
Was moving some files from one drive to another with the cutting option (Ctrl+X). The app crashed immediately after doing the cut. Reproduced the issue by doing the exact same thing. Attaching debugs.
[debug.txt](https://github.com/files-community/files-uwp/files/4907926/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/4907927/debug_fulltrust.txt)

**To Reproduce**
1. Select files on one of your SSD drives
2. Cut the files with Ctrl+x

**Expected behavior**
Cutted files grayed out making them possible to move to another ssd drive.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 2004 (19041.329)
 - App version: v0.11.0.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by yaichenbaum** [comment]
This issue was fixed with #1820.
