### ISSUE TITLE
"Open With" does nothing

### ISSUE THREAD

**Issue by AdinAck** [files-community/files-uwp#1408]
**Describe the bug**
When right clicking on a file, and then clicking "Open With" nothing happens.

**To Reproduce**
1. Right click on file
2. Click "Open With"
3. See menu close

**Expected behavior**
Open with should open a selection of programs that could be immediately opened with the file.

**Desktop (please complete the following information):**
 - OS Version: 10.0.18363 Build 18363
 - App version: [v0.11.0]

**Comment by Jaiganeshkumaran** [comment]
It only occurs for a few file types.

**Comment by yaichenbaum** [comment]
@AdinAck We have not been able to reproduce this issue, what type of file are you seeing this issue with?

**Comment by AdinAck** [comment]
It appears to work now! Looks like it was fixed at some point or a windows update maybe fixed it, who knows?
