### ISSUE TITLE
Properties window not closing when pressing "Esc" key.

### ISSUE THREAD

**Issue by osieltorres** [files-community/files-uwp#1409]
**Describe the bug**
Currently the file or folder Properties window is not closed when pressing "Esc" key on keyboard, although this is a natural behaviour in default windows explorer.

**To Reproduce**
1. Go to any file or folder.
2. Right click and go to menu Properties option .
3. Press the "Esc" key to close the window.
4. The Properties window does not close.

**Expected behavior**
The Properties window to close when "Esc" key is pressed.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.329]
 - App version: [v0.11.0.0]

**Comment by XPoppyX** [comment]
@yaichenbaum

**Comment by yaichenbaum** [comment]
This issue has been fixed with #1504 and should roll out to users in a couple of weeks.
