### ISSUE TITLE
Setting a language other than my Windows language breaks translation

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#1416]
**Describe the bug**
When you set another language other than the Windows language, some elements still display in the Windows language.

**To Reproduce**
Steps to reproduce the behavior: (Only works if you speak multiple languages)
1. Go to settings->options and change the language to another language other than your Windows language
2. Restart the app
3. Some elements may appear in your Windows language instead of the language set for Files UWP.

**Expected behavior**
All elements should display in the selected language.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro Insider Preview 20161.1000
 - App version: v0.12.0

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Can you provide details on which elements show up with the wrong strings?

**Comment by Jaiganeshkumaran** [comment]
The item type and library folder names.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Files UWP does not translate those strings as it pulls it from Windows. We only translate the UI and strings that we have added ourselves.

**Comment by Jaiganeshkumaran** [comment]
The library folder names are translated by us so they should appear properly.
