### ISSUE TITLE
Change Date format options to "Short" and "Long" instead of "System" and "Application"

### ISSUE THREAD

**Issue by R3voA3** [files-community/files-uwp#1419]
I actually had to read the wiki entry here on GitHub to know what System and Application actually means. By changing the option names to ```Short  6/3/2020``` and ```Long Wednesday, June 3, 2020``` the user immediately knows what to expect.

**Comment by Jaiganeshkumaran** [comment]
The system format can be changed via settings so it doesn't make sense.

**Comment by R3voA3** [comment]
The windows settings? If yes, I didn't know that.

**Comment by Jaiganeshkumaran** [comment]
Yes. You change the default system format in Windows Settings.
