### ISSUE TITLE
Add a page to settings which lists all the nice shortcuts

### ISSUE THREAD

**Issue by R3voA3** [files-community/files-uwp#1421]
I would be very handy to have a page a user can check to get an overview over all available shortcuts.

**Comment by yaichenbaum** [comment]
@R3voA3 Would creating a wiki page with the available shortcuts be helpful?

**Comment by R3voA3** [comment]
That would work as well, sure.

**Comment by yaichenbaum** [comment]
@R3voA3 I started work on a new Wiki [page](https://github.com/files-community/files-uwp/wiki/Keyboard-shortcuts), there are many shortcuts available which we will add to the list over time.
