### ISSUE TITLE
Lost over 10 Houers of work becouse cut paste corrupts my files when using files-UWP

### ISSUE THREAD

**Issue by NicTanghe** [files-community/files-uwp#1428]
**Describe the bug**
cut paste corrupts my files when using files-UWP

**To Reproduce**
Cut and paste houdini .hip files

**Expected behavior**
it works like it always does.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Not sure if this only causes errors in Houdini And also not 100% the issue does not lie somewhere else.
If it happens again with the normal file explorer i will update the ticket.

**Comment by Jaiganeshkumaran** [comment]
Sorry for the inconvenience caused. Could you try using a recovery program like Recuva to try recover your data?

**Comment by yaichenbaum** [comment]
@NicTanghe Sorry about the troubles, we are working on a new file transfer UI that will let you know if there is an issue transferring a file. This will hopefully prevent issues like this from happening again.

**Comment by NicTanghe** [comment]
I'm not going to do that I'm just going to ditch the project it was more of research project than something I need or need to earn money with. I already learned from it what I wanted to. I was overreacting a tad bit.

Don't worry bout me just about making the program better

**Comment by Jaiganeshkumaran** [comment]
@NicTanghe<mailto:notifications@github.com> Can you explain what really went wrong and what happened? I’ve experienced issue before when copying or moving files within Files UWP. Also could you share the log file so that I could what can I do.

**Comment by yaichenbaum** [comment]
@NicTanghe Can you share the log file so we can properly investigate the issue?

**Comment by NicTanghe** [comment]
I don't have any log files sorry.
