### ISSUE TITLE
Layout mode

### ISSUE THREAD

**Issue by madhavDey98** [files-community/files-uwp#1434]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to change a particular layout for a drive (say Drive C)
and that same layout gets implemented globally across all the drives.
 
**Describe the solution you'd like**

I would love if there has to be like regular File Explorer , where the layout mode is distinctive for a particular Drive and not implemented globally. Also please add Zoom in and out for layout change that makes things easy and short.
I really love the new Files UWP. its amazing

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Jaiganeshkumaran** [comment]
You can zoom in and zoom out already by pressing Ctrl + Scroll Wheel. I don't know whether it works touchscreen or not.

**Comment by yaichenbaum** [comment]
Merging with #530.
