### ISSUE TITLE
Redesigned Files UWP menu with a corner. 

### ISSUE THREAD

**Issue by seohyun1108** [files-community/files-uwp#1436]
**Describe the solution you'd like**
Files UWP menu with a corner will be great. It will look good.

**Comment by yaichenbaum** [comment]
@seohyun1108 Can you please update your proposal with more details on what you would like to see?

**Comment by seohyun1108** [comment]
![533E2EE0-DE85-4C8D-A267-2D566C7D217C](https://user-images.githubusercontent.com/43906110/87425315-6426ca80-c618-11ea-8325-78a2923c9be6.jpeg)

Like that! (Sorry, I'm not good at drawing)
Menu with a corner.
And, I think it will be beautiful if the settings button become like it. (No "Settings" letter, only an icon)

**Comment by XPoppyX** [comment]
something like this?
![Anotación 2020-07-14 085807](https://user-images.githubusercontent.com/61259627/87428776-d9f74b80-c5b0-11ea-98f6-33e020d3bf0a.jpg)

**Comment by osieltorres** [comment]
The requested design looks nice, but I believe that rounded corners would break out with based Windows style.

**Comment by seohyun1108** [comment]
Yes! I like it!

**Comment by yaichenbaum** [comment]
A rounded corner design wouldn't look too good in this case unless the actually window was rounded as well.

**Comment by jaigak** [comment]
@yair100 It's not possible to round a UWP window.

**Comment by yair100** [comment]
> @yair100 It's not possible to round a UWP window.

Correct.

**Comment by seohyun1108** [comment]
I think Microsoft is developing UWP round windows, so maybe later this can be happen.
