### ISSUE TITLE
Inproper file size format on zh-CN

### ISSUE THREAD

**Issue by smallg0at** [files-community/files-uwp#1440]
**Describe the bug**

This is a problem on file size format which will confuse users, might caused by string replacement.
Currently the zh-cn file size format looks like this:

![image](https://user-images.githubusercontent.com/30719670/87368920-ba145780-c5b1-11ea-963c-31ea4cc09659.png)
If translated to English you may see this as: XX.x Kilobytes (K Bytes (B))
The current format is full of gibberish information that doesn't mean anything.

**To Reproduce**
1. Inspect any folder with your app display language as zh-cn
2. reproduced.

**Expected behavior**

Example:
- Megabytes => 1.2 MB
- Kilobytes => 12.5 KB
- Bytes => 233 字节
- Gigabytes => 1.2 GB

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 2004 20161.1000]
 - App version: [v0.12.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app? Yes.

**Comment by yaichenbaum** [comment]
This issue has been fixed with #1610.
