### ISSUE TITLE
Add support for Disk Drive (like original file explorer)

### ISSUE THREAD

**Issue by seohyun1108** [files-community/files-uwp#1445]
Add support for formatting a disk drive. Plus, I want this panel.
![7F9B0540-AE27-477E-9092-98533B821DB0](https://user-images.githubusercontent.com/43906110/87425597-e2836c80-c618-11ea-8176-d3e3c56eb313.jpeg)

**Comment by yaichenbaum** [comment]
We are exploring adding a disks widget to the homepage, merging with #366.
