### ISSUE TITLE
Add Support for Control Panel. 

### ISSUE THREAD

**Issue by seohyun1108** [files-community/files-uwp#1446]
I know that Control Panel is a part of file explorer. However, when I open a Control Panel, Files UWP opens. I can't use it! Please fix it so I can set Files UWP to default file explorer. Is there any solutions?

**Comment by Jaiganeshkumaran** [comment]
There's no solution but I'm investigating support for opening control panel when Files is the default. Till then don't replace the File Explorer and instead add the option to open a folder in Files UWP and open folders easily in File Explorer. Check this out: https://github.com/files-community/files-uwp/wiki/Add-Files-UWP-to-the-File-Explorer-context-menu

**Comment by jaigak** [comment]
@yair100 Until a solution is found for this issue, the wiki must say that 'after replacing File Explorer, you can't access the Control Panel.' Most users don't know that the Control Panel is part of Explorer.

**Comment by yair100** [comment]
> @yair100 Until a solution is found for this issue, the wiki must say that 'after replacing File Explorer, you can't access the Control Panel.' Most users don't know that the Control Panel is part of Explorer.

There is already a warning "This guide involves modifying the registry, make sure to create a backup beforehand and proceed at your own risk.".
