### ISSUE TITLE
Open pinned folders in existing windows of F-UWP instead of creating a new one

### ISSUE THREAD

**Issue by crashmit** [files-community/files-uwp#1448]
Hi there,

**Problem:**
I often open new folders by right-clicking the explorer and opening a shortcut. One of my favourite "features" of F-UWP is that you don't open new windows for every instance, but instead have tabs like in a browser - except from when you open a pinned folder from the taskbar.

**Solution:**
I would love to have a setting which allows me to open pinned folders from the taskbar in a already existing window of Files-UWP instead of opening a new window.

![image](https://user-images.githubusercontent.com/58466626/87430856-172a0080-c5e6-11ea-9ffd-1a27c8e95df5.png)

**Comment by gave92** [comment]
I'd like this as well and it's easy enough to implement. Perhaps we should add a setting to select the desired behavior.

**Comment by yaichenbaum** [comment]
> I'd like this as well and it's easy enough to implement. Perhaps we should add a setting to select the desired behavior.

Adding a setting would probably be the best choice here.

**Comment by yaichenbaum** [comment]
This has been implemented with the v0.12.1 beta release.
