### ISSUE TITLE
Remove acrylic sidebar from settings | Default to on

### ISSUE THREAD

**Issue by RandomAJL** [files-community/files-uwp#1454]
I believe that **allowing the user to choose** weather they want the acrylic sidebar turned on will **cause confusion** and therefore will increase the likelihood of **false issue reports**.

The acrylic sidebar **(when turned on)** respects the **windows global setting for transparency** **(Windows settings app -> Personalisation -> Colours -> Transparency effects)**.
Even when the files app has acrylic sidebar turned on, **it won't work unless transparency effects are enabled** through windows settings. The two solutions to this are either to make it not respect the windows settings and allow the acrylic effects no matter what, or alternatively **remove the option all together** and have it **respect the windows setting for transparency by default**; which is exactly what I think should be the case.

Example of what currently happens:

![image](https://user-images.githubusercontent.com/32604070/87450227-29ac3600-c5f6-11ea-8294-ad7c13f23614.png)
![image](https://user-images.githubusercontent.com/32604070/87450236-2c0e9000-c5f6-11ea-9aa9-98eabc3dde4f.png)

**Comment by duke7553** [comment]
@RandomAJL We added this as an option specific to the app, because certain users expect acrylic in the Windows Shell, but not on the sidebar pane. We'll keep this suggestion in mind, but there is a low likelihood we'll act on it considering how background acrylic is technically poor design.
