### ISSUE TITLE
OnStartup:  Alignment of "Add a new page" button

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#1471]
With longer text the button should expand to the left and not to the right, to maintain alignment

**Current:**
![Anotación 2020-07-15 171546](https://user-images.githubusercontent.com/61259627/87597295-917a8380-c6bf-11ea-9458-7c62f839c32d.png)

**Proposal:**
![Anotación 2020-07-15 1715462](https://user-images.githubusercontent.com/61259627/87597312-98a19180-c6bf-11ea-80d2-96a42e5e3f8b.png)

**Comment by yaichenbaum** [comment]
@XPoppyX Upon checking the latest beta release, it looks like the button is already lined up.

**Comment by XPoppyX** [comment]
with the latest changes, it still looks like this
![Anotación 2020-07-19 080620](https://user-images.githubusercontent.com/61259627/87874322-ea376e00-c996-11ea-84cb-041322f0b518.png)
