### ISSUE TITLE
Option to Open Folder in Windows File Explorer

### ISSUE THREAD

**Issue by DesmondWillowbrook** [files-community/files-uwp#1475]
**Is your feature request related to a problem? Please describe.**
A lot of the times I want to use features of the top ribbon in the File Explorer but currently while browsing in files-uwp I have to again navigate to the path of the files I'm opening.

**Describe the solution you'd like**
An option to open the path in Windows File Explorer on right-clicking inside the files-uwp app.

**Describe alternatives you've considered**
I've thought of suggesting incorporating all the features of the Windows File Explorer but that's what you are doing.

**Additional context**
![Files-UWP Issue](https://user-images.githubusercontent.com/51814158/87635320-76118600-c75c-11ea-809d-3a66b96bfdab.png)

**Comment by Jaiganeshkumaran** [comment]
This should be optional since you can replace File Explorer with Files UWP.

**Comment by StevenTsvetkov** [comment]
I've also pretty much replaced the File Explorer with Files UWP. It's an awesome software, it looks great, and 90% of the time, it gets the job done. This seems like a good temporary feature for those 10%, where you have to quickly hop into Explorer and get something done.

I currently solve this with an AHK script, but I think such a button would be a welcome addition and it will sit nicely below `Open in Terminal`.

**Comment by yaichenbaum** [comment]
There are no plans to implement such an option as the goal is to completely replace File Explorer. We know we haven't gotten to that point yet but we don't think it's a good idea to add something that we know will be removed shortly after.
