### ISSUE TITLE
Optional tab layout suggestion

### ISSUE THREAD

**Issue by yarikv8601** [files-community/files-uwp#1476]
This layout is inspired by Firefox side panel and in my opinion It would be perfect for wide screen monitors.

![untitled_page](https://user-images.githubusercontent.com/52413473/87680390-087a4f80-c786-11ea-81a7-02d2cc0c1049.png)

**Comment by yaichenbaum** [comment]
@duke7553

**Comment by mdtauk** [comment]
Edge is soon to be getting Vertical Tabs - and the idea of TabPlacement being added to the WinUI TabView control has been brought up.  So once it's added to the control - it should be easier to include in Files.

![image](https://user-images.githubusercontent.com/7389110/87670657-01444900-c768-11ea-8cde-b9c181323e90.png)

**Comment by yaichenbaum** [comment]
@mdtauk While we can implement a full VerticalTab pane, it can cause confusion with navigation as you already have a sidebar compared to Edge, which does not.

**Comment by mdtauk** [comment]
The vertical tabs could be placed on the right of the Icon/Grid view.  Top Tabs seem to work fine, and I only mentioned that the TabView may be getting vertical tab support in the future, and you could implement it if you wish, even if the default remains the top tabs.

**Comment by duke7553** [comment]
@mdtauk No. There were numerous issues with the horizontal tab strip design which led us to implement the vertical flyout. Trust me, we had this in the pipeline long before you suggested it. 🙂

**Comment by duke7553** [comment]
Closing this until @yarikv8601 can tell us specifically how his mockup is better than the existing design, and what problems it solves.

**Comment by yarikv8601** [comment]
@duke7553 keep it closed since I already made better ones (Yeah, this one sucks)
