### ISSUE TITLE
App crashes when I open the preference panel

### ISSUE THREAD

**Issue by iisGmoney** [files-community/files-uwp#1480]
**Describe the bug**
When I try and open the preferences settings panel the app crashes.

**To Reproduce**
1. Click on Settings
2. Click on Preferences
3. App crashes

**Expected behavior**
What should happen is that a preference panel should open.

**Desktop**
 - OS Version: Windows 10 20H2
 - App version: 0.12.0.0

**Comment by Jaiganeshkumaran** [comment]
Could you post the log file, please?

**Comment by iisGmoney** [comment]
where would that be located

**Comment by Jaiganeshkumaran** [comment]
In the settings page.

**Comment by iisGmoney** [comment]
[debug.txt](https://github.com/files-community/files-uwp/files/4933025/debug.txt)

**Comment by pixl-8** [comment]
It doesn't do that for me.

OS: Win 10 Home 20170.rs_prerelease
App Version: v0.12

**Comment by XPoppyX** [comment]
@yaichenbaum Was this fixed with this #1634 ?
