### ISSUE TITLE
App crashes when go to 'Preferences' settings

### ISSUE THREAD

**Issue by xmha97** [files-community/files-uwp#1488]
**Describe the bug**
This app crashes when I go to 'Preferences' settings.

**To Reproduce**
1. Click on 'Settings'
2. Click on 'Preferences'
3. The app crashes and closed.

**Expected behavior**

**Screenshots**
![Files UWP](https://user-images.githubusercontent.com/23485114/87801369-e3104300-c864-11ea-8dee-c4808b38e070.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909 18363.959]
 - App version: [v0.12.0.0]

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Comment by yaichenbaum** [comment]
Merging with #1480.
