### ISSUE TITLE
If one of several files you want to delete is in use, delete the others and show an option to skip

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#1495]
In the file explorer, if you want to delete for example 10 files and 2 of them are in use, it deletes all the others except the ones that are in use, and shows an option to skip all the ones that cannot be deleted. On the other hand, in Files UWP, if any file is in use, none is deleted and there is no option to skip

**Comment by yaichenbaum** [comment]
Merging with #114.
