### ISSUE TITLE
Tab theme

### ISSUE THREAD

**Issue by jbvc97** [files-community/files-uwp#1501]
**Describe the bug**
Tab theme don't follow app theme setting

**To Reproduce**
1. Change Windows to Dark mode [Settings > Personalization > Colors > Select _Dark_ on _Choose your color_]
2. Change the application's app theme to Light [Settings > Appearance > Select _Light_ on _App theme_]
3. Restart the application

**Expected behavior**
The tab theme applied should be Light

**Screenshots**
![Anotação 2020-07-18 192009](https://user-images.githubusercontent.com/5308392/87859281-df93bf00-c92b-11ea-92d1-cdb56ad7fb4a.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 19041.329
 - App version: 0.12.0.0

**Comment by Jaiganeshkumaran** [comment]
TabView has been removed in the latest preview.

**Comment by yaichenbaum** [comment]
This issue is no longer present in the latest preview build.
