### ISSUE TITLE
Segoe MDL2 Assets are still present

### ISSUE THREAD

**Issue by SimoneRaspagni** [files-community/files-uwp#1509]
**Describe the bug**
Segoe MDL2 Assets are still present in small parts of the app

**To Reproduce**

Segoe MDL2 Assets are still present in:
1. right clik flyout in path bar (and is not present for "select all")
2. right clik flyout in column header (edit colunm and size alla colunm to fit)

**Expected behavior**
Replaced this Segoe MDL2 Assets with Fluent UI icons

**Screenshots**
no

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1909 18363.657]
 - App version: [v0.12.1.0]

**Comment by XPoppyX** [comment]
> 1. and is not present for "select all"

for texts, normally for "select all" icon is not used

**Comment by yaichenbaum** [comment]
Since the menus are built into the TextBox, I am not sure if there is a way to change these icons.
