### ISSUE TITLE
希望能将主页的“下载”，“文档”，“图片”等按钮后添加或替换成自己设置的文件夹

### ISSUE THREAD

**Issue by shjdgwj** [files-community/files-uwp#1510]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
希望能将主页的“下载”，“文档”，“图片”等按钮后添加或替换成自己设置的文件夹
**Describe alternatives you've considered**
我知道这是windows设置的，并且可以更改这些文件夹的默认位置。但是我更想把他们替代成其他我需要的文件夹，用以代替windows资源管理器的“快速访问”功能。希望能有添加，更改，删除“下载”，“文档”，“图片”这些按钮的功能。
谢谢
![QQ截图20200720122231](https://user-images.githubusercontent.com/11689121/87899455-ce5dc600-ca83-11ea-9134-33798eea5fd5.png)

同时，在上传这个图片的过程中，我发现这个软件不支持文件直接拖动？
**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by jaigak** [comment]
@yair100 Instead of displaying pre-listed folders, we can show the folders pinned on the sidebar.

**Comment by duke7553** [comment]
@shjdgwj Users already have the capability to modify the sidebar to their choosing by pinning/unpinning folders.

@Jaiganeshkumaran I hope I'm interpreting this correctly. 😨

**Comment by XPoppyX** [comment]
@duke7553 mm, he mentions the home page

**Comment by shjdgwj** [comment]
> @shjdgwj Users already have the capability to modify the sidebar to their choosing by pinning/unpinning folders.
> 
> @Jaiganeshkumaran I hope I'm interpreting this correctly. 😨

![QQ截图20200720122231](https://user-images.githubusercontent.com/11689121/87899496-f9e0b080-ca83-11ea-9eaa-ed3a47a8af91.png)
This is what I am refering to

**Comment by shjdgwj** [comment]
> @shjdgwj Users already have the capability to modify the sidebar to their choosing by pinning/unpinning folders.
> 
> @Jaiganeshkumaran I hope I'm interpreting this correctly. 😨
it seems that i can not change the order of the siderbar.How can i do it？

**Comment by Jaiganeshkumaran** [comment]
You can change the order currently however you can add folders and unpin existing folders. To add a folder, navigate to that folder and click ‘Pin to sidebar’. To unpin a folder right click on a folder on the sidebar and click ‘Unpin’.
