### ISSUE TITLE
The latest version of QuickLook cannot open files in "Files UWP"

### ISSUE THREAD

**Issue by SinGuLaRiTy2001** [files-community/files-uwp#1515]
The v3.6.9 QuickLook cannot open files after I select one file and press SPACE key.
I reported this to the developer of QuickLook, but they've asked me to report this to you. https://github.com/QL-Win/QuickLook/issues/689

**Comment by Talisman39ar** [comment]
It's working fine for me (v3.6.9 of Quicklook, and v0.12.0.0 of Files UWP). With the previous version of Files UWP, Quicklook was only working in List view, not in Icons view, and it's now working for me in all views (see other Issue a couple of pages back)

**Comment by SinGuLaRiTy2001** [comment]
I've used the QuickLook installer trying to fix this and it worked! Thank you so much! @Talisman39ar
