### ISSUE TITLE
Choose the folders pinned to sidebar 

### ISSUE THREAD

**Issue by SimoneRaspagni** [files-community/files-uwp#1516]
**Is your feature request related to a problem? Please describe.**
Feature request: Choose the folders pinned to sidebar through the settings page (like "Pin OneDrive to the sidebar)

**Describe the solution you'd like**
Add ability to pin/unpin folders (desktop, documents, downloads, music...) via settings > preferences.
Add Fluent UI icons

**Describe alternatives you've considered**
---

**Additional context**
---
![pin-unpin sidebar folders](https://user-images.githubusercontent.com/22842679/87938195-79777b00-ca96-11ea-99ff-65fb6686c407.png)

**Comment by yaichenbaum** [comment]
@SimoneRaspagni You can already unpin items from the sidebar by right clicking on them. You can also pin an item yourself by right clicking on a directory, and clicking on the pin option.
