### ISSUE TITLE
Ribbon menu

### ISSUE THREAD

**Issue by SimoneRaspagni** [files-community/files-uwp#1517]
**Is your feature request related to a problem? Please describe.**
more than a new feature, mine is a question about a hidden / removed feature?
Are you planning to reintroduce ribben menu (see image below), present in the first versions of Files UWP?
I find it comfortable

![Annotazione 2020-07-20 144927](https://user-images.githubusercontent.com/22842679/87939576-901ed180-ca98-11ea-9c90-a3ee5eceb396.png)

**Comment by Jaiganeshkumaran** [comment]
@SimoneRaspagni There are no plans to bring it back.

**Comment by flying-night-slasher** [comment]
I like the ribbon menu. I'm more used to old style file explorer and if Microsoft replaces it with this or something else I'll have trouble navigating the new file explorer without some familiarity; I mean you could always put in there with the ability to turn it off and on.
