### ISSUE TITLE
Media controls shown in the taskbar preview

### ISSUE THREAD

**Issue by winiston2212** [files-community/files-uwp#1521]
**Describe the bug**
The preview window that is shown up when hovering over the Files UWP app in the taskbar shows the media controls that are shown for apps like Spotify and Groove to control music. The media controls are greyed out, so they don't actually do anything when pressed. This also shows on the files properties windows.

**To Reproduce**
1. Open Files UWP
2. Hover over Files UWP in the taskbar
3. Behold the almighty media controls

**Expected behavior**
I was not expecting media controls.

**Screenshots**
![2020-07-20](https://user-images.githubusercontent.com/59544401/87981467-2a2b4d80-ca8a-11ea-8f93-56509a39570f.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 20170.1000
 - App version: v0.12.0.0 (both in Beta and Dev versions, if that makes any difference)

**Comment by yaichenbaum** [comment]
This is a bug in the latest version of Windows 10. https://github.com/microsoft/msix-packaging/issues/357
