### ISSUE TITLE
Windows Terminal Preview support

### ISSUE THREAD

**Issue by erayrafet** [files-community/files-uwp#1528]
![image](https://user-images.githubusercontent.com/34194191/88135549-fa965580-cbef-11ea-9139-c791ba4c91a5.png)
https://www.microsoft.com/en-us/p/windows-terminal-preview/9n8g5rfz9xk3?rtc=1

**Comment by XPoppyX** [comment]
you can edit terminal profiles to add windows terminal to the list
https://github.com/files-community/files-uwp/wiki/Sample-terminal-profiles

**Comment by erayrafet** [comment]
> you can edit terminal profiles to add windows terminal to the list, or have you already tried that and it doesn't work with the preview version of windows terminal?
> https://github.com/files-community/files-uwp/wiki/Sample-terminal-profiles

I can't find the .exe name of the preview release.

**Comment by xumepoc** [comment]
This is strange. It is working for me
![Annotation 2020-07-23 111512](https://user-images.githubusercontent.com/46034979/88265307-ee84c380-ccd5-11ea-9a79-cbf71f41db15.jpg)

**Comment by erayrafet** [comment]
> This is strange. It is working for me
> ![Annotation 2020-07-23 111512](https://user-images.githubusercontent.com/46034979/88265307-ee84c380-ccd5-11ea-9a79-cbf71f41db15.jpg)
> 

There is a separate release track for the preview version of Windows Terminal.

**Comment by lampenlampen** [comment]
Under `Settings > Apps > Apps & Features > Aliase` you can choose which app the alias `wt.exe` opens (normal or preview). Unfortunately the preview does not have it's own alias.

**Comment by erayrafet** [comment]
> Under `Settings > Apps > Apps & Features > Aliase` you can choose which app the alias `wt.exe` opens (normal or preview). Unfortunately the preview does not have it's own alias.

I only have the preview version installed and manually setting the default terminal app to wt.exe does the trick, but sadly, now I can't access the Preferences tab in the settings of Files UWP. The app freezes and eventually quits.

**Comment by yaichenbaum** [comment]
@erayrafet Files UWP already supports Windows Terminal Preview.

**Comment by EdiTurn** [comment]
The support of Windows Terminal Preview still have problems:
1. If both Windows Terminal & Windows Terminal Preview are installed ,everything works fine. And the app opened by wt.exe can be set in Aliase. 

2.  If only Windows Terminal Preview installed:
  - auto detect not work
  - change terminal.json (add profile manually), then the changes will be reset after Files UWP restart. 
  - change terminal.json (remove CMD profile, leave wt.exe profile only), Files UWP will crash when clicking Settings - Preference.
