### ISSUE TITLE
If the file name does not have a suffix, the file cannot be opened

### ISSUE THREAD

**Issue by yxhl** [files-community/files-uwp#1530]

**Comment by Jaiganeshkumaran** [comment]
@yxhl By suffix do you mean by the file type extension? These files can't be opened since Windows doesn't know which app to use. In File Explorer, it lets you select an app to open a file like that but Files UWP doesn't do anything.

**Comment by yxhl** [comment]
> @yxhl By suffix do you mean by the file type extension? These files can't be opened since Windows doesn't know which app to use. In File Explorer, it lets you select an app to open a file like that but Files UWP doesn't do anything.

yes, Can I use Notepad as the default application to open these files? Or add Notepad to right click menu?

**Comment by Jaiganeshkumaran** [comment]
You can't set defaults for files without an extension but you could try using the Open with option.

**Comment by Jaiganeshkumaran** [comment]
Actually I found out that there's no option to open with these files but opening them using double click brings up the open with dialog where you can select Notepad.

**Comment by yxhl** [comment]
Strange, I just showed the desktop and then double-clicked the file, which can pop up dialog, but there was no prompt before, and it may be that dialog was hidden under other windows.

**Comment by Jaiganeshkumaran** [comment]
Minimize all windows using the Windows + M shortcut and then open Files UWP maximized.

**Comment by yxhl** [comment]
It work, thanks
