### ISSUE TITLE
Crash on click 'Preferences' in setting panel

### ISSUE THREAD

**Issue by makunterry** [files-community/files-uwp#1534]
**Describe the bug**
Each time click the 'Preferences' button on setting panel, the app crash.
This directly disable any chance in changing the preferences of this app.

**To Reproduce**
1. Click 'Settings' and open setting panel;
2. Click 'Preferences' button on the left;

**Expected behavior**
Preferences panel should be shown on the right side.

**Screenshots**
No.

**Desktop (please complete the following information):**
 - OS: Windows 2004 10.0.19041
 - App version: 0.12.0.0

**Additional context**
[debug.txt](https://github.com/files-community/files-uwp/files/4960316/debug.txt)

**Comment by makunterry** [comment]
As investigated by myself, this bug should be related with using **'OneDrive'** environment variable.
in `Files/View Models/SettingsViewModel.cs` reading 'OneDrive' from ENV.
And did not check null before using.
Proved by adding a fake 'OneDrive' var in ENV and the preferences page showed correctly.
Please fix this.

**Comment by hunterlan** [comment]
@makunterry do you have installed OneDrive?
