### ISSUE TITLE
File size measure unit

### ISSUE THREAD

**Issue by AlfaSierra92** [files-community/files-uwp#1535]
**Describe the bug**
Issue with file size when language is set to Italian.

**To Reproduce**
1. Set app language to "Italiano (Italia)"
2. Explore any folder

**Expected behavior**
Files dimension should be show correctly (e.g. app shows "knowledge Gase" instead KB)

**Screenshots**
Attacched.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909 18363.959
 - App version: v0.12.0.0

**Additional context**
![Bug](https://user-images.githubusercontent.com/4050967/88185478-44a12a80-cc34-11ea-8ee0-064d45264699.jpg)

**Comment by Jaiganeshkumaran** [comment]
@AlfaSierra92 It shows the translated version instead of the English string and currently, KB is translated as knowledge Gase in Italian. If you think this is wrong, please modify the translation resource file and open a PR. You can learn about translation in the Wiki.

**Comment by AlfaSierra92** [comment]
I checked Files.it-IT.xlf to correct the strings but it seems to have been corrected with a commit already 9 days ago; surely with next update issue will be no more. Thanks!
