### ISSUE TITLE
Can't create new tabs

### ISSUE THREAD

**Issue by rdrtnk** [files-community/files-uwp#1537]
**Describe the bug**
Can't open new tabs.

**To Reproduce**
1. Go to 'More options'
2. Click on 'New Tab'
3. Nothing happens.

**Expected behavior**
It should open a new tab, but it doesn't.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Insider (Dev Channel) 20170.1000
 - App version: v0.12.2.0

**Additional context**
Restarting won't fix it, neither reparing/reseting the app via Apps & features.

**Comment by duke7553** [comment]
@rdrtnk Hello there.

We recently changed the default behavior of the tabs to be in a Vertical tab flyout. 

Can you try accessing the vertical tabs flyout after creating a new tab?
![image](https://user-images.githubusercontent.com/20365014/88200905-c8e3b580-cc14-11ea-8b90-850ad5b71edf.png)

**Comment by rdrtnk** [comment]
> @rdrtnk Hello there.
> 
> We recently changed the default behavior of the tabs to be in a Vertical tab flyout.
> 
> Can you try accessing the vertical tabs flyout after creating a new tab?
> ![image](https://user-images.githubusercontent.com/20365014/88200905-c8e3b580-cc14-11ea-8b90-850ad5b71edf.png)

Hello duke7553, thanks for answering promptly.

Thanks, now I've just figured out how it works now.

Is there any keyboard shortcut to create a new tab instead of creating them by the menu?

Thanks again!

**Comment by yaichenbaum** [comment]
@rdrtnk Have you tried `ctrl + t`?

**Comment by rdrtnk** [comment]
> @rdrtnk Have you tried `ctrl + t`?

@yair100 yes. I just noticed that it indeed creates the new tab, but you're not automatically redirected to it, creating the feeling that it didn't work - unless you know you have to go to the menu and select it.

Will this be the default behavior from now on?

Thanks!

**Comment by yaichenbaum** [comment]
The expected behavior is for the app to switch to the new tab.

**Comment by SOI7** [comment]
> @rdrtnk Hello there.
> 
> We recently changed the default behavior of the tabs to be in a Vertical tab flyout.
> 
> Can you try accessing the vertical tabs flyout after creating a new tab?
> ![image](https://user-images.githubusercontent.com/20365014/88200905-c8e3b580-cc14-11ea-8b90-850ad5b71edf.png)

Please, tell me that's optional and there's a toggle to bring back the horizontal tabs layout

**Comment by mdtauk** [comment]
> > @rdrtnk Hello there.
> > We recently changed the default behavior of the tabs to be in a Vertical tab flyout.
> > Can you try accessing the vertical tabs flyout after creating a new tab?
> > ![image](https://user-images.githubusercontent.com/20365014/88200905-c8e3b580-cc14-11ea-8b90-850ad5b71edf.png)
> 
> Please, tell me that's optional and there's a toggle to bring back the horizontal tabs layout

Not at the moment

**Comment by TailyFair** [comment]
Vertical flyout tabs is very inconvenient, not only you don't see what tabs are open without any clicks, interacting with tabs is hassle.

It would be great if horizontal tabs would be brought back.

**Comment by mdtauk** [comment]
> Vertical flyout tabs is very inconvenient, not only you don't see what tabs are open without any clicks, interacting with tabs is hassle.
> 
> It would be great if horizontal tabs would be brought back.
> 
> Vertical tabs save space when there is a lot of open tabs, but I think Files UWP use case differs from let's say browser. People usually don't have more than 4 open File Explorer tabs (noticed from co-workers and myself).

There is no good visual indicator when a new tab has been created.  You have no good visual way to just see what tabs are open at a glance, when doing file system manipulations.

Vertical tab display itself is not a bad idea, and would be useful as an option, but hiding them within a flyout is bad UX in my opinion.

I am not sure what is being solved by moving the Tabs out of a clearly visible region.

**Comment by duke7553** [comment]
> Vertical flyout tabs is very inconvenient, not only you don't see what tabs are open without any clicks, interacting with tabs is hassle.
> 
> It would be great if horizontal tabs would be brought back.
> 
> Vertical tabs save space when there is a lot of open tabs, but I think Files UWP use case differs from let's say browser. People usually don't have more than 4 open File Explorer windows (noticed from co-workers and myself) and that kind of beats the purpose of having vertical tabs.

This is one of the many reasons we removed the horizontal tabstrip, because it took up far too much space for one/two tabs open at once.

**Comment by duke7553** [comment]
> There is no good visual indicator when a new tab has been created. You have no good visual way to just see what tabs are open at a glance, when doing file system manipulations.

Improvements in this area are coming soon, but we prefer to keep it separate from the tabs area.
 
> Vertical tab display itself is not a bad idea, and would be useful as an option, but hiding them within a flyout is bad UX in my opinion.

Maybe we could promote the flyout more?

> I am not sure what is being solved by moving the Tabs out of a clearly visible region.

See https://github.com/files-community/files-uwp/issues/1193

**Comment by mdtauk** [comment]
> > There is no good visual indicator when a new tab has been created. You have no good visual way to just see what tabs are open at a glance, when doing file system manipulations.
> 
> Improvements in this area are coming soon, but we prefer to keep it separate from the tabs area.
> 
I will remain hopeful this solution is functional.

> > Vertical tab display itself is not a bad idea, and would be useful as an option, but hiding them within a flyout is bad UX in my opinion.
> 
> Maybe we could promote the flyout more?
> 
At this stage, I predict users would probably prefer to keep the tabs, and change the sidebar implementation.  I remain convinced the flyout is a poor substitute for visible tabs.  Promoting it is not going to substitute for an always present UX.

> > I am not sure what is being solved by moving the Tabs out of a clearly visible region.
> 
> See #1193
You seem to have decided to sacrifice the TabView, to maintain an sidebar being separate from the content view.  I am not sure the usefulness of the NavigationView sidebar equals that of the tabs.

There are examples of other file exploring interfaces that may be useful to explore.
![063TMWhg5qVmzTrO7EgywWq-12 v_1592944612](https://user-images.githubusercontent.com/7389110/88407285-cf675e00-cdc9-11ea-90b0-9b2cc508626e.png)
![finder dark list](https://user-images.githubusercontent.com/7389110/88407357-e9a13c00-cdc9-11ea-93f4-ff859c645f9f.jpg)
![finder dark three panes](https://user-images.githubusercontent.com/7389110/88407360-ea39d280-cdc9-11ea-9806-20c3e386eac9.jpeg)

![elementary-files-tabs-restore 1](https://user-images.githubusercontent.com/7389110/88407577-338a2200-cdca-11ea-97e2-90d1a91ee490.png)

The tab metaphor does not always require the components to be contained to an area.

In the Discord server I posted a couple of images of an app design using visible tabs.  
![image](https://user-images.githubusercontent.com/7389110/88407862-a4313e80-cdca-11ea-8b2a-86e56ba2c9eb.png)
![image](https://user-images.githubusercontent.com/7389110/88407897-b27f5a80-cdca-11ea-8854-b1e4eb906f17.png)

I am not for a moment suggesting these layouts are better than what you are currently using.  But I would ask that you consider if a flyout is really necessary to be set as the only option (as opposed to an option to "Hide tab views" in the settings).

And if you really feel the sidebar can lead to some degree of confusion over hidden tabs - would you consider changing the visual approach of the sidebar, to "correct" the grouping of elements within a tab?
