### ISSUE TITLE
Allow users to turn off recent items

### ISSUE THREAD

**Issue by 1466587594** [files-community/files-uwp#1538]
**Is your feature request related to a problem? Please describe.**
Certain people dont want to show recent items due to privacy reasons.

**Describe the solution you'd like**
Allow users to turn off recent items.

**Describe alternatives you've considered**
Nothing.

**Additional context**
Nothing.

**Comment by Jaiganeshkumaran** [comment]
I proposed this earlier but they said they will do it later. This can be merged with #366.

**Comment by duke7553** [comment]
Duplicate of #366
