### ISSUE TITLE
Put UWP-Preview Files with its configuration to place interaction with Razer Chroma RGB

### ISSUE THREAD

**Issue by AngerZeur** [files-community/files-uwp#1540]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by AngerZeur** [comment]
Put UWP-Preview Files with its configuration to place interaction with Razer Chroma RGB

**Comment by AngerZeur** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/60907149/88237315-665ed980-cc55-11ea-88dd-7e4daf0b70e0.png)

**Comment by AngerZeur** [comment]
configuration for files UWP-Preview interface stay with O Razer Chroma RGB

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
