### ISSUE TITLE
The tabview scroll buttons aren't properly aligned

### ISSUE THREAD

**Issue by soumyamahunt** [files-community/files-uwp#1543]
**Describe the bug**
The scroll buttons in tabview aren't properly aligned.

**To Reproduce**
1. Launch files-uwp app.
2. Go to a folder with sufficiently large path.
3. Right click on it and open it in new tab.
4. Open the vertical tabview flyout.

**Expected behavior**
The scroll buttons should be centered.

**Screenshots**
![ApplicationFrameHost_v7vPqEoW7p](https://user-images.githubusercontent.com/51203900/88253882-06a61400-ccd1-11ea-92dd-e8a594144fdd.png)

**Desktop (please complete the following information):**
 - OS Version : Windows 10 1903 18362.239
 - App version: v0.12.0

**Additional context**
Also the the style of button should match the style of rest of buttons in the app.

**Comment by yaichenbaum** [comment]
In this, there shouldn't be any scroll buttons, the expected behavior would be for a tool tip to show the full path or name.

**Comment by soumyamahunt** [comment]
> In this case, there shouldn't be any scroll buttons, the expected behavior would be for a tool tip to show the full path or name. 

In that case I will implement that, also I am thinking of disabling horizontal scrolling here entirely, since with tooltip it's not needed, also it interferes with vertical scrolling.

**Comment by Talisman39ar** [comment]
I'm on 0.12.0 but don't see that tab flyout - I just have the 3-dots and the search (which doesn't work - clicking on it does nothing). Am I missing something?

**Comment by soumyamahunt** [comment]
> I'm on 0.12.0 but don't see that tab flyout - I just have the 3-dots and the search (which doesn't work - clicking on it does nothing). Am I missing something?

You mean you don't have that button?? Have you enabled this:

![ApplicationFrameHost_mXhyUEpLEY_LI](https://user-images.githubusercontent.com/51203900/88406852-deacd280-cdee-11ea-87b2-60691b77c928.jpg)

**Comment by Talisman39ar** [comment]
At least on my 0.12.0.0 that toggle isn't in Settings.
Though upon further reading about how this supersedes horizontal tabs along the top, I'd actually want to stay with horizontal 😉 - fewer clicks, less information hidden. This may make sense in an overflow situation with loads of tabs (though that seems like a super edge case), but otherwise definitely a worse UX.

**Comment by yaichenbaum** [comment]
> At least on my 0.12.0.0 that toggle isn't in Settings.
> Though upon further reading about how this supersedes horizontal tabs along the top, I'd actually want to stay with horizontal 😉 - fewer clicks, less information hidden. This may make sense in an overflow situation with loads of tabs (though that seems like a super edge case), but otherwise definitely a worse UX.

The new tab layout is only in the beta builds right now, hovering over the flyout button will automatically expand the flyout so there is no need for extra clicks. We are still exploring the options and we will continue to improve the new experience before rolling out the changes to everyone else.
