### ISSUE TITLE
Executables do not run in the directory they are executed in

### ISSUE THREAD

**Issue by CrankySupertoon** [files-community/files-uwp#1555]
**Describe the bug**
A clear and concise description of what the bug is and why it is more urgent than other issue reports. Can't answer this? Please return to the previous page and file a regular bug/feature report.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.12.0]

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
