### ISSUE TITLE
Yet another vertical tab/side panel layout suggestion

### ISSUE THREAD

**Issue by yarikv8601** [files-community/files-uwp#1556]
I think I finally found the best side panel layout look that can solve all frustration from removing horizontal tab layout.
Pros of this layout:

- Keeps everything compact and in one place
- All opened tabs can be visible all the time. No need to press dedicated button to reveal them.
- Quick access list and tabs list can be switched fast and easy between themselves.

![files_side_panel_tabs_v3](https://user-images.githubusercontent.com/52413473/88336326-7520bb80-cd3d-11ea-9191-1ec5abf1a702.png)
![files_side_panel_tabs_v3_tabson](https://user-images.githubusercontent.com/52413473/88336335-794cd900-cd3d-11ea-8674-d501662a9cdd.png)

**Comment by R3voA3** [comment]
Looks sweet.

**Comment by yaichenbaum** [comment]
@yarikv8601 Thank you for sharing your concept for Files UWP, at the moment, there are no plans to implement the design.
