### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by awsomenes** [files-community/files-uwp#1558]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
I believe it would be a neat feature to drag a file from one tab to another. For example: lets say you have a picture in a picture folder. You have the picture folder in one tab and your downloads folder in another tab. It would be great if you can drag the photo file from your pictures tab to the downloads tab and that photo will be moved to the downloads folder
**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
This is already available in the latest beta build and will roll out to all users once we have finished testing this feature.
