### ISSUE TITLE
Add a badge to folder icons indicating that the folder is empty

### ISSUE THREAD

**Issue by R3voA3** [files-community/files-uwp#1574]
I just thought it would be handy to see before opening a folder whether or not it's empty. This could be indicated by a badge displayed at the icon of the folder.

**Comment by XPoppyX** [comment]
What about something like this?

**left:** empty
**right:** contains items

![Anotación 2020-07-25 191452](https://user-images.githubusercontent.com/61259627/88468109-d1eeb400-ceac-11ea-81f8-6bd5256c76c1.png)

**Comment by R3voA3** [comment]
How does it look in the light theme? It should be easily distinguishable.

**Comment by XPoppyX** [comment]
what about this?

is the icon used in OneDrive

![Anotación 2020-07-26 083423](https://user-images.githubusercontent.com/61259627/88479104-e6699580-cf1a-11ea-9f67-64e4aa17c9ae.png)

**Comment by R3voA3** [comment]
Looks sweet.

**Comment by XPoppyX** [comment]
@yaichenbaum

**Comment by yaichenbaum** [comment]
This has been implemented with #1614.
