### ISSUE TITLE
When I drag and drop an item with right click, Show a dialog to choose if I want to copy or move

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#1579]
instead of a dialog, it could also be a context menu

![Right-Click-Held-Options](https://user-images.githubusercontent.com/61259627/88482161-9811c200-cf2d-11ea-8139-89e5d52ed80f.png)

**Comment by gave92** [comment]
@XPoppyX copy, move or [https://github.com/files-community/files-uwp/pull/1573](create shortcut) 😜

**Comment by XPoppyX** [comment]
Duplicate of #1396
