### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by nightfire68** [files-community/files-uwp#1583]
**Is your feature request related to a problem? Please describe.**
I would like an option to access my iCloud drive and photos

**Describe the solution you'd like**
I would like to see an option to the setting to enable support for iCloud, weather that be a portal to the website, or direct support.

**Describe alternatives you've considered**
An alternative I have considered is a portal to the website embedded in the program in a side tab labeled iCloud.
**Additional context**
N/A

**Comment by Jaiganeshkumaran** [comment]
Duplicate of #242
