### ISSUE TITLE
Cut-Pasting or Renaming Any Files/Folders that require Elevation make the app crash immediately..

### ISSUE THREAD

**Issue by m98770** [files-community/files-uwp#1584]
**Describe the bug**
Cut Pasting or Renaming any files/folders that require elevation makes the app crash immediately.

**To Reproduce**
1. Cut a txt file and paste that into Folders like Program Files or Windows 
2. or try to rename a sub-folder inside those folders .

**Expected behavior**
It should ask for Elevation rights and paste/rename files/folders  like it does in default File explorer.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.264]
 - App version: [v0.12.4]

**Comment by Jaiganeshkumaran** [comment]
Duplicate of #1353

**Comment by m98770** [comment]
> Duplicate of #1353

not only for Renaming but also for cut-pasting . it doesnt even ask for elevation or Administrator Rights on my machine, just crashes
