### ISSUE TITLE
Weird Translation of Data Units under Chinese

### ISSUE THREAD

**Issue by Verplitic** [files-community/files-uwp#1593]
I found that, under Chinese translation, data units such as gigabyte is translated to "吉字节（G字节（B））".
This is no doubt too long and confusing to read. *吉字节* is the correct translation to gigabyte, but we are still more accustomed to **GB**. The default name of gigabyte under Chinese in Windows is GB, too.
![the confusing translation](https://user-images.githubusercontent.com/57583509/88605040-658dd380-d0ab-11ea-8925-872964b3e58f.png)
Other units also have such issue. Please fix them, thanks.

**Comment by ChihweiLHBird** [comment]
![image](https://user-images.githubusercontent.com/43905414/88637072-8dab1180-d06e-11ea-8a4f-915456dbc1ca.png)
请问你觉得是否需要将“字节”保留呢？还是改为“B”？其他的都转换为英文字符吗？比如: 兆字节--->MB

**Comment by Verplitic** [comment]
其它都转换成英文字符。“字节”的话，我个人没有意见，也许也可以为了统一而写成“B”吧…

**Comment by ChihweiLHBird** [comment]
> 其它都转换成英文字符。“字节”的话，我个人没有意见，也许也可以为了统一而写成“B”吧…

谢谢，我查一下台港澳的繁体中文是否也是这样显示，然后再看看要怎么改。

**Comment by yaichenbaum** [comment]
This issue has been fixed with #1610.
