### ISSUE TITLE
“Show Hidden Files, Folders, and Drives” switch couldn't be turned on.

### ISSUE THREAD

**Issue by liukenny961** [files-community/files-uwp#1595]
When I use file-UWP, I notice that it doesn't show hidden folders. I went to Settings and then to files and folders, but I found that the “Show Hidden Files, Folders, and Drives” switch couldn't be turned on. What's the problem?
![Snipaste_2020-07-28_10-52-07](https://user-images.githubusercontent.com/65520199/88614139-b0b2e100-d0c1-11ea-9077-479787ac34a0.png)

**Comment by Jaiganeshkumaran** [comment]
@liukenny961 It hasn't been implemented yet.
