### ISSUE TITLE
Recycling multiple files, and switching to another tab results in an app crash

### ISSUE THREAD

**Issue by duke7553** [files-community/files-uwp#1596]
**Describe the bug**
Moving multiple files to the recycle bin, and switching to another tab results in an app crash

**To Reproduce**
1. Moving multiple files to the recycle bin
2. switch to another tab
3. Observe crash

**Expected behavior**
Obviously no crash here. We need to find a better way to associate the current app instance with the AppService connections

**Screenshots**
![image](https://user-images.githubusercontent.com/20365014/88692762-713dc200-d0cc-11ea-9c2c-e6fa0b1e15a6.png)

**Additional context**
Files.IShellPage.FilesystemViewModel.**get** returned null.

Maybe @gave92 has a solution for this one? I'd propose passing the current app instance to the AppService connection for each request.

**Comment by gave92** [comment]
@duke7553 hi! could you confirm if something like the following is sufficient to solve the issue? (sorry I'm pasting code below, I'll make a proper PR when I can)

In App.xaml.cs -> Connection_RequestReceived 
```cs
// If we are currently displaying the reycle bin lets refresh the items
if (App.CurrentInstance.FilesystemViewModel?.CurrentFolder?.ItemPath == path)
{
    await Windows.ApplicationModel.Core.CoreApplication.MainView.CoreWindow.Dispatcher.RunAsync(CoreDispatcherPriority.Normal,
    () =>
    {
        // Let's check again in case current folder has changed
        if (App.CurrentInstance.FilesystemViewModel?.CurrentFolder?.ItemPath == path)
        {
            App.CurrentInstance.FilesystemViewModel.RefreshItems();
        }
    });
}
```
