### ISSUE TITLE
Capability to show and use .lnk shortcut files

### ISSUE THREAD

**Issue by kwolf111316** [files-community/files-uwp#1599]
**Is your feature request related to a problem? Please describe.** No
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] unable to see or use .lnk files

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add support for .lnk files if possible

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. Na

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment]
Merging with #177.
