### ISSUE TITLE
盘符显示打不开

### ISSUE THREAD

**Issue by jh-chn** [files-community/files-uwp#1605]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by hez2010** [comment]
Please describe your problem in details.

**Comment by ChihweiLHBird** [comment]
可以详细描述一下您遇到的问题吗？

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
