### ISSUE TITLE
Shortcuts: Add "Open file location" in context menu

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#1606]
it is faster to open the file location from the context menu, it would be a bit annoying to have to open the properties window first
![Anotación 2020-07-29 215651](https://user-images.githubusercontent.com/61259627/88871677-78f18980-d1e6-11ea-9470-b6e4f4463c2b.png)

**Comment by yaichenbaum** [comment]
This feature was implemented with #1573.

**Comment by XPoppyX** [comment]
really?, I know it's in the properties window, but I don't see that it's in the context menu

**Comment by XPoppyX** [comment]
there is no "Open file location" in the context menu of file shortcuts

![Anotación 2020-07-29 223652](https://user-images.githubusercontent.com/61259627/88874012-07b4d500-d1ec-11ea-8417-05f28c1abef4.png)
