### ISSUE TITLE
Crush when user change his own default folders to hidden

### ISSUE THREAD

**Issue by VOSAICA** [files-community/files-uwp#1617]
# Crush when user change his own default folders to hidden
When I changed the folder of Downloads, Documents, Music etc. from the User folder in C disk to D disk and set them hidden, the  program would not be able to locate them and will crush.

![image](https://user-images.githubusercontent.com/57782331/89029365-db6e9500-d360-11ea-9e87-c623ecffbfdc.png)
In this situation, the program will crush when I press the button of the Documents in the files UWP

**Comment by Jaiganeshkumaran** [comment]
Currently Files doesn't support hidden files so that's why it doesn't work.
