### ISSUE TITLE
Properties for drives

### ISSUE THREAD

**Issue by hunterlan** [files-community/files-uwp#1627]
**Is your feature request related to a problem? Please describe.**
Default file manager has a possibility to show properties a driver. It would be really good, if you added this feature.

![image](https://user-images.githubusercontent.com/38838841/89122707-4390b880-d4d2-11ea-8c50-6db85af2aa7a.png)
![image](https://user-images.githubusercontent.com/38838841/89122716-53a89800-d4d2-11ea-94e9-5879c94a428c.png)

**Comment by tsvietOK** [comment]
Drive properties you could see through right click in its root.

**Comment by hunterlan** [comment]
> Drive properties you could see through right click in its root.

Got it, but is it possible to add it, when you click on drive in left-side?

**Comment by tsvietOK** [comment]
It will be added as soon as possible.

**Comment by XPoppyX** [comment]
for sidebar: #1212
