### ISSUE TITLE
SFTP support 

### ISSUE THREAD

**Issue by Dubzer** [files-community/files-uwp#1629]
Hi. It would be great to see SFTP support in Files UWP.
Currently, there is only three options to use SFTP in Windows: 
1. WinSCP - an old app that is not very comfortable to use. (there is also MobaXterm, but it just works even slower)
2. Apps that create a virtual network drive. As they integrate with Windows Explorer, this is not a bad option, but path that Explorer uses is not Unix-style, so you can't just copy path to some file and paste it in terminal. (for ex. Z:\etc\nginx instead of /etc/nginx)
3. Total Commander and Far Manager SFTP plugins (which is not modern and more for old-school users)

Files UWP can take it advantages and get users who are looking for a modern SFTP client on Windows.
I've seen SFTP packages on nuget, so it might not be that difficult to implement

**Comment by yaichenbaum** [comment]
Merging with #1342.
