### ISSUE TITLE
放置多个同步盘于侧边栏的驱动器区域

### ISSUE THREAD

**Issue by ChenShihuan** [files-community/files-uwp#1632]
**Is your feature request related to a problem? Please describe.**
目前files-uwp的驱动器栏仅提供了一个OneDrive同步盘的按钮，我希望得到多个

**Describe the solution you'd like**
可以放置多个同步盘于侧边栏的驱动器区域，并提供自定义（本人电脑上挂着三个OneDrive，包括一个个人版和两个商业版，和一个NextCloud）

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by ChihweiLHBird** [comment]
Duplicate of #16

**Comment by ChenShihuan** [comment]
> Duplicate of #16
> 该问题已被提出，建议前往 #16 进行讨论哦，谢谢。

感谢指路
