### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by Beefy32659** [files-community/files-uwp#1651]
**Is your feature request related to a problem? Please describe.**
I'm annoyed that I can't drag files from one tab to another.

**Describe the solution you'd like**
I'd like to be able to drag and drop files between tabs.

**Additional context**
Add any other context or screenshots about the feature request here. Ex: Desktop Windows 10 Pro (20H2), version 0.12.5.0?

**Comment by yaichenbaum** [comment]
Drag and drop for files and tabs has been implemented in the latest beta build.
