### ISSUE TITLE
App crashed when copy a folder to USB drive

### ISSUE THREAD

**Issue by LinuxWincomn** [files-community/files-uwp#1652]
**Describe the bug**
I'm new to this app. This is a great one!
But 5 munites ago, I tried to copy a folder from C: to a USB drive via the app, it crashed.
I checked the log file, there was nothing useful, just reguler info.

**Desktop**
 - OS Version: Windows 10 2004 19041.388
 - App version: v0.12.0.0

**Comment by Jaiganeshkumaran** [comment]
@LinuxWincomn Do you mean USB drive?

**Comment by LinuxWincomn** [comment]
@Jaiganeshkumaran Yes! Sorry, my bad.

**Comment by Jaiganeshkumaran** [comment]
@LinuxWincomn Could you post the log file so that we can understand your issue better. You can access it from Settings->About->Open log location.

**Comment by LinuxWincomn** [comment]
@Jaiganeshkumaran I've already deleted the app. Sorry about that.

**Comment by Jaiganeshkumaran** [comment]
@LinuxWincomn We can't fix the problem without knowing where, how and when it occurs. Please install our app again and then try it again. If it crashes, post the log file. If it works the close the issue.

**Comment by LinuxWincomn** [comment]
@Jaiganeshkumaran Alright, I will try it today.

**Comment by LinuxWincomn** [comment]
@Jaiganeshkumaran Sorry for the delay. I have tried twice, the first time gone nothing and the second time got crashed. Here is the log files. 
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5054484/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/files-uwp/files/5054486/debug.txt)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #1780.
