### ISSUE TITLE
Weird behaviour when deleting multiple items in the Recycle Bin

### ISSUE THREAD

**Issue by R3voA3** [files-community/files-uwp#1653]
See the video:
https://youtu.be/3zVWEbXpQ1k

**Comment by Jaiganeshkumaran** [comment]
When deleting multiple items from the recycle bin, Files UWP deletes an item one by one and so every time it deletes a file the folder gets modified so Files UWP reloads it again. A solution would be to temporarily unsubscribe from the changed event.

**Comment by gave92** [comment]
We can probably do something smarter than clearing and reloading the whole bin contents. We should be able to just remove the deleted file from the list as with the other folders.
