### ISSUE TITLE
Fluent Design Context Menu in Desktop

### ISSUE THREAD

**Issue by seohyun1108** [files-community/files-uwp#1654]
**Is your feature request related to a problem? Please describe.**
In Files UWP, I can experience Fluent Design context menu. However, in Desktop, it is an original Windows 10 context menu. But I like Fluent Design context menu like Files UWP's.

**Describe the solution you'd like**
Can you redesign the context menu in Desktop like Files UWP context menu? I like it.

**Additional context**
Fluent Design Context Menu in Desktop like this!

![maxresdefault](https://user-images.githubusercontent.com/43906110/89407833-70ef9780-d75a-11ea-94e6-341366443c3a.jpg)

**Comment by XPoppyX** [comment]
Sorry if I misunderstood you but it is a feature request that you must send to microsoft, not here, since it is change outside Files UWP.
