### ISSUE TITLE
Files UWP can suddenly crash

### ISSUE THREAD

**Issue by CreepKY** [files-community/files-uwp#1670]
Files UWP can suddenly crash when I click the next folder.
For example, when I firstly clicked and opened Files UWP, it run smoothly. But sometimes as soon as I click the next folder, the whole screen will get stuck and finally the application crash.
The issue often happen, almost everytime.
My OS version: Windows 10 2004
My Files UWP version:0.12.0.0

**Comment by Talisman39ar** [comment]
Same for me. Happens on both my HP desktop and ThinkPad laptop. Both are running 2004, but it was this was before that installed too. Usually for me the crash process is instant - it doesn't sit there and hang, it just disappears. There's a similar issue in another thread, maybe they should be combined? I had posted a log file in that one

**Comment by Jaiganeshkumaran** [comment]
@CreepKY Please post the log file so that we can understand your issue better and fix it.

**Comment by THX1188** [comment]
Same for me,...

**Comment by AqilCont** [comment]
Same for me with the specs stated above

**Comment by yaichenbaum** [comment]
@CreepKY Is this still an issue in v0.13.1?

**Comment by duke7553** [comment]
Thanks again for your feedback. 

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
