### ISSUE TITLE
App crashed when opening Documents folder

### ISSUE THREAD

**Issue by R3voA3** [files-community/files-uwp#1676]
App randomly crashed when accessing the Documents folder through the side bar.

[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5044816/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/files-uwp/files/5044817/debug.txt)

**Comment by gave92** [comment]
Judging from the log file this issue is the same as the one fixed here: #1717 (KeyNotFoundException due to shortcuts)

**Comment by yaichenbaum** [comment]
@R3voA3 Is this still an issue in v0.13.1?

**Comment by R3voA3** [comment]
Not sure if fixed, but I can't reproduce it.
