### ISSUE TITLE
Add "Clear Recycle Bin" to the context menu when the Recycle Bin is opened

### ISSUE THREAD

**Issue by R3voA3** [files-community/files-uwp#1678]
![image](https://user-images.githubusercontent.com/17484252/89705169-41f44400-d95b-11ea-9da6-241fa9dfc359.png)

**Comment by Jaiganeshkumaran** [comment]
@R3voA3 It's already there as 'Empty recycle bin' when the recycle bin has deleted items

**Comment by R3voA3** [comment]
Strange. It didn't show up for me, otherwise I would not have reported it.

**Comment by Jaiganeshkumaran** [comment]
@R3voA3 Which version of Files are you using?

**Comment by R3voA3** [comment]
I restarted the app and now it's showing fine. I think this can be closed for now.
