### ISSUE TITLE
Keyboard shortcut to gain focus on file location bar

### ISSUE THREAD

**Issue by menturi** [files-community/files-uwp#1683]
To my knowledge there currently is not a way to gain focus of the file location / address bar using keyboard shortcuts. This feature request is for implementation of a keyboard shortcut to gain focus of the file location bar using *F6* or *Alt+d*, which are the shortcuts used in other programs:

**Firefox and Chrome:** F6 and Alt+d.
**File Explorer:** Alt+d

**Comment by yaichenbaum** [comment]
@menturi The latest beta build uses `ctrl + l` to focus on the navigation bar.
