### ISSUE TITLE
rename bug

### ISSUE THREAD

**Issue by TarsChiu** [files-community/files-uwp#1684]
**before** 
1. Go to '设置'
2. Click on '.实验性'
3. Scroll down to '双击重命名‘
**then**
1. Go to 'Any file'
2. Click on '重命名'
3. See error
It does not rename, but opens the file directly

**Expected behavior**

**It should be renamed**

**Comment by Jaiganeshkumaran** [comment]
@TarsChiu You need to click on the name part of the grid to rename using double tap or click. Clicking somewhere else will open the file instead.

**Comment by TarsChiu** [comment]
I know it can double click on the file name and rename it

The point is, after you turn off the experimental feature, double-click the rename

A normal right - click rename ,but it is opens a file




我知道它可以双击文件名可以重命名
重点是，在关闭实验性的功能双击重命名后
正常的右键重命名却是打开文件

&nbsp;


TarsChiu
tarschiu@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jaiganesh Kumaran"<notifications@github.com&gt;; 
发送时间: 2020年8月9日(星期天) 中午11:41
收件人: "files-community/files-uwp"<files-uwp@noreply.github.com&gt;; 
抄送: "瞿泰秭"<2059192947@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [files-community/files-uwp] rename bug (#1684)





 
@TarsChiu You need to click on the name part of the grid to rename using double tap or click. Clicking somewhere else will open the file instead.

**Comment by gave92** [comment]
This should be fixed with #1736

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.

**Comment by duke7553** [comment]
@gave92 Thank you for the prompt action on this one.
