### ISSUE TITLE
Gray out unfocused tab header

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#1693]
![Anotación 2020-08-09 210618](https://user-images.githubusercontent.com/61259627/89745945-d9a18180-da84-11ea-92a7-1b84bec38988.png)

**Comment by yaichenbaum** [comment]
@XPoppyX We don't see a reason to change the style of the unfocused state, if you still feel it should be changed, can you please fill out the issue template to help us evaluate this change?
