### ISSUE TITLE
New Featurn Request

### ISSUE THREAD

**Issue by Radcliffe-Bai** [files-community/files-uwp#1696]
Hope that I can drag my files from one files-uwp window to another files-uwp window.
I also hope that I can drag my files to the desktop conveniently, and do not need to drag it, then click the "copy"

**Comment by Radcliffe-Bai** [comment]
Maybe my English is so bad that you can't understand what I mean, here is the Chinese version.
我希望可以直接再files-uwp窗口之间拖拽来移动文件，和从files-uwp的窗口拖拽文件到桌面，而不用在拖拽之后还要再点击一次复制到所在位置。

**Comment by Jaiganeshkumaran** [comment]
@Radcliffe-Bai Better dragging support is coming in the next version (0.13).
