### ISSUE TITLE
A progress bar please?

### ISSUE THREAD

**Issue by LinuxWincomn** [files-community/files-uwp#1702]
**Is your feature request related to a problem? Please describe.**
When I copy something to anywhere, there is no display of the progress.

**Describe the solution you'd like**
I think it could be better to have a progress bar for copping, deleting, cutting.

**Describe alternatives you've considered**
Maybe you can make it like this: when something is copied and pasted, a gray colored icon can be displayed in the view, and then filled by its own color with progress.

**Comment by XPoppyX** [comment]
Duplicate of #114
