### ISSUE TITLE
You need to double click on an about page item to open

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#1705]
**Expected behavior**
On version 0.13, you need to double click on an about page item to open it which should not be the case. Also clicking should not select it. This can be done using SelectionMode="None". For clicking use the ItemClick event and make sure to enable IsItemClickEnabled.

**Comment by R3voA3** [comment]
Something else I'd like to add to the ticket:

Why not add the licence and webpage (source code) also as a button. This would clean up the About page even more.

![image](https://user-images.githubusercontent.com/17484252/90026174-42704000-dcb7-11ea-8ec9-508e47685042.png)

**Comment by d2dyno1** [comment]
Created Pull Request #1773

**Comment by yaichenbaum** [comment]
> Something else I'd like to add to the ticket:
> 
> Why not add the licence and webpage (source code) also as a button. This would clean up the About page even more.
> 
> ![image](https://user-images.githubusercontent.com/17484252/90026174-42704000-dcb7-11ea-8ec9-508e47685042.png)

The reason we don't want to do that is because the list of licenses will grow over time.
