### ISSUE TITLE
Crash when trying to open Desktop

### ISSUE THREAD

**Issue by generalguy41** [files-community/files-uwp#1712]
**Describe the bug**
Program crashes when opening Desktop.

**To Reproduce**
1. Go to:
   a. Desktop in sidebar (if pinned)
   b. C > Users > your user > Desktop
2. Attempt to open

**Expected behavior**
Program should not crash

**Screenshots**
![ezgif-4-4aeff4d5a2b2](https://user-images.githubusercontent.com/8879244/90018835-88a7ae00-dc7b-11ea-9b4e-ef4581e3a1e2.gif)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 20185.1000]
 - App version: [v0.13.0.0]

**Additional context**
[debug.txt](https://github.com/files-community/files-uwp/files/5062845/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5062844/debug_fulltrust.txt)

**Comment by gave92** [comment]
Judging from the log file this issue is the same as the one that was (hopefully) fixed with #1717 (KeyNotFoundException due to shortcuts)

**Comment by generalguy41** [comment]
Issue seems to be fixed in v0.13.1.0.
