### ISSUE TITLE
Crash when renaming

### ISSUE THREAD

**Issue by R3voA3** [files-community/files-uwp#1713]
Happened after fresh start of the app.

[debug.txt](https://github.com/files-community/files-uwp/files/5063199/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5063200/debug_fulltrust.txt)

**Comment by seohyun1108** [comment]
Me too

**Comment by R3voA3** [comment]
> Me too

Attach your log files, please.
