### ISSUE TITLE
Use nameof() instead

### ISSUE THREAD

**Issue by d2dyno1** [files-community/files-uwp#1729]
**Is your feature request related to a problem? Please describe.**
There's nothing wrong with using `NotifyPropertyChanged("SomeProperty")`. The problem starts when the property gets renamed. You then must remember (and know where) to rename all the strings within `NotifyPropertyChanged("SomeProperty")` to avoid any hidden errors. With the new solution, VS wouldn't let you complile the app - pointing out the problem immediately.

**Describe the solution you'd like**
I'd like to propose a little code improvement - changing `NotifyPropertyChanged("SomeProperty")` -> to `NotifyPropertyChanged(nameof(SomeProperty))`

**Comment by Jaiganeshkumaran** [comment]
@d2dyno1 Don't create an issue for code changes, create a pull request instead. Use the issues section only for reporting bugs and giving feedback.

**Comment by d2dyno1** [comment]
Ok, I'll create a pull request

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Issues should be created for everything in order to avoid changes that might not get approved.

**Comment by Jaiganeshkumaran** [comment]
But this is a just minor code change not an enhancement.
