### ISSUE TITLE
"Empty Recycle Bin" is greyed out in right-click context menu, even when Bin is full

### ISSUE THREAD

**Issue by SOI7** [files-community/files-uwp#1732]
**Describe the bug**
The "Empty Recycle Bin" option in the right-click context menu of the Recycle Bin sidebar item is always greyed out, regardless if the Bin is empty or full

**To Reproduce**
1) Right click on Recycle Bin from the sidebar
2) See the option

**Expected behavior**
The option should be greyed out only when the Bin is empty

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - App version: v0.13.1

**Comment by tobias-mayer** [comment]
@SOI7 this should be fixed with my PR for #1420. 
The PR was not included in the latest release. As soon as this is released, this Bug should be fixed. 
With the current version of the code everything is working fine for me.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our stable branch and should be available from the Microsoft Store. Please subscribe to our releases to be notified when fixes like this are available.
