### ISSUE TITLE
Selection with mouse drag

### ISSUE THREAD

**Issue by antnauman** [files-community/files-uwp#1738]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by antnauman** [comment]
Please make able to select file/folders using mouse click and drag.

**Comment by Jaiganeshkumaran** [comment]
@antnauman Duplicate of #94
