### ISSUE TITLE
Switch to newly opened tab

### ISSUE THREAD

**Issue by Nuzza** [files-community/files-uwp#1739]
Perhaps add an option within settings that would set a newly opened tab as active (switch to) as currently when clicking the plus button (for a new tab) or opening a folder in a new tab does create the new tab, but doesn't switch to it as you would expect. If you take a look at how Chrome handles new tabs and you will see that it switches to it straight away without the user having to manually select the new tab.

**Comment by generalguy41** [comment]
Duplicate of #1726
