### ISSUE TITLE
Windows Explorer context menu

### ISSUE THREAD

**Issue by KaKi87** [files-community/files-uwp#174]
I would like to be able to use Windows Explorer's context menu in Files, especially its custom entries, like, in my case : WinRAR, 7-Zip, LockHunter, Beyond Compare, Git Bash, Sublime Text, etc...

The context menu is also stored in Windows Registry.

I found some of my context menu items on my Windows Registry database, but, they're not located in the same place.

There's at least these :
```
HKEY_CLASSES_ROOT\*\shell
HKEY_CLASSES_ROOT\*\shellex
HKEY_CLASSES_ROOT\Folder\shell
HKEY_CLASSES_ROOT\Folder\shellex
HKEY_CLASSES_ROOT\Directory\shell
HKEY_CLASSES_ROOT\Directory\shellex
```

*([Source](https://www.howtogeek.com/howto/windows-vista/how-to-clean-up-your-messy-windows-context-menu/))*

Some way, [CCleaner](https://www.cnet.com/how-to/clean-up-your-windows-right-click-menu-with-ccleaner/) and [other software](https://www.techspot.com/guides/1670-windows-right-click-menu/) manages to find them all.

Two software that I use, TreeSize and WinSCP, allows to display Windows Explorer's context menu, TreeSize isn't open source but WinSCP is : I found the feature in [this Delphi file](https://github.com/winscp/winscp/blob/f2dcd2124366780de568716d69c37fa3820915e0/source/packages/filemng/ShellDialogs.pas) by the `ShellDisplayContextMenu` function.

I think this approach is different from reading the Registry because it's the genuine Windows Explorer context menu which is shown, so I guess there's some way to access it directly.

Unfortunately, I there's nothing more I can do to help you figure this out.

Good luck

**Comment by yaichenbaum** [comment]
I don't think it would be possible to hook in to all those applications to do what they are meant to do.

**Comment by KaKi87** [comment]
Nothing is impossible, especially when other developers have done it before...

And the commands are specified in the Registry

![2019-07-18 12_00_05-](https://user-images.githubusercontent.com/21284089/61448706-aeb52e80-a953-11e9-842a-1d571876dba9.png)

**Comment by yaichenbaum** [comment]
Oh, I see now @duke7553 whats your take?

**Comment by lukeblevins** [comment]
@KaKi87 @yair100 Actually it is impossible because, to my knowledge, universal apps do not have access to the registry.

**Comment by yaichenbaum** [comment]
UWP apps can actually read from the registry, however I am not sure how something like this would work with localization.

**Comment by KaKi87** [comment]
Context menu strings are exclusively managed by the software which added itself to it. Indeed, if you change Files's language, the software's won't.

**Comment by yaichenbaum** [comment]
There are two types of context menu entries that I can think of, the first type would be for the open with menu and the new file menu, the second type would be for additional entries in the right click context menu for items such as 7zip.
We would probably need a way of classifying them and adding sub menus for the ones that require that like 7zip.

**Comment by BuraChuhadar** [comment]
I would like to take a look at this. However what I couldn't find is the menu options of 7-Zip. Where is the submenu items located under the registry of Windows? Here is more information how this can be done. 

https://stackoverflow.com/questions/20449316/how-add-context-menu-item-to-windows-explorer-for-folders

https://www.askvg.com/add-cascading-menus-for-your-favorite-programs-in-windows-7-desktop-context-menu/

**Comment by yaichenbaum** [comment]
The open with menu items are interesting because it includes more then the programs you would expect to show. For example, the items for text files include a bunch of strings that seem to have nothing to do with opening files.
![image](https://user-images.githubusercontent.com/39923744/79162377-23b27900-7dab-11ea-8b49-464dcd883c93.png)

**Comment by BuraChuhadar** [comment]
Some of the application's shell context menu cannot simply be retrieved from the registry. 7-Zip for example is using shell extensions. These are in-process COM objects which extend the abilities of Windows operating system. To retrieve the menu items for 7-Zip, COM object needs to be queried.

**Comment by yaichenbaum** [comment]
@BuraChuhadar We can technically check for 7zip and manually add the menu items like we do for QuickLook.

**Comment by BuraChuhadar** [comment]
I am not sure how did you get the "Open With" list from your registry. I am seeing on my end Open With is also a shell extension which needs to be queried as a COM object. See "Computer\HKEY_CLASSES_ROOT\*\shellex\ContextMenuHandlers\Open With" which then calls "%SystemRoot%\system32\shell32.dll".

**Comment by yaichenbaum** [comment]
I got mine from `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts`.

**Comment by BuraChuhadar** [comment]
I would suggest to keep it simple and look only these sections for now without shell extension functionality:
```HKEY_CLASSES_ROOT\*\shell
HKEY_CLASSES_ROOT\*\shellex  
HKEY_CLASSES_ROOT\Folder\shell  
HKEY_CLASSES_ROOT\Folder\shellex  
HKEY_CLASSES_ROOT\Directory\shell  
HKEY_CLASSES_ROOT\Directory\shellex
```

Then it can be expanded into "Open With" and/or shell extensions functionality.

**Comment by yaichenbaum** [comment]
@BuraChuhadar That sounds like a good starting point, is this something you wanted to implement?

**Comment by BuraChuhadar** [comment]
Yes I want to take a look at this please.

**Comment by BuraChuhadar** [comment]
I am also sharing this here: 
https://stackoverflow.com/questions/5708434/how-to-use-shell32-within-a-c-sharp-application
https://stackoverflow.com/questions/53035823/using-folderitemverbs-and-invoke-or-doit-to-execute-a-submenu-item-in-a-windows

**Comment by yaichenbaum** [comment]
@BuraChuhadar Make sure to keep us updated on your progress 😊

**Comment by BuraChuhadar** [comment]
So far I have this: https://github.com/duke7553/files-uwp/commit/4ee24dbb73956762910aa8b86e9baef9d522db4f

I have been experimenting with also getting the information from other ways.

**Comment by BuraChuhadar** [comment]
Current progress: https://github.com/duke7553/files-uwp/pull/699 not done yet.

**Comment by AkazaRenn** [comment]
Would it also help the support for other shell extensions? Like TC4Shell which is an archive viewer integrated into File Explorer.

**Comment by soumyamahunt** [comment]
I think an approach like Windows Terminal will be better. A single json file will store the context menu data for different file extensions in different profiles, user can edit this file to add/remove/sort the entries of context menu for a certain item. Additionally, we can provide a gui for editing context menu which may contain detected entries from registry as suggestions.

**Comment by KaKi87** [comment]
As long as there's a GUI, it's okay.

**Comment by yaichenbaum** [comment]
> I think an approach like Windows Terminal will be better. A single json file will store the context menu data for different file extensions in different profiles, user can edit this file to add/remove/sort the entries of context menu for a certain item. Additionally, we can provide a gui for editing context menu which may contain detected entries from registry as suggestions.

Most users are not interested in setting up the right click context menu.

**Comment by KaKi87** [comment]
Well, my initial feature request was to add an entry to the UWP context menu which would contain the existing entries of the Windows Explorer context menu, just like TreeSize, WinSCP, Beyond Compare, etc.
So, if that feature gets implemented, then, technically, the context menu would be customizable using existing software with Windows Explorer context menu customization features like CCleaner or ShellMenuView.
Thanks

**Comment by yaichenbaum** [comment]
@BuraChuhadar Can you share a status update where things are with this issue? Thank you 😃

**Comment by yaichenbaum** [comment]
@gave92 Thank you for all your great work on implementing this feature in #1754.

**Comment by KaKi87** [comment]
Nice ! When will the feature be available on MS Store ?

**Comment by yaichenbaum** [comment]
> Nice ! When will the feature be available on MS Store ?

The feature is already available to users in the beta flight, however it will be a at least couple weeks before we roll it out to regular users since we still working on refining the improved context menu.

**Comment by revanmj** [comment]
Is there any way to get into beta flight?

**Comment by KaKi87** [comment]
I have `Files UWP - Preview`, version `0.13.1.0`, is that the *beta flight* ? It doesn't seem so, because I can't see find the feature

**Comment by BuraChuhadar** [comment]
hello everyone, I apologize for the radio silence I have been dealing with some life/work issues and couldn't get to this work. I really appreciate @gave92 for implementing this feature this looks really nice.
