### ISSUE TITLE
When german translation isn't available it should use english

### ISSUE THREAD

**Issue by lorisobi** [files-community/files-uwp#1742]
Right now when a string isn't translated to german the app uses the russian version. Even if some people in german-speaking countries understand russian and can read cyrillic it are way less than people understanding english. So Files should use the english strings when german isn't available

![image](https://user-images.githubusercontent.com/28399150/90312932-91f97a80-df08-11ea-9ae3-357bad965f83.png)

**Comment by yaichenbaum** [comment]
@lorisobi Files UWP already defaults to English, if there is a translation available for the language a user sets then the app will use that instead.

**Comment by lorisobi** [comment]
But why does Files show some Strings to me in Russian?

**Comment by Jaiganeshkumaran** [comment]
@lorisobi That's because Russian comes first in your Windows language list. You can manage it Settings->Time & Language->Language. Windows always uses the language list order. To change the order select a language from the list and hit up or down.
