### ISSUE TITLE
Consent dialog for broadFileSysteAccess is not shown

### ISSUE THREAD

**Issue by gave92** [files-community/files-uwp#1747]
**Describe the bug**
App never shows consent dialog for broadFileSystemAccess permission (e.g after install, or if the capability is disabled in Settings)
This causes the app to launch without crashing but the only drive listed in the sidebar is the OneDrive folder and most operations fail with UnauthorizedAccessException.
Users may not know to go to Settings and enable permission without being informed by the Consent Dialog.

**To Reproduce**
1. Disable broadFileSystemAccess permission for Files UWP in Settings
2. Launch app
3. App won't show Consent Dialog

**Expected behavior**
App should show consent dialog if broadFileSystemAccess permission is denied for the app

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.13.0] from Store

**Comment by ChihweiLHBird** [comment]
Where can I disable broadFileSystemAccess permission for Files UWP in Settings? I did not find this option...
![image](https://user-images.githubusercontent.com/43905414/90328408-15d75500-df51-11ea-9239-ccfb809bdb2b.png)

**Comment by gave92** [comment]
@ChihweiLHBird it's under Settings > Privacy > File System

**Comment by Jaiganeshkumaran** [comment]
@gave92 Actually Files doesn't appear in the File system permissions in 2004+ as it grants the permission automatically if you also had a full trust component.

**Comment by gave92** [comment]
@Jaiganeshkumaran Thanks for the info. Might still be worth to fix this since we support older versions as well

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran The dialog only comes up on older versions.

**Comment by jaigak** [comment]
@yair100 I know that since 2004 allows users to grant right from the app instead of settings but if you are wondering why it's not shown in the list it is because of the full trust component.

**Comment by yaichenbaum** [comment]
2004 non longer requires access to the file system for apps with a full trust component, because of this, the consent dialog won't show in the first place.

**Comment by gave92** [comment]
Even in 2004 if the user switches off the "global" switch for the filesystem permission (the one for all the apps) it will still affect Files UWP
