### ISSUE TITLE
Ability to extract .rar files

### ISSUE THREAD

**Issue by Jackaroo05** [files-community/files-uwp#1748]
**Is your feature request related to a problem? Please describe.**
With .rar files being worked with a lot, it would be nice to have the ability to extract them via the context menu

**Describe the solution you'd like**
I would like to be able to extract .rar files via the context menu and create a subfolder in the same folder of the .rar with the .rar contents inside.

**Describe alternatives you've considered**
To be able to extract a .rar file, I have to either open the default flile explorer and find the file and extract it via 7zip or set the default .rar application to 7zip and extract it via the file manager 7zip has.

**Additional context**
I would like to to be all in one app without having to open something like 7zip and extracting it like that.

**Comment by Jaiganeshkumaran** [comment]
Related to #1562

**Comment by yaichenbaum** [comment]
Merging with #174.

**Comment by yaichenbaum** [comment]
This has been implemented in #1754.
