### ISSUE TITLE
Sarasa-Gothic font may look better if it's taken in UI 

### ISSUE THREAD

**Issue by ColbertBrave** [files-community/files-uwp#1749]
Now the font seems to be calibra and microsoft Yahei. They look ordinary.  Sarasa-Gothic font may look better if it's taken in UI.

You can download it here: https://github.com/be5invis/Sarasa-Gothic

**Comment by yaichenbaum** [comment]
We plan to continue using Segoe UI as it's the recommended font for Windows apps.
