### ISSUE TITLE
Quick access shortcuts/folders are not visible

### ISSUE THREAD

**Issue by Daksh777** [files-community/files-uwp#1759]
**Describe the bug**
The quick folder or quick shortcuts which appear in the left menu of Explorer do not appear in the app. I am only able to see the Music folder.

**Expected behavior**
All the quick access folders/shortcuts should appear in the left menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/43648146/90528786-a64fa880-e190-11ea-8fa6-9d73501ce5eb.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 1909 18363.418
 - App version: v0.13.1.0

**Comment by gave92** [comment]
Make sure you have given file system access.
You can check it in Settings->Privacy->File system.

**Comment by Daksh777** [comment]
Thank you. That worked.
