### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NoStyle27** [files-community/files-uwp#1760]
**Describe the bug**
After you set the layout mode to list view,click twice or double click after one click any file or folder，App will crash. Other layout modes will not.

**To Reproduce**
1. Open and use Files UWP
2. set the layout mode to list view
3. Click twice any file or folder/Double click after one click any file or folder

**Expected behavior**
There should be many users who are still accustomed to List View and hope it can be fixed.
**Screenshots**
![IMG_20200818_225325](https://user-images.githubusercontent.com/68083847/90529297-259ba700-e1a6-11ea-98bf-f468feb32de4.jpg)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909 18363.1016]
 - App version: [v0.13.1.0]

**Additional context**
Does this problem occur again after restarting the app?
Yes

**Comment by Jaiganeshkumaran** [comment]
@NoStyle27 Please upload the log files. You can access them from Settings->About->Open log location.

**Comment by NoStyle27** [comment]
@Jaiganeshkumaran Is this ？
![capture_20200819175440977](https://user-images.githubusercontent.com/68083847/90620850-934ae000-e245-11ea-9ba6-f5e562285ef4.jpg)

[debug.txt](https://github.com/files-community/files-uwp/files/5095570/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5095572/debug_fulltrust.txt)

**Comment by Jaiganeshkumaran** [comment]
@NoStyle27 Only debug.txt is needed for me.

**Comment by NoStyle27** [comment]
@Jaiganeshkumaran It's okay. It's all yours.

**Comment by gave92** [comment]
This should be the same issue that was fixed in #1736

**Comment by NoStyle27** [comment]
To support you
