### ISSUE TITLE
External device cannot be removed while app is opened

### ISSUE THREAD

**Issue by osieltorres** [files-community/files-uwp#1767]
**Describe the bug**
If you open an external device in app, you cannot remove device unless you close the app

**To Reproduce**
1. Plug in any external device
2. Open it in app
3. Change disk to any other and try to remove external device from taskbar option
4. Not possible to remove device, windows keeps telling that device is in use, after closing the app, then the device is removed without problem.

**Expected behavior**
App should close any link to external device when selecting the Remove device option in taskbar to allow safe extraction.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 19041.450
 - App version: v0.13.1.0

**Comment by yaichenbaum** [comment]
@tsvietOK
