### ISSUE TITLE
Difference between v0.13 and v0.13.1?

### ISSUE THREAD

**Issue by stamminator** [files-community/files-uwp#1774]
My Files UWP app has automatically updated to version 0.13.1.0. This repo doesn't mention anything about a .1 minor release, I only see a 0.13 release. What changes does this minor release contain, and why isn't it documented in the releases?

**Comment by yaichenbaum** [comment]
@stamminator 0.13.1 is just a minor revision with updated dependencies.

**Comment by stamminator** [comment]
In the interest of transparency, we should be able to view all of the code for each version we're installing on our machines.

**Comment by yaichenbaum** [comment]
@stamminator You are correct, we will try to be more transparent about minor patches in the future.
