### ISSUE TITLE
New UI Based on Edge and New Office 365

### ISSUE THREAD

**Issue by astalavista5000** [files-community/files-uwp#1790]
**Is your feature request related to a problem? Please describe.**
The app now it looks like that it's in progress for another UI refresh and is looking a bit odd, maybe the tabs being separate from the rest?

**Describe the solution you'd like**
I was thinking since Microsoft is focusing on another design language and it seems that everything is being taken from the new office 365 new dashboard that is showing as well in Edge.

**Describe alternatives you've considered**
Remove the Reveal Effect, from what Microsoft said they won't be putting any reveal effects in Edge and a leaked StartMenu design that says that the StartMenu, Desktop and Action Center are being rewritten in WinUI instead of XAML.
Take an example from the new Office 365 dashboard (you can find the design on ONMSFT) and the Vertical Tabs from the upcoming update in Edge, instead of reveal, it becomes more like a popup and other reveal/popup effect when you navigate the side bar from the Office web version.
The side bar and the topbar coming as one layout and Acrylic Effect with Search ion the right side with a small Depth Effect and navigation bar on the right (keeping is classic positions) and the preview panel will be like another layout like when you check Outlook on the Web Version.
For the Tabs you can keep it like it is now.
And for the context menus (right-click) can you edit it like OneNote right click?
![Files UI](https://user-images.githubusercontent.com/57917817/90977778-410d0600-e548-11ea-9715-dd6123c4713a.png)

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by duke7553** [comment]
@astalavista5000 Thanks for suggesting this. Usually, we don't leave large, monolithic requests open like this. 

In order to best address this in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one. 

Closing this now.
