### ISSUE TITLE
Drag and Drop and a way to make it default, please :)

### ISSUE THREAD

**Issue by g2vnn** [files-community/files-uwp#1795]
**Is your feature request related to a problem? Please describe.**
I can't drag and drop and I'm not able to open files with Files UWP, rather, the standard file explorer.

**Describe the solution you'd like**
I'd like a drag and drop feature added, and a way to make this my default, because man it's so nice.

**Describe alternatives you've considered**
Just uninstalling and waiting hopefully.

**Additional context**
App version: 0.13.1.0

**Comment by yaichenbaum** [comment]
@g2vnn Can you please provide more details on the steps to reproduce this issue?

**Comment by yaichenbaum** [comment]
I am going to close this issue as it has been inactive for over a week, please reopen it and provide more details if you are still experiencing this issue.
