### ISSUE TITLE
Unexpected closing of the application

### ISSUE THREAD

**Issue by SofyUchiha** [files-community/files-uwp#1797]
Selecting two or more items (either files or folders), right-clicking, and requesting properties closes the program completely.

![image](https://user-images.githubusercontent.com/70182567/91112943-c41e8100-e65a-11ea-9986-508e6035e970.png)

![image](https://user-images.githubusercontent.com/70182567/91112949-cd0f5280-e65a-11ea-98c8-fb7d15f43e00.png)

Outside of that, I found no critical bugs. Very good project!

Pd: Sorry for my bad english, I'm argentinian

**Comment by yaichenbaum** [comment]
@SofyUchiha Can you please fill out the issue template in order to help us troubleshoot the issue better?

**Comment by SofyUchiha** [comment]
> @SofyUchiha Can you please fill out the issue template in order to help us troubleshoot the issue better?


I would be happy to do this, but it's my first time on GitHub, I'm still learning how to use it: c I made this account to report this problem, when giving in properties having two or more elements selected, the program just closes. As soon as I get a better handle on this platform, I'll provide more information.

**Comment by Thomas1664** [comment]
I can verify this issue. I showed a friend of mine this app and as he tried to open properties the app crashed. However, it works on my device. I think this issue occurs only on Windows 10 version 1903/1909

**Comment by Thomas1664** [comment]
But this bug was fixed in #1771

**Comment by yaichenbaum** [comment]
@Thomas1664 This issue has been fixed in the `master` branch, but it has not rolled out to users yet.
