### ISSUE TITLE
Crash when closing app where New tab opened and Continue where you left off enabled

### ISSUE THREAD

**Issue by tsvietOK** [files-community/files-uwp#1799]
**Describe the bug**
App crashing every time when user closes it with New tab opened and Continue where you left off enabled

**To Reproduce**
1. Go to Settigns -> On Startup -> Enable "Continue where you left off"
2. Open new tab
3. Close app

**Expected behavior**
App should be closed properly without an error.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.450]
 - App version: [v0.13.4]

**Log file**
[debug.txt](https://github.com/files-community/files-uwp/files/5124013/debug.txt)

**Comment by d2dyno1** [comment]
I'll investigate
