### ISSUE TITLE
Increase disk capacity usage

### ISSUE THREAD

**Issue by Jianghanlin** [files-community/files-uwp#1800]
Dear developer, 
My suggestion is that the software should be able to include a diagram of disk capacity usage.

**Comment by gave92** [comment]
Disk usage is already available if you right click on the root folder of a drive > properties

<img width="250" src="https://user-images.githubusercontent.com/9673091/91211552-3f416f00-e70f-11ea-83f5-750239e9d3f0.png"/>

**Comment by Jianghanlin** [comment]
Thanks for your reminder. What you are talking about is a detailed display and a way to check. But what I mean is that I hope to add a way to quickly check the disk capacity, which can be displayed in the main interface immediately. The following is a reference picture. The picture I designed may be a bit ugly, hahaha
![Snipaste_2020-08-26_16-34-30](https://user-images.githubusercontent.com/41952800/91281677-f810b800-e7ba-11ea-9c2a-ed327dbee7ed.png)

**Comment by d2dyno1** [comment]
I think that would make the user interface cluttered, you can already see the disk usage when hovering on the disk

**Comment by yaichenbaum** [comment]
Merging with #366.
