### ISSUE TITLE
Windows 'under-construction' UWP File explorer

### ISSUE THREAD

**Issue by Cyberdroid1** [files-community/files-uwp#1801]
To open the app - 

Open Start and enter this code -

explorer shell:AppsFolder\c5e2524a-ea46-4f67-841f-6a9465d9d515_cw5n1h2txyewy!App

Click or press enter on first result. The app opens.

Attaching screenshot of app
![image](https://user-images.githubusercontent.com/51435948/91204356-95b7a900-e721-11ea-94f9-6e934f3a185e.png)

**Comment by gave92** [comment]
There is also the new File Explorer beta that is found on Windows 10X emulator, it looks *a lot* like Files UWP :)

![image](https://user-images.githubusercontent.com/9673091/91211300-d9ed7e00-e70e-11ea-9f49-d6db507075a8.png)

**Comment by d2dyno1** [comment]
> There is also the new File Explorer beta that is found on Windows 10X emulator, it looks _a lot_ like Files UWP :)
> 
> ![image](https://user-images.githubusercontent.com/9673091/91211300-d9ed7e00-e70e-11ea-9f49-d6db507075a8.png)

The Windows 10X File Explorer looks 💩 imo. The Files UWP look so much better + they have tab support

**Comment by SOI7** [comment]
The only thing I like more in Windows 10X is the shortcuts buttons in the toolbar, but other than that I prefer Files UWP by Miles

**Comment by duke7553** [comment]
Thanks for the positive feedback. I'll close this now.
