### ISSUE TITLE
"Something went wrong" notification

### ISSUE THREAD

**Issue by SOI7** [files-community/files-uwp#1809]
**Describe the bug**
I keep getting a "Something went wrong" notification each time I close or reduce Files UWP. The irony is that the app didn't even crash

**To Reproduce**
Open the app, then close or reduce it

**Expected behavior**
No notification at all (the app is working fine apparently)

**Screenshots**
![image](https://user-images.githubusercontent.com/50930970/91327121-6bb7c280-e7c5-11ea-8df8-47ea2550975e.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - App version: v0.13.4

**Log file**
This is what Log file says:

2020-08-26 17:57:13.9234|ERROR|Files.App|Puntatore non valido.

Error trying to serialize the value to be written to the application data store|System.NullReferenceException: Puntatore non valido.

Error trying to serialize the value to be written to the application data store

**Comment by duke7553** [comment]
I get this too whenever I minimize the app.

**Comment by gave92** [comment]
This just got fixed in 9e1461a6736c010b2f8c7d4b3699afd8159f87be
@d2dyno1 confirm?
