### ISSUE TITLE
App asks for file system access permission on Win10 2004 and doesn't show local drives.

### ISSUE THREAD

**Issue by yarikv8601** [files-community/files-uwp#1813]
**Describe the bug**
When Files app starts, it asks for granting file system access permission. After pressing 'Grant Permission' button, in settings page there's no Files app listed. However I'm able to access any folder or file on any of of my local drives by entering folder path manually. Also drives do not show on the side panel.

**To Reproduce**
1. Open Files UWP app.
2. Click on 'Grant Permission' button.
3. When file system settings page is shown, there's no Files app shown on the list of apps that can access file system.
4. Returning back to Files app, there's no drives at the side panel.

**Expected behavior**
The app must automatically access the file system and show all local drives in the side panel since I'm using Win10 version 2004 and Files UWP is a full-trust app.

**Screenshots**
![Аннотация 2020-08-26 234448](https://user-images.githubusercontent.com/52413473/91355472-de8d6180-e7f6-11ea-81d2-3f9f503239f0.png)
![Аннотация 2020-08-26 234625](https://user-images.githubusercontent.com/52413473/91355507-e9e08d00-e7f6-11ea-87c6-c8cb0d82e763.png)
![Аннотация 2020-08-26 234708](https://user-images.githubusercontent.com/52413473/91355513-ed741400-e7f6-11ea-950a-d2557496a1d9.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 19041.450
 - App version: v0.13.4.0

**Additional context**
Complete re-installation didn't solve the problem.

**Log file**
[debug.txt](https://github.com/files-community/files-uwp/files/5132734/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5132735/debug_fulltrust.txt)

**Comment by gave92** [comment]
@yarikv8601 could you check again with version 0.13.6? It may still crash but it will log more useful debug info

**Comment by yarikv8601** [comment]
@gave92 logs from version 0.13.6:
**debug.txt**
`2020-08-31 22:44:21.8290|INFO|Files.App|App launched|
2020-08-31 22:44:22.0290|INFO|Files.Filesystem.DrivesManager|Drive added: C:\, Fixed|
2020-08-31 22:44:22.0610|INFO|Files.Filesystem.DrivesManager|Drive added: D:\, Fixed|
2020-08-31 22:44:22.0940|INFO|Files.Filesystem.DrivesManager|Drive added: E:\, Fixed|
2020-08-31 22:44:22.1330|INFO|Files.Filesystem.DrivesManager|Drive added: F:\, CDRom|
2020-08-31 22:44:22.1590|WARN|Files.Filesystem.DrivesManager|One or more errors occurred. (Отказано в доступе. (Exception from HRESULT: 0x80070005))|System.UnauthorizedAccessException: Отказано в доступе. (Exception from HRESULT: 0x80070005)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Files.Filesystem.DrivesManager.<>c__DisplayClass20_0.<<GetDrives>b__1>d.MoveNext() + 0xb7`

**debug_fulltrust.txt**
`2020-08-31 22:44:23.0766|INFO|FilesFullTrust.QuickLook|QuickLook detected: False|
2020-08-31 22:44:43.0872|INFO|FilesFullTrust.Program|Argument: Terminate|`

**Comment by Talisman39ar** [comment]
I'm getting the same Grant Permission request, and the same issue where the list of apps granted file system access is blank - on both my HP desktop and Lenovo laptop, using v14 of Files UWP. On my desktop, Files continues to work anyway, and I'm seeing my external drives. But on my laptop, it crashes immediately, and there's a toast message saying "something has gone wrong". LMK if you want log files from either one.

On my desktop, Files is running much faster now - the refresh of a new director level is far quicker, probably 2-3x faster than before (though I'd guess about half as fast as regular File Explorer)

**Comment by gave92** [comment]
@Talisman39ar yes, the log files for both would be useful. Thanks!

**Comment by gave92** [comment]
@Talisman39ar thank you. Looking at the log files, the issue you see on the HP is the same @yarikv8601 reported. On the lenovo is a different one, could you open a new issue describing the problem you experience on the lenovo?

**Comment by yarikv8601** [comment]
@gave92 I think I should mention that before it all started I manually installed KB4568831 update and activated updated Start Menu using registry. Reverting to old Start menu didn't fixed the issue with Files app though.

**Comment by Talisman39ar** [comment]
@gave92 Having the same issue on the HP now too - Files starts (though window doesn't populate with files list), toast message about something went wrong appears, and Files disappears. Here's the log files from the HP - I'll do the Lenovo later and file a separate ticket for that, don't have it with me right now

[debug.txt](https://github.com/files-community/files-uwp/files/5204651/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5204652/debug_fulltrust.txt)

**Comment by gave92** [comment]
@Talisman39ar could you check if disabling the "Continue where you left off" option in the app's settings "solves" the issue ?
