### ISSUE TITLE
Selecting multiple files and using cut (ctrl+x) crashes the program.

### ISSUE THREAD

**Issue by DeDaMrAzR** [files-community/files-uwp#1816]
**To Reproduce**
1. select all files
2. Click on cut or ctrl+x
3. See error, or not (:

**Expected behavior**

**Desktop (please complete the following information):**
 - OS:  Windows 10 2004 19041.450
 - App version: v 0.13.1.0

**Additional context**
I think title is self explanatory.

**Log file**
[debug.txt](https://github.com/files-community/files-uwp/files/5132967/debug.txt)

**Comment by gave92** [comment]
Thanks for this feedback item. I can reproduce this in both ListView and GridView modes as long as there are enough items in the folder to make scrollbars appear. 👍

**Comment by yaichenbaum** [comment]
This issue was fixed with #1820.
