### ISSUE TITLE
File UWP flashes back when deleting a file

### ISSUE THREAD

**Issue by eachann1026** [files-community/files-uwp#1821]
File UWP flashes back when deleting a file 
**Now the software is still prone to collapse and unstable**

**Comment by yaichenbaum** [comment]
@eachann1026 Can you please fill out the issue template so we can better understand the issue?

**Comment by duke7553** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
