### ISSUE TITLE
Add Scoop and Chocolatey package managers installation method

### ISSUE THREAD

**Issue by rashil2000** [files-community/files-uwp#1824]
**Is your feature request related to a problem? Please describe.**
Many people use package managers. It's just a part of the workflow. Adding an option to install through either Scoop or Chocolatey is extremely easy. 
**Describe the solution you'd like**
I'd like to install and update Files-UWP through the commandline, i.e. using a package manager, preferably Scoop or Chocolatey. I know I can install it through winget, but that package manager is still in early stages and is not widely popular.

**Comment by yaichenbaum** [comment]
Unfortunately it looks like Winget is the only package manager that currently support Msix installers.

**Comment by Jaiganeshkumaran** [comment]
@yaichenbaum They don't officially support MSIX however since they rely on PowerShell script you can actually deploy MSIX to them as a PowerShell script that installs it.

**Comment by yaichenbaum** [comment]
@rashil2000 @Jaiganeshkumaran Files is now available from Chocolatey https://chocolatey.org/packages/files.

**Comment by rashil2000** [comment]
@yaichenbaum I suppose that Scoop installation would be possible now too? Scoop already supports .msixbundle files. 

If Files allows installation to a custom location, I can help in preparing the Scoop manifest.

**Comment by yaichenbaum** [comment]
@rashil2000 Feel free to take the msixbundle from the release page, we usually put the bundle up a day or two after publishing a new release.

**Comment by rashil2000** [comment]
@yaichenbaum I was making the Scoop manifest. I'm running into some missing DLL errors while using running Files.exe from the extracted msixbundle. Specifically, `vcruntime140_app.dll`, `SharedLibrary.dll` and `mrt100_app.dll`. 

Could you reopen this? How do I proceed? Scoop relies on running that exe.

**Comment by yaichenbaum** [comment]
> @yaichenbaum I was making the Scoop manifest. I'm running into some missing DLL errors while using running Files.exe from the extracted msixbundle. Specifically, `vcruntime140_app.dll`, `SharedLibrary.dll` and `mrt100_app.dll`.
> 
> Could you reopen this? How do I proceed? Scoop relies on running that exe.

I just tested the bundle, and it seems like it works on my end, it could be you need to add those dlls manually for Scoop.

**Comment by jimleroyer** [comment]
Are there any instruction on how to install Files using Scoop? I don't see any available package for Files when running `scoop search file` from both the `main` and `extras` buckets.

**Comment by rashil2000** [comment]
Files is not present in Extras or Main. I wasn't able to create a manifest, I still face the same missing DLL errors even today from the msixbundle, even when I have all sorts of VC++ Redistributables installed.

**Comment by yaichenbaum** [comment]
@rashil2000 can you see if you can get the dlls from this package? https://filescommunity.blob.core.windows.net/files/preview/Files.Package_2.0.43.0_Test/Files.Package_2.0.43.0_x86_x64_arm64.msixbundle

**Comment by rashil2000** [comment]
Same error

**Comment by t3dium** [comment]
any luck?
