### ISSUE TITLE
Acrylic didn't work on Windows 10 ver. 2004 (20201.1000)

### ISSUE THREAD

**Issue by EugeneVe** [files-community/files-uwp#1828]
Acrylic didn't work on Windows 10 ver. 2004 (20201.1000) toggle Acrylic on/off doing nothing. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by yaichenbaum** [comment]
@EugeneVe Can you try update to v0.13.1?

**Comment by Jaiganeshkumaran** [comment]
@EugeneVe You need enable Acrylic. It isn't applied by default.

**Comment by duke7553** [comment]
Thanks again for your feedback. 

_Since we didn't hear from you on this topic for 6+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
