### ISSUE TITLE
Preview for each tab

### ISSUE THREAD

**Issue by xmha97** [files-community/files-uwp#183]
Internet Explorer shows preview for each tab that is open at the moment

![IE Tabs Preview](https://cdn.guidingtech.com/media/assets/WordPress-Import/2012/06/IE-Tabs-Preview.png)

Please add this feature.

**Comment by szaimen** [comment]
Yeah this would be nice! 
(Should be shown for all tabs not only for different windows)

**Comment by yaichenbaum** [comment]
We are following a lot of the behavior of Edge, Edge doesn't function this way so I don't think we should add this feature.

**Comment by szaimen** [comment]
okay but maybe then this button:
![image](https://user-images.githubusercontent.com/42591237/67966919-02970b00-fc05-11e9-8bd8-9dfca208a1f0.png)

Or hovering images (when hovering over with the mouse) for tabs (like in chrome):
![image](https://user-images.githubusercontent.com/42591237/67967168-64577500-fc05-11e9-96bb-a8a0929db92b.png)

**Comment by yaichenbaum** [comment]
@szaimen Both of the features you brought up in the last comment are things we plan on implementing in the future.

**Comment by yaichenbaum** [comment]
@xmha97 Thank you for opening this issue, there are not any plans to implement this option but if users request it in the future we will reevaluate.
