### ISSUE TITLE
Registry replacement to open Files UWP launches the app for everything else related to Explorer

### ISSUE THREAD

**Issue by dockyflash** [files-community/files-uwp#1835]
Hi, after following [these steps](https://github.com/files-community/files-uwp/wiki/Replacing-File-Explorer-with-Files-UWP) opening folders was fine but when I went to open "additional power options" on System > energy and suspension it opened Files UWP, so I went on the search bar to open the control panel and it also opened Files. I know this is just a "hack" but so letting you guys know if no one else already did. 

Thanks

**Comment by yaichenbaum** [comment]
@dockyflash This is a known side affect of using this method. We don't recommend editing the registry if you need access to Control Panel.
