### ISSUE TITLE
There is no way of selecting multiple files without left click on the mouse

### ISSUE THREAD

**Issue by ZoroNasr** [files-community/files-uwp#1841]
When i try to select multiple files away from each other, i tried pressing on ctrl, moving then pressing the space bar, but the file was not selected. the only way to do it is to press on the left click on the mouse. 

app version : 0.13.1.0

**Comment by Jaiganeshkumaran** [comment]
@ZoroNasr You can click the bottom button in the right and select everything

**Comment by ZoroNasr** [comment]
No, i don't want to select everything, i want to select like 3 or 4 files, and i can't do everything using the keyboard, i have to use the mouse unlike the normal explorer where u can go to the files with the arrows, and click on the space bar to select them. that is what i meant !!

**Comment by Jaiganeshkumaran** [comment]
@ZoroNasr You can do that by pressing shift while you use the arrow keys.

**Comment by yaichenbaum** [comment]
@ZoroNasr Can you add your feedback to #9?

**Comment by ZoroNasr** [comment]
Well, no, if i press the shift key, it will choose all the files in the row, i was to select specific files 3 or 4 rows on top, i can click on the file, hold on to control, and then i need to move the mouse up and then left click on it. on the normal explorer, u can simply click on space bar when u reach the file u want to select, and it gets selected. I hope you got my point. Simply imagine not using the mouse at all, and you want to select only 2 files away from each other inside the same folder between 100 other files. Thanks

**Comment by yaichenbaum** [comment]
@ZoroNasr We are tracking feedback related to mouse and keyboard shortcuts in #9. Please add your feedback there so that we can keep track of it.
