### ISSUE TITLE
Cannot run bat files

### ISSUE THREAD

**Issue by Sav22999** [files-community/files-uwp#1858]
**Describe the bug**
I've found [this issue](https://github.com/files-community/files-uwp/issues/948), but it's closed and marked as "Solved", but it's not.

I can't run my .bat files

**To Reproduce**
1. Double-Click on a '.bat' file
2. The file is not executed

**Expected behavior**
Execute the bat file

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 2004 19041.450
 - App version: v0.13.1.0

**Comment by yaichenbaum** [comment]
@Sav22999 Have you tried running them as administrator?

**Comment by Sav22999** [comment]
@yair100 Ok, basically after I've executed it as administrator, it worked. And now works also without admin permissions.
