### ISSUE TITLE
Renaming a file crashes Files UWP

### ISSUE THREAD

**Issue by crashmit** [files-community/files-uwp#1859]
**Describe the bug**
Files crashes sometimes when double-clicking folders

**To Reproduce**
1. Go to a Folder
2. Double click it or Right-click and select rename
3. Files crashes

**Expected behavior**
Allow me to rename the folder

**Desktop:**
 - OS Version: [e.g. Windows 10 2004 19041.450]
 - App version: [v0.13.01]

**Additional context**
Initially I encountered the problem when double-clicking file names (with the goal to enter the folder). I have "double-click to rename" turned off, as I more often than not entered the rename flow instead of opening the folder. My thought was, that this might be the issue, but just now when right clicking and selecting rename, it crashed again. It doesn't always happen, but when it happens it usually happens with the same folder multiple times in a row. The folders are local Google Drive folders synced by Backup & Sync.

**Log file**
[debug.txt](https://github.com/files-community/files-uwp/files/5161382/debug.txt)

**Comment by gave92** [comment]
This issue should be already solved in 0.13.6

**Comment by crashmit** [comment]
Okay, then it's all fine. I'm not a beta tester and don't have access to that version yet.
