### ISSUE TITLE
Trying to open Control Panel just opens the files-uwp home screen

### ISSUE THREAD

**Issue by Forresett** [files-community/files-uwp#1865]
**Describe the bug**

**To Reproduce**
1. Make sure you set this as your default files app over the Windows File Explorer
2. Type in "Control Panel" in the Windows search
3. Try to open Control Panel-
4. Realize you are at the files-uwp home screen :(

**Expected behavior**
After opening Control Panel is just immediately sends you to the files home screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10.0.18363 Build 18363
 - App version: [v0.13.0]

**Additional context**
Restarted computer, nothing changed

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by Jaiganeshkumaran** [comment]
@Forresett Did you replace the File Explorer with Files UWP? Control Panel is part of File Explorer and as a consequence replacing it will prevent it from working.

**Comment by yaichenbaum** [comment]
This is a known side effect with the method used to set Files UWP as the default. It's not recommended if you need to use control panel.
