### ISSUE TITLE
Music control icons in taskbar popup

### ISSUE THREAD

**Issue by Cyberdroid1** [files-community/files-uwp#1870]
**Describe the bug**
The icon popup of FIles UWP in taskbar has music playback buttons (previous, play/pause, next).

**To Reproduce**
1. Launch Files UWP
2. Hover cursor on app icon
3. See the popup

**Expected behavior**
The media playback buttons should not be present there.

**Screenshots**

![image](https://user-images.githubusercontent.com/51435948/92201202-91b22680-ee99-11ea-884a-b8ce1f221dd8.png)

**Desktop**
 - OS Version: [Win10 19042.487]
 - App version: [v0.13.6.0]

**Additional context**
This problem is there all the time.

**Comment by Jaiganeshkumaran** [comment]
@Cyberdroid1 This is a known issue with Windows 10 hybrid apps (Desktop + WinRT)

**Comment by yaichenbaum** [comment]
This is a known issue for UWP apps that take advantage of the desktop bridge and there is nothing we can do on our end to fix it.
