### ISSUE TITLE
Crash when moving a tab that hasn't been loaded yet out of the window

### ISSUE THREAD

**Issue by lidua** [files-community/files-uwp#1875]
**Describe the bug**
The app crashes when moving a tab that hasn't been loaded yet out of the window

**To Reproduce**
1. Create a new tab
2. Move it out of the window

**Expected behavior**
Create a new window

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 Enterprise LTSC 1809 17763.1397]
 - App version: [v0.13.1.0]

**Log file**
[debug.txt](https://github.com/files-community/files-uwp/files/5178515/debug.txt)

**Comment by yaichenbaum** [comment]
@lidua Is this still an issue in v0.14?

**Comment by gave92** [comment]
Yup it's still an issue. Same stacktrace.
> 2020-09-12 22:52:55.3003|ERROR|Files.App|Object reference not set to an instance of an object.|System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.UserControls.HorizontalMultitaskingControl.TabStrip_TabDroppedOutside(TabView sender, TabViewTabDroppedOutsideEventArgs args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
