### ISSUE TITLE
My USB Stick Doesn't Recognize On UWP Files Devices and Drives - Preview

### ISSUE THREAD

**Issue by AngelZeur** [files-community/files-uwp#1884]
**Describe the bug**
A clear and concise description of what the bug is and why it is more urgent than other issue reports. Can't answer this? Please return to the previous page and file a regular bug/feature report.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. For instance, are you building from source or using a precompiled build/snapshot?

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.

**Comment by AngelZeur** [comment]
I have a serious problem when I put my USB stick directly on my computer the UWP Files - Preview does not recognize my PENDRIVE on the Devices and drives correct this big error please

**Comment by yaichenbaum** [comment]
@AngelZeur Please fill out the issue template to better help us understand the issue.
