### ISSUE TITLE
Media Controls in taskbar preview shouldn't exist

### ISSUE THREAD

**Issue by SOI7** [files-community/files-uwp#1900]
**Describe the bug**
I see media controls in the taskbar preview, but they don't work, and tbh I see no point on having them at all

**To Reproduce**
Hover the mouse on an open Files UWP instance

**Expected behavior**
Media controls shouldn't be there

**Screenshots**
![image](https://user-images.githubusercontent.com/50930970/92645810-b6692c80-f2e5-11ea-9fac-594a456bc0cd.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - App version: v0.14.0

**Comment by yaichenbaum** [comment]
This is an issue with Windows 10 2004, I would advise opening an issue on the Feedback Hub.
