### ISSUE TITLE
Files UWP crashes on startup, following "something went wrong" toast message

### ISSUE THREAD

**Issue by Talisman39ar** [files-community/files-uwp#1908]
**Describe the bug**
I started out mentioning this bug in #1813 but @gave92  asked me to file it separately.
I don't get to the grant permission request - app is crashing as soon as a toast message saying "Something went wrong" appears in bottom right corner.

**To Reproduce**
Start Files
Window briefly appears but doesn't populate with files
Toast message appears
Files disappears

Reboot doesn't help. This appears to have been introduced with v14.

**Expected behavior**
Files opens and stays open

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10, 2004 (non-insider)
 - App version: [v0.14.0]

**Log file**
Please post the log file here so that we can understand your problem better. You can access it from Settings->About->Open log location.
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5205617/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/files-uwp/files/5205618/debug.txt)

**Comment by gave92** [comment]
@Talisman39ar could you check if disabling the "Continue where you left off" option in the app's settings "solves" the issue?

**Comment by Talisman39ar** [comment]
I had to uninstall and reinstall in order to try that (since the app crashed before I had any chance of getting to the Settings). I think I had "Continue where you left off" turned off and I'll leave it off now, but i had set a folder on OneDrive as the default for new tabs/startup. Maybe that was causing an issue. I'll leave it to the default Files homepage and see if the problem reoccurs. I'm stilling getting the Grant Permission request every time it starts up now.
