### ISSUE TITLE
Going from Home to Recycle Bin directly creates a bug.

### ISSUE THREAD

**Issue by Cyberdroid1** [files-community/files-uwp#1935]
**Describe the bug**
When I launch Files UWP and at Home tab, I directly go to Recycle Bin and see that the screen is not updated.

**Expected behavior**
Recycle Bin screen should have appeared properly.

**Screenshots**

![image](https://user-images.githubusercontent.com/51435948/93464808-64d52900-f907-11ea-934f-9476089464eb.png)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2 19042.508]
 - App version: [v0.14.1.0]

**Additional context**
Going from any other folder and then to Recycle Bin doesn't cause this issue.

**Comment by gave92** [comment]
This issue may have been fixed with #1926 
@Thomas1664 do you confirm?

**Comment by Thomas1664** [comment]
@gave92 I can confirm that the issue doesn't occur on master.
