### ISSUE TITLE
This PC should be available in the left section

### ISSUE THREAD

**Issue by Mohsin5154** [files-community/files-uwp#210]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by duke7553** [comment]
Hello. Thanks for this feedback. It would help us if you described exactly what features you need from "This PC"

**Comment by Mohsin5154** [comment]
This PC should display all the drives as in File Explorer on Windows 10

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Henboy10** [comment]
It should also show how much storage is left in each drive
![image](https://user-images.githubusercontent.com/22181579/62741882-20881180-ba02-11e9-9107-858d40bd0aab.png)

**Comment by yaichenbaum** [comment]
If the drive space indicator would display like the picture attached, would that solve the need for a dedicated page?
![image](https://user-images.githubusercontent.com/39923744/67805262-0a20ad80-fa67-11e9-8f0b-f7cf26ff2e72.png)

**Comment by generalguy41** [comment]
Personally, I'd just like "This PC" as a home page instead of the current implementation. I don't use the favourites or the recent items, so that whole page is useless to me. Of course, that's just me.

**Comment by yaichenbaum** [comment]
I am interested in understanding what having a This PC homepage would do for you. From my view having the drives on the side is more then enough, however the one place I do see how having a dedicated page would be useful is for someone with a lot of network drives or just a bunch of regular drives.

**Comment by yaichenbaum** [comment]
Here is a basic idea of how it could look 
![image](https://user-images.githubusercontent.com/39923744/67906256-5ee92480-fb4a-11e9-9f50-e6bad1a3f4ee.png)

**Comment by generalguy41** [comment]
> I am interested in understanding what having a This PC homepage would do for you. From my view having the drives on the side is more then enough, however the one place I do see how having a dedicated page would be useful is for someone with a lot of network drives or just a bunch of regular drives.

Personal preference. I often keep my drives on the left hand side minimized anyway. It also helps for drives that have special names or icons, as those don't show up in the list. Hard to tell which drives are which based on "Local Disk (E:\)" and "Removable Drive (D:\)". (Maybe I should raise that as a bug?)

![image](https://user-images.githubusercontent.com/8879244/67906258-60b2e800-fb4a-11e9-89bc-2a59dd48f684.png)

It could be made an option like it is on the default explorer.

![image](https://user-images.githubusercontent.com/8879244/67906364-ae2f5500-fb4a-11e9-8385-cb45dd79ad64.png)

**Comment by yaichenbaum** [comment]
As far as I know we already have custom icons for different drive types. In the even this page is added there will be an option to open to it.

**Comment by generalguy41** [comment]
Sorry, I meant custom icons/images, like the Lacie drive I posted. The naming thing is more important though, as neither the external hard drive nor my network drive show their proper names (though maybe this has been addressed, I'm only on the store version).

**Comment by yaichenbaum** [comment]
There were no changes to that specific area however there is a long list of other changes and bug fixes to be included in the next update.

**Comment by szaimen** [comment]
> however there is a long list of other changes and bug fixes to be included in the next update.

BTW: When will the next update be available?

**Comment by yaichenbaum** [comment]
@szaimen as soon as a bug stopping us from creating the release package is fixed.

**Comment by yaichenbaum** [comment]
We will have information to share on this feature request very soon and we will need your feedback to make sure its implemented the best way.

**Comment by chuchanpr** [comment]
@yaichenbaum do you have a beta for this available yet? Would love to see this.

**Comment by yaichenbaum** [comment]
@chuchanpr We are rethinking how the home page will work, the goal is to enable optional "widgets" that can be pinned to the home page, one of the possible widgets would be a drives section.

**Comment by yaichenbaum** [comment]
We have came to the conclusion that we will not be adding a dedicated page for drives, however as part of #366 we will work on creating a widget for this much requested feature and you will be able to pin it to the home page.
