### ISSUE TITLE
Add option to right click context menu to pin the current directory to the sidebar

### ISSUE THREAD

**Issue by szaimen** [files-community/files-uwp#255]
**Is your feature request related to a problem? Please describe.**
I want to add a whole smb-server to the sidebar. Since the network address section isn't shown, I cannot view network addresses and therefore pin e.g. whole SMB-servers through right click to the sidebar. (e.g. such addresses: **\\\smb-server**)

**Describe the solution you'd like**
Please enable us to pin the current path to the sidebar.

**Describe alternatives you've considered**
Maybe right-clicking on the current path (or anywhere inside the current folder) and showing the option to pin the current path to the sidebar could be the UX for that. In the file explorer you can do this through pulling the current path into the sidebar section.

**Comment by szaimen** [comment]
BTW: If I want to access my smb-server the first time, so I type \\\smb-server and press enter, I then don't get asked for my credentials. Is this a bug? Because If I do the same in file explorer, I get asked and afterwards access the server also with the files uwp app.

**Comment by yaichenbaum** [comment]
Great idea! It would be a help if you created a second issue for your second comment so we can track it separately from the feature request.

**Comment by szaimen** [comment]
> It would be a help if you created a second issue for your second comment so we can track it separately from the feature request.

I opened https://github.com/duke7553/files-uwp/issues/258 to track it separately.

**Comment by yaichenbaum** [comment]
@szaimen Thank you!

**Comment by szaimen** [comment]
@yaichenbaum You are welcome!

**Comment by kangsoto** [comment]
nice trick and good isue


Hello guys, i just want you to know there is a game called https://joker123gaming.co You can play this game where ever you are, and so simple to play.

**Comment by mexicanbuttslutt** [comment]
Who likes Mexican tight round ass
![1590405238593](https://user-images.githubusercontent.com/65930165/82850809-647dd180-9ec3-11ea-8cbc-7bdd0779bf24.jpg)

**Comment by mexicanbuttslutt** [comment]
![VideoCapture_20200524-100738](https://user-images.githubusercontent.com/65930165/82850885-a4dd4f80-9ec3-11ea-9ed1-780637418c7b.jpg)

**Comment by yaichenbaum** [comment]
@szaimen This feature has been implemented with #1084.
