### ISSUE TITLE
Refinements to Properties

### ISSUE THREAD

**Issue by szaimen** [files-community/files-uwp#259]
**Is your feature request related to a problem? Please describe.**
I suggest these refinements to the properties especially useful when comparing folders/files.
Currently I just can see the size of one file but not for folders and or when selecting more than on folder/file.

**Describe the solution you'd like**
I would like to see the overall size of a folder and/or files (and the count of folders and files inside this folder).

**Describe alternatives you've considered**
Also when choosing more than one file and/or folder, I would like to see the count of files and the overall size.

**Additional context**
This is how it is handled in file explorer:
![image](https://user-images.githubusercontent.com/42591237/67964833-41c35d00-fc01-11e9-97c6-b24c264f3aab.png)

**Comment by yaichenbaum** [comment]
This proposal seems to include all the information we need so I will go ahead and approve this for development.

**Comment by szaimen** [comment]
Would be really nice, if you would also add an option to the right-click menu to calculate the size of current selected folders directly inside the list view (per folder) , so that you are afterwards able to sort all files and folders based on their size.

If you change something inside this folder, or navigating away from the current path, I imagine that it gets resetted.

**Comment by yaichenbaum** [comment]
Have the points brought up in this issue been resolved in the recent updates? If not please let me know which things still need to be addressed, thank you 🙂.

**Comment by szaimen** [comment]
@yaichenbaum All points are addressed for single files but they don't work for a selection of files/folders which is still very important imo.
Also the size of a folder is missing from this dialog (when showing the properties of only one folder).

**Comment by yaichenbaum** [comment]
@szaimen The size for folders is a different issue, #645 that we will work on in the future. I will keep this issue open since you mentioned you still need it to support showing the properties with the total size of all the selected items.

**Comment by yaichenbaum** [comment]
This issue has been resolved with recent pull requests.
