### ISSUE TITLE
Improvements to the path-bar

### ISSUE THREAD

**Issue by szaimen** [files-community/files-uwp#278]
**Is your feature request related to a problem? Please describe.**
The path-bar can be a killer navigation feature when you know how to use it.
Unfortunately many features of file explorer are currently not working.
I will try to write them down.

**Describe the solution you'd like**

- [x] Clicking on a directory in the path bar should open it. 
- [x] Clicking one time into the Path-bar should result in automatically selecting the whole current path. (and probably also revealing the whole path, starting with e.g. "C:" or "\\\smb-share")
- [x] When the path-bar is selected, and you rightclick on your selection, edit options get shown, but they do nothing because when rightclicking it instantly leaves the edit mode. -> should work imo.
- [ ] When typing in special words, directorys get opened automatically (which is one of the killer featues of file explorer imho). you currently can type in and press enter to open the following directorys immediately: 
- - [ ] your username like "manuel" or "Manuel" or "MANUEL" -> you get the point (so it doesn't depend on the typing and also fits to all other directorys that I am listing below)
- - [x] all default user directorys like "downloads" or "documents"...
- - [x] your connected drives like "c:" or "D:"
- - [ ] open a folder inside the current directory
- - [ ] open the Recycle Bin 
- - [ ] probably more but I cannot remember 😅

**Describe alternatives you've considered**
> - your connected drives like "c:" or "D:"

Is maybe not the most intuitive way to do so: 
- [ ] So I propose to just enter "c" or "d" without the ":" sign. Maybe both could work?
- [ ] Also beeing able to open all items that are added to your favorits (also self added items) based on their shown name in the left navigation bar this way would be a killer feature imho ;) (and this is also currently not possible with file explorer)

**Comment by szaimen** [comment]
BTW: Sry for spamming your repo with ideas but I think files UWP has really the potential to become an amazing piece of software!

**Comment by yaichenbaum** [comment]
First of all we love all your ideas and they are extremely helpful! Keep them coming.

> When typing in special words, directorys get opened automatically (which is one of the killer featues of file explorer imho). you currently can type in and press enter to open the following directorys immediately:
This is something called environmental variables #182 

Everything on the list makes sense and we will try to address as many of them as possible when we work on enhancing this area.

**Comment by yaichenbaum** [comment]
>  open a folder inside the current directory

What would this add over appending the folder name to the directory path?

> So I propose to just enter "c" or "d" without the ":" sign. Maybe both could work?

I think `c:` should be enough.

> Also being able to open all items that are added to your favorites (also self added items) based on their shown name in the left navigation bar this way would be a killer feature imho ;) (and this is also currently not possible with file explorer)

Can you clarify what you are requesting with this one?

**Comment by szaimen** [comment]
> > open a folder inside the current directory
> 
> What would this add over appending the folder name to the directory path?

The advantage would be that it would be faster: (and is also possible with file explorer)
Because if you first select the navigation bar, the whole path gets selected which makes sense, then you can just type in the new folder name and don't have to press another key to navigate to the end of the path first.

Maybe you could also compare it to the cd command:
if you are in a directory, you can just type in the folder name (after cd) to navigate into the folder instead of entering the whole path.

I hope that explanation makes sense...

> > So I propose to just enter "c" or "d" without the ":" sign. Maybe both could work?
> 
> I think `c:` should be enough.

okay

> > Also being able to open all items that are added to your favorites (also self added items) based on their shown name in the left navigation bar this way would be a killer feature imho ;) (and this is also currently not possible with file explorer)
> 
> Can you clarify what you are requesting with this one?

It could work like this: if you have pinned a folder like "examplefolder" to the sidebar, you could open that folder if you type in "examplefolder" into the navigation bar.

**Comment by yaichenbaum** [comment]
> The advantage would be that it would be faster: (and is also possible with file explorer)
Because if you first select the navigation bar, the whole path gets selected which makes sense, then you can just type in the new folder name and don't have to press another key to navigate to the end of the path first.

Maybe you could also compare it to the cd command:
if you are in a directory, you can just type in the folder name (after cd) to navigate into the folder instead of entering the whole path.

I hope that explanation makes sense...

It is definitely possible, however if there is a folder called "Folder 1" in a directory and there is a different folder also called "Folder 1" pinned to the sidebar, which one should the app navigate to?

**Comment by szaimen** [comment]
> > The advantage would be that it would be faster: (and is also possible with file explorer)
> > Because if you first select the navigation bar, the whole path gets selected which makes sense, then you can just type in the new folder name and don't have to press another key to navigate to the end of the path first.
> 
> It is definitely possible, however if there is a folder called "Folder 1" in a directory and there is a different folder also called "Folder 1" pinned to the sidebar, which one should the app navigate to?

I would vote to always open the folder in the current directory first. If there is no folder with this name in the current directory, you would then open the favourite from the sidebar...

**Comment by yaichenbaum** [comment]
@szaimen Thank you for opening this issue, over the past few months we have worked on several areas to improve the navigation bar, in order to continue and help break up the work, it would be best if you opened up individual issues or commented on existing ones for each feedback item.
