### ISSUE TITLE
Consider the option to show folders between files

### ISSUE THREAD

**Issue by szaimen** [files-community/files-uwp#282]
**Is your feature request related to a problem? Please describe.**
This is possible e.g. in finder on macos so maybe you could consider this option? But I don't know if this is technically possible?

**Describe the solution you'd like**
Consider the option to show folders between files like in finder on macos. (So when sorting alphabetically or Date modified it get shown between files.

**Describe alternatives you've considered**
currently no other idea

**Additional context**
Here is a screenshot from finder from macos:
![image](https://user-images.githubusercontent.com/42591237/68503276-c0a04180-0262-11ea-90ac-f930e629e807.png)

**Comment by yaichenbaum** [comment]
Thank you for opening this issue.

**Comment by yaichenbaum** [comment]
This can probably be added as a sort option, however there doesn't seem to be much support for adding this feature.

**Comment by szaimen** [comment]
> This can probably be added as a sort option, however there doesn't seem to be much support for adding this feature.

I see, would of course love this getting implemented nonetheless.

**Comment by yaichenbaum** [comment]
@szaimen I am going to be leaving this issue open. As the app gets more users, the needs of the users change and there might be more requests for this feature.

**Comment by yaichenbaum** [comment]
Closing this issue due to lack of interest.

**Comment by yaira2** [comment]
The option to sort files together with folders is now available. You can download the latest version of Files from our website https://files.community/download
