### ISSUE TITLE
Customize Favorites

### ISSUE THREAD

**Issue by szaimen** [files-community/files-uwp#286]
**Is your feature request related to a problem? Please describe.**
I would like to remove a few of the default Favorites.

**Describe the solution you'd like**
This could be solved through right-clicking on one of the default items in the navigation bar and choosing "unpin item".

**Describe alternatives you've considered**
Alternatively this could be solved through right-clicking on one of the big default Buttons with the items inside when first opening the app. and also selecting "unpin item".

**Additional context**
Probably showing the option to open the item in a new window (or tab) could also be useful, when right-clicking on one of the Favorites.

**Comment by yaichenbaum** [comment]
This is something we should definitely do and have plans for in the future.

**Comment by yaichenbaum** [comment]
This has been implemented in v0.10 and will be rolling out to all users in the coming days.
