### ISSUE TITLE
Please let us choose the path of the default librarys through right-clicking

### ISSUE THREAD

**Issue by szaimen** [files-community/files-uwp#291]
**Is your feature request related to a problem? Please describe.**
In files explorer you are able to choose the path of the default libraries through the library properties.
This option should be changable through right-clicking on a default library.

**Describe the solution you'd like**
Maybe when right-clicking on a default library (on the sidebar and the coherent button in the favorites section), you could show the option to change the path of the library.

**Describe alternatives you've considered**
 I don't think that this option should be hidden in the properties of the default librarys like currently in file explorer.

To also have these three buttons and don't clutter the right-clicking menu of the default libraries, the three options could be hidden in a context menu that could be shown when hovering over it:
so probably:
1. right click on a default library
2. show a "Change Path" option 
3. When hovering over "Change Path" or clicking on it, you see a hidden context menu with the four options: 
- show/edit the current path
- restore the path
- move the path
- search for the target location

**Additional context**
This is how it looks in file explorer:
![image](https://user-images.githubusercontent.com/42591237/68550971-35f94700-0408-11ea-8487-22871c6c3c1d.png)

**Comment by yaichenbaum** [comment]
You should be able to do that in settings right now.

**Comment by szaimen** [comment]
Yes but only with file explorer and not only with files UWP.

**Comment by yaichenbaum** [comment]
I am not sure I understood correctly, you want the changes you made in Files Explorer to to take affect in Files UWP?

**Comment by szaimen** [comment]
No, these work for files UWP when changing them with the file explorer.
I just would like to be able to change the path with files UWP und not having to open file explorer for that :)

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/68551325-c5d3cc80-03d9-11ea-99ae-8d7f5de0a924.png)
Try going to settings > preferences to set custom locations.

**Comment by szaimen** [comment]
@yaichenbaum Thank you for the advice 👌
Actually I have completely forgotten, that this feature is already implemented. 😅
Please consider this feature request then as a request to bring this customisation to the right-click menu!

**Comment by yaichenbaum** [comment]
That I cant do, in the future we plan on making it that you can interact more with the side bar but before we do that we just need to get #289 out of the way.

**Comment by szaimen** [comment]
okay 👍
Since you already implemented the feature of changing the path, maybe one entry in the context menu is enough: "Change the path" to directly open the coherent option inside the settings.

**Comment by yaichenbaum** [comment]
@szaimen At a quick glance, the `NavigationView` does not appear to support context menus. I can probably modify the control to add support for context menus but I don't know when that will be.

**Comment by yaichenbaum** [comment]
After looking into this, it seems we will need to modify the registry in order to do this. It is technically possible, but it's recommended to stay away from that. Any thoughts?

**Comment by szaimen** [comment]
So do I understand you correctly: to add a right-click to the `NavigationView` you need to modify the registry? 

Since there are already feature requests to add some other options to the right click menu of the NavigationView, this would be just one additional option. So I would really love to see this added.

But as I said this would be enough for me:

> Since you already implemented the feature of changing the path, maybe one entry in the context menu is enough: "Change the path" to directly open the coherent option inside the settings.

**Comment by yaichenbaum** [comment]
No, context menu's are possible, it's the changing of the path that requires modifying the registry. Another option we can look into is opening the properties dialog in File Explorer to let you change it from there.

**Comment by szaimen** [comment]
So then I would vote for the following UX:
1. right-click on any library in the `NavigationView` to open the context-menu
2. click on `Change the path to the library" to open that section inside the settings and automatically enable this option (if not already enabled):
![image](https://user-images.githubusercontent.com/42591237/78505352-3efe0280-7773-11ea-9eae-b793154a6831.png)

Depending on if you can implement this, you could also automatically open the file explorer to change the path of the library, that you wanted to change directly, which would be much faster because normally you have to press on an additional button to do so but this last idea is not a must have...

**Comment by yaichenbaum** [comment]
As of now the plan is to use the default locations set in Windows. If plans change in the future we will make sure to let you know.
