### ISSUE TITLE
Feature request: default starting path

### ISSUE THREAD

**Issue by jwdotpark** [files-community/files-uwp#308]
Hi, thank you for the great application first of all especially there are not so many great UWP file browser! But I'd like to suggest 

1. Startup default path feature. 

1. Quick access sidebar would be also nice. 

Other than that It works beautifully for me. Thank you again!

**Comment by yaichenbaum** [comment]
@jwdotpark I have added this issue to the v0.8 milestone, this means that once v0.7.1 is released we will take some time to investigate these requests.

**Comment by yaichenbaum** [comment]
This has been implemented with the v0.9.2 release.
