### ISSUE TITLE
[Feature Request] Everything Search Integration

### ISSUE THREAD

**Issue by phileastv** [files-community/files-uwp#316]
### Is your feature request related to a problem? Please describe.

I think we can all agree that Windows Search (even with the latest updates) isn’t particularly great for searching through a lot of files.

As a video editor who has to find files fast, I use Everything from voidtools (with the Wox  Launcher UI) to search all my assets. In my opinion, this is one of the best and fastest Files Search engines.

**I don’t know of how Files-UWP plan to implement search in the app, have the option to select this tool as the default search method would be a great time saver.**

### Describe the solution you’d like

Add an option to replace the defaults search results with Everything when you are using the search bar. Everything has a [CLI](https://www.voidtools.com/support/everything/command_line_interface/).

Here’s some example of [projects](https://github.com/oliverschwendener/ueli/issues/93) who already has implemented this [solution](https://github.com/Wox-launcher/Wox/wiki/Default-Plugins.-Everything-Search).

### Describe alternatives you’ve considered

I know that Listary also exists as an alternative software, but has not any CLI.

### Additional context
I read on other posts that the user will need to install Everything by themselves and point to the executable CLI file. This seems complicated for the average user. I hope it is still possible to do this in the Settings. Eventually, if @duke7553 doesn’t have any idea to implement search in the app, this could be a great start to build an Search results UI.

This is definitely not a high priority request, but I see great potential in this project, and wanted to suggest this idea.

**Comment by yaichenbaum** [comment]
Search is something we started on a while ago but paused so we can focus on other areas. There are some built in API's that we will most likely use however if the result is not satisfactory we will look in to other methods like the one you mentioned above.

**Comment by yaichenbaum** [comment]
Closing this issue as there hasn't been many requests for using this search provider. We are still planning on adding search and we are tracking the feature here #333.
