### ISSUE TITLE
Side Panel options 

### ISSUE THREAD

**Issue by moutasem1989** [files-community/files-uwp#342]
enable side panel resizing using mouse and touch;
enabling and disabling side panel;
enable and disable expanding open folders in side panel;
enable and disable preview panel of selected items with quick edits of known file formats "images; docs ..."

**Comment by yaichenbaum** [comment]
Hi, can you be a little more specific what you meant by side panel?

**Comment by generalguy41** [comment]
@yair100 I assume they mean the navigation pane (I don't believe there are any other panels?)

**Comment by yaichenbaum** [comment]
There is an issue for a preview pane which is planned. I just want to make sure I understand which pane @moutasem1989 is talking about.

**Comment by moutasem1989** [comment]
![this is what i mean by Side Panel in Files UWP app](https://user-images.githubusercontent.com/32243157/71449823-58e08000-2756-11ea-8d94-ed31f9180bcc.png)
![and this is the preview panel in the legacy app](https://user-images.githubusercontent.com/32243157/71449824-58e08000-2756-11ea-9ae7-c94a07c5cf90.png)

**Comment by yaichenbaum** [comment]
A preview pane should pretty easy to add once we make a new file view model with the path of the selected file. And a control to resize both side panes is a great idea!

**Comment by yaichenbaum** [comment]
Merging with #692 and #672.
