### ISSUE TITLE
Batch rename files

### ISSUE THREAD

**Issue by tomyan112** [files-community/files-uwp#372]
For example 
insert 
delete 
remove 
replace 
rearrange

**Comment by yaichenbaum** [comment]
@RobbyRobbyRobby Would you be interested in doing an integration with Bulk File Rename and Files UWP? How it would probably make sense to do it is to detect if the Bulk File Rename is installed and then we can add some buttons to the right click context menus in Files UWP.
Then we would launch and pass a list of files over to Bulk File Rename and the user could then do whatever they want.

**Comment by RobbyRobbyRobby** [comment]
Hi @yair100,

Can UWP apps detect other apps?

Alternately we could achieve something like this through regular 'share' interaction.  the UWPFiles app has builds a share out function and I build share in functionality to Bulk File Rename.

**Comment by yaichenbaum** [comment]
@RobbyRobbyRobby Absolutely, we are already doing something like this for #348.

**Comment by generalguy41** [comment]
An alternative would be to look into Microsofts own [PowerToys](https://github.com/microsoft/PowerToys) which has a built-in bulk renamer. If that could be integrated the way QuickLook was, that could alleviate this request.

**Comment by yaichenbaum** [comment]
In fact we can look about doing both 😃

**Comment by duke7553** [comment]
We're currently looking at a way to standardize use of plugins and creating integrations for Files.

**Comment by yaichenbaum** [comment]
@RobbyRobbyRobby Is it possible to Launch BatchFileRename with parameters from Files UWP?

**Comment by jaigak** [comment]
@yair100 You can launch any app in a modal window using LaunchForResults. However, the app needs to support it.

**Comment by yaichenbaum** [comment]
There are no plans to include a built-in option for batch renaming files, however, PowerToys will work with Files UWP when #174 is implemented.
