### ISSUE TITLE
Can't display other drives 

### ISSUE THREAD

**Issue by NellPoi** [files-community/files-uwp#488]
**Describe the bug**
My computer can only display one drive,but I have a total of 6 drive letters, others devices **cannot be displayed**

**To Reproduce**
1. Launch the program
2. Authorize file management permissions

**Screenshots**
![image](https://user-images.githubusercontent.com/16631927/77903818-14fd9980-72b6-11ea-8625-d6ec4e00614f.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 10.0.18363  Ver18363]
 - App version: [v0.7.2]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
This problem cannot be fixed when restart program

**Comment by Crocodile73** [comment]
@NellPoi you really need to try 0.7.2 version

**Comment by NellPoi** [comment]
> @NellPoi you really need to try 0.7.2 version
I tried and the problem still exists
Version:0.7.2.0
![image](https://user-images.githubusercontent.com/16631927/77912835-df60ac80-72c5-11ea-8f2a-1f74492d44e3.png)

**Comment by yaichenbaum** [comment]
Drives that cannot be loaded for whatever reason will not be displayed in Files UWP. In the future, we should probably look into supporting more drives.

**Comment by lukeblevins** [comment]
@yair100 To confirm this we should probably have them post their log file.

**Comment by creamtea47** [comment]
> @yair100 To confirm this we should probably have them post their log file.

So where is the log..? I also found that when I DblClick to open any folders, it will causes a crash（100%），I can't view subfolders of any folders on this program

**Comment by yaichenbaum** [comment]
@NellPoi Did you give Files UWP files permissions?

**Comment by NellPoi** [comment]
> @NellPoi Did you give Files UWP file permissions?

Of course
![image](https://user-images.githubusercontent.com/16631927/77948715-6890d700-72f8-11ea-9c32-4c7c0fcb5fa5.png)

**Comment by duke7553** [comment]
@NellPoi Are there any other user accounts on this PC?

**Comment by duke7553** [comment]
@NellPoi Hi, I'm going to mark this as more-info

**Comment by NellPoi** [comment]
> @NellPoi Are there any other user accounts on this PC?

you're right，there are three local accounts on PC by my created

**Comment by NellPoi** [comment]
![image](https://user-images.githubusercontent.com/16631927/79762777-c0e65200-8355-11ea-8fcb-ba9b77146d83.png)
It's better than before on this version now (ver0.7.5.0) ,it fixed the most serious problem，App crash issue was fixed,but it still can't display any devices...

> @NellPoi Hi, I'm going to mark this as more-info

![image](https://user-images.githubusercontent.com/16631927/79762777-c0e65200-8355-11ea-8fcb-ba9b77146d83.png)
It's better than before on this version now (ver0.7.5.0) ,it fixed the most serious problem:App crash issue was fixed,but it still can't display any devices...

**Comment by lukeblevins** [comment]
@yair100 Is there still a log file he can post to give us more information about drive loading?

**Comment by yaichenbaum** [comment]
@NellPoi Is this still an issue in v0.9?

**Comment by NellPoi** [comment]
> @NellPoi Is this still an issue in v0.9?

No fix yet，it's only show onedrive device
![image](https://user-images.githubusercontent.com/16631927/83155610-fdb31f00-a133-11ea-8a8f-9dc626b8a15c.png)

**Comment by duke7553** [comment]
@NellPoi 
Thank you for opening this issue. Would you be able to share the log file here for additional information? You can get it by going to the folder %localappdata%/Packages, search there for the folder Files and there in the folder LocalState should be a file debug.txt, which contains a stacktrace.

**Comment by NellPoi** [comment]
> @NellPoi
> Thank you for opening this issue. Would you be able to share the log file here for additional information? You can get it by going to the folder %localappdata%/Packages, search there for the folder Files and there in the folder LocalState should be a file debug.txt, which contains a stacktrace.

[debug.txt](https://github.com/files-community/files-uwp/files/4717179/debug.txt)
I've been on my evection these days,so I didn't read your comments,I'm very sorry,I hope that it can do some help to you.

**Comment by duke7553** [comment]
#926 may fix this

**Comment by yaichenbaum** [comment]
This issue has been fixed with #1168.
