### ISSUE TITLE
Have tabs curve onto the title bar rather than going straight down (hard to explain, refer to pictures)

### ISSUE THREAD

**Issue by carmellolb** [files-community/files-uwp#508]
It looks strange currently, it goes straight down but should curve onto the title bar, like the concepts by Michael West.

IMAGES ATTACHED:

![cur](https://user-images.githubusercontent.com/49946175/78508458-123af280-7755-11ea-95ab-c23630226cde.png)
![prp](https://user-images.githubusercontent.com/49946175/78508459-123af280-7755-11ea-9c5d-57b15e07a9cc.png)

**Comment by yaichenbaum** [comment]
Thank you for opening this issue. The WinUI TabView control does not currently support bottom rounding of the corners on tabs. It is planned for [TabView vNext](https://github.com/microsoft/microsoft-ui-xaml/issues/1332). We try to keep Files UWP up to date with the latest versions of WinUI, so you should see this added around the same time it's added to WinUI.

**Comment by duke7553** [comment]
I did try back-porting the curved tab items from WinUI vNext, but I think it's best to wait for the official release for now because their implementation will be better. I'll keep this item open until it releases.

**Comment by yaichenbaum** [comment]
There is now an open pull request on the WinUI repo that will address this issue https://github.com/microsoft/microsoft-ui-xaml/pull/2201.

**Comment by yaichenbaum** [comment]
This has been addressed with #894.
