### ISSUE TITLE
Files UWP First Reactions

### ISSUE THREAD

**Issue by lindseyleeanna** [files-community/files-uwp#509]
I love the way this is going! 😲😀
Especially the mouse drag to switch between folders!  Really nice surprise! Add an option to toggle this feature on and off. Some people may start folder jumping unintentionally.
Obviously there are many things grayed out, and some things cause the app to crash onclick. 

I noticed it needs: 

- [ ] Fast Toggle hidden files button,
- [ ] The preview/details pane & quick toggle option.  I actually use this for the ability to quick edit keywords, author details, and copyright info - which I made possible with an add on called FileMeta. Please make it possible to quick edit the metadata & handle batches with the same.  Tinker around on adobe bridge for some inspiration, but make it....so much easier to get large batches done.  Make it photographer friendly.
- [ ] Get rid of the labels, or add a toggle option for them - like the taskbar.  The icons are pretty straight forward as they are. 
- [ ] Show Dimensions and MP on photo type files.  
- [x] Ability to drag folders to the left navigation pane to have them stick there - like favorites, additionally being able to drag up or down to reorder them, and option to delete the favorite (not the contents)..
- [ ] Options to color code files and content. 

:) Thanks

**Comment by yaichenbaum** [comment]
Thank you for opening this issue. Your feedback is really helpful and we will take a look at addressing them as we continue to refine the app.

**Comment by lindseyleeanna** [comment]
👍 Kindest Regards,LindseyLeeanna 2020 From: Yair AichenbaumSent: Monday, April 6, 2020 9:21 PMTo: duke7553/files-uwpCc: lindseyleeanna; AuthorSubject: Re: [duke7553/files-uwp] Files UWP First Reactions (#509) Thank you for opening this issue. Your feedback is really helpful and we will take a look at addressing them as we continue to refine the app.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yaichenbaum** [comment]
@lindseyleeanna It looks like your message got messed up, can you try editing it so that we can read it?

**Comment by lindseyleeanna** [comment]
As to that last email, yeah that does look messed up. I didn't consciously send that... lol wtf? It obviously came from my email though. I have no idea! I would just ignore all that jumble and if it happens again I'll have to figure out what's causing it.

**Comment by Frioo** [comment]
One up for syntax highlighting!
Would love to try and help with a pull request but I must admit I've never done anything related to syntax highlighting, so somone would need to point me in the right direction:)

**Comment by yaichenbaum** [comment]
@Frioo Can you clarify what you mean by syntax highlighting?

**Comment by Frioo** [comment]
@yaichenbaum I mean displaying source code in different colors and fonts according to the category of terms.

**Comment by yaichenbaum** [comment]
Are you talking about Quick Pad? Usually syntax highlighting is referring to text editors or code editors as opposed to a file explorer app.

**Comment by Frioo** [comment]
Wow I just noticed I'm on the worng tab haha
Was browsing around some cool UWP apps on github with this repo being open and notepads, was meant for the latter.

just delete my comments, sorry for the trouble

**Comment by yaichenbaum** [comment]
@Frioo No problem haha.

**Comment by lindseyleeanna** [comment]
🤣Had me confused, lol

**Comment by yaichenbaum** [comment]
@lindseyleeanna About the preview pane, have you tried out the QuickLook integration?

**Comment by lindseyleeanna** [comment]
Yes I have quicklook :) I feel like this app is different than the last time I used it?  Yes because i can now pin the folders in the left nav bar :) This is almost very usable. You have the toggle labels thing going in the settings with the burger button. I like that there aren't auto expanding dropdowns in the nav bar, and the drives are clear. Cool  👍  Libraries though??

**Comment by yaichenbaum** [comment]
> Libraries though

Can you clarify what you mean by "libraries"?

> number/date

You should be able to choose the date format from the settings page.

**Comment by lindseyleeanna** [comment]
Well I'm usually on windows file explorer and if I have a library  I can add whichever multiple folders from all over the drive and view and edit them in one place while the original file locations stay the same.
For some reason I guess I assumed this was a windows project...

**Comment by yaichenbaum** [comment]
This is a Windows project, I just wasn't sure what you meant by that.

**Comment by duke7553** [comment]
Wow. This is some great feedback!

Thank you for taking the time to open this one. In order to best address these in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one. 

Closing this now.
