### ISSUE TITLE
Design suggestion [Files 0.7.3]

### ISSUE THREAD

**Issue by xPoppyx** [files-community/files-uwp#520]
**Updated image: I have moved the menu a little higher**
![design-files2](https://user-images.githubusercontent.com/61259627/78668927-7cfd4280-78a9-11ea-97d6-3eccb7958c66.jpg)

**Comment by yaichenbaum** [comment]
I am a fan of adding the Quick Access header but I am not such a fan of shifting down the menu.

**Comment by xPoppyx** [comment]
no problem, it will not look bad if it is higher, what interests me most is the size of the texts / icons and the space between them and the side
![asdasdasd](https://user-images.githubusercontent.com/61259627/78627748-418a5600-7860-11ea-923a-f34cc4b1ba9c.jpg)

**Comment by generalguy41** [comment]
I agree with reducing the size of the font and icons, and adding the bolded headers. It adds a degree of separation and hierarchy. And while I agree with not shifting it down that much, I do like the idea of shifting it in from the left a little bit.

**Comment by xPoppyx** [comment]
> 
> 
> I agree with reducing the size of the font and icons, and adding the bolded headers. It adds a degree of separation and hierarchy. And while I agree with not shifting it down that much, I do like the idea of shifting it in from the left a little bit.

maybe like this?
![cccfg](https://user-images.githubusercontent.com/61259627/78628679-dbeb9900-7862-11ea-9be6-5ae902502edb.jpg)

**Comment by R3voA3** [comment]
I am not sure if I like the idea of a smaller font. Currently it's very easy on the eyes, if its size is decreased it might appear unsharp.

Perhaps a settings page for font and icon sizes?

**Comment by xPoppyx** [comment]
> 
> 
> I am not sure if I like the idea of a smaller font. Currently it's very easy on the eyes, if its size is decreased it might appear blurred.
> 
> Perhaps a settings page for font and icon sizes?

Whether it is blurry or not will depend on the screen resolution of the users.
an option to change the font size would be fine, everyone happy xd

**Comment by yaichenbaum** [comment]
Perhaps we will provide an option to choose between the compact style and regular style. However I would recommend waiting until you actually try this to see how it looks on your screen.

**Comment by generalguy41** [comment]
> Perhaps we will provide an option to choose between the compact style and regular style. However I would recommend waiting until you actually try this to see how it looks on your screen.

On a semi-related note, would it be possible to make the sidebar expandable? I notice that some of my drive names are cut off, and there's no way to adjust. It would be partially fixed with smaller font, but still.

**Comment by szaimen** [comment]
> On a semi-related note, would it be possible to make the sidebar expandable? 

+1

**Comment by yaichenbaum** [comment]
>I also think that this gap looks kind of random:

The small gap is to indicate a difference between the tabs and the sidebar. The plan is to make the sidebar expandable, we just haven't gotten to that yet. For the meantime, you should be able to see the full drive name by hovering over it.

**Comment by szaimen** [comment]
> The small gap is to indicate a difference between the tabs and the sidebar.

Hm, I still don't like it :/

Maybe a header like "quick access" as already proposed would solve this issue if aligned to the very top without that gap?

**Comment by xPoppyx** [comment]
> Maybe a header like "quick access" as already proposed would solve this issue if aligned to the very top without that gap?

if it's too high it'll be ugly, I edited the image and moved the menu a little higher, what do you think?

![gab-](https://user-images.githubusercontent.com/61259627/78721038-c8890e00-78f4-11ea-8b3e-d54c33fa8ef9.jpg)

**Comment by szaimen** [comment]
@xPoppyx Yes, I also think that the first variant (on the left) looks better but what about this?
![image](https://user-images.githubusercontent.com/42591237/78724737-5f25f100-792e-11ea-8bc9-b5e983ef0b58.png)

**Comment by xPoppyx** [comment]
just a little bit more space between the blue bar and the icons and it will be perfect.

![new de](https://user-images.githubusercontent.com/61259627/78725606-f1fa6780-78fd-11ea-8266-4dd60f4211dd.jpg)

**Comment by szaimen** [comment]
Maybe something like this?
![image](https://user-images.githubusercontent.com/42591237/78726359-0fe1bf80-7932-11ea-8714-dd8aeac0d952.png)

**Comment by xPoppyx** [comment]
perfect

**Comment by yaichenbaum** [comment]
We are using the default navigation menu, we don't plan on extending it further then adding an option to choose between compact and regular views. The question still remains on how large of a gap to have between the edge of the app and the header. Looking forward for some more feedback on that 🙂

**Comment by szaimen** [comment]
> We are using the default navigation menu, we don't plan on extending it further then adding an option to choose between compact and regular views. The question still remains on how large of a gap to have between the edge of the app and the header. Looking forward for some more feedback on that

This is what will work for me:
> I think what is important here is, that the gap to the left has to match the gap to the top. then it will look nice. 

Also a header like "Quick Access" will definitely be helpful solving the problem, imho.

**Comment by generalguy41** [comment]
> The plan is to make the sidebar expandable, we just haven't gotten to that yet. In the meantime, you should be able to see the full drive name by hovering over it.

Actually, it seems to only show me the size of the drive. It's no real issue to me as I can see the majority of the name of the drive.

As for the spacing above the header, here are a few options I've seen that we can discuss:
1. Even amount of space on both the top and left side of the content, but clearly more space than there is between each element ([here](https://external-preview.redd.it/nfDv3s2RIbMBpXYsoPF5wgryrejciWc_VDoSp678XQ0.png?auto=webp&s=a654f6cc7fd4fb3faebd3a40003e24bdb3af6453)).
2. Same as number 1, but with more emphasis on the hierarchy of the folders to the headers ([here](https://i.pinimg.com/originals/86/ec/41/86ec413c3d2e225e0e97b41c454497fb.png)).
3. The teased preview that Microsoft themselves showed of (what I can only assume is) an early look at the UWP File Explorer, which basically matches what's done here (though with colourful icons that I think look great). They abandon headers entirely and just use increased spacing, but still show some slight folder hierarchy ([here](https://fossbytes.com/wp-content/uploads/2020/03/Windows-10-Modern-File-Explorer-Teaser.jpg)).
4. Hamburger menu for collapsing and and integrated search bar (pretend they're lined up with the top) ([here](https://camo.githubusercontent.com/36a0848d50b1f69a2520aceb020956c769c2fe04/68747470733a2f2f692e6779617a6f2e636f6d2f65333335356336323237633533353564633137333265626562643863366232302e6a7067)).
5. The name of the app in the space (again, love the colourful icons) ([here](https://betanews.com/wp-content/uploads/2019/01/File-Explorer-hero.jpg)).

Personally I like 2 and 5, though the idea of having a hamburger menu in that spot for whenever the collapsible sidebar is implemented would make sense. It would also be nice if it were draggable as the current implementation isn't, leaving only a tiny spot beside the new tab button to use when the tabs are full.

**Comment by xPoppyx** [comment]
continue here: #692
