### ISSUE TITLE
open pictures with photos app should allow to cycle through all photos in that directory

### ISSUE THREAD

**Issue by szaimen** [files-community/files-uwp#524]
**Is your feature request related to a problem? Please describe.**
when opening a picture with the microsoft photos app, I am not able to switch to the next item in the list but have to double click on the next item instead to open that in a new instance of the photos app?

**Describe the solution you'd like**
be able to cycle through all photos in that directory with the photos app

**Comment by yaichenbaum** [comment]
@duke7553

**Comment by duke7553** [comment]
Hmm... I wonder if this is a limitation with the Photos app because we open items in a standard way.

**Comment by szaimen** [comment]
> Hmm... I wonder if this is a limitation with the Photos app because we open items in a standard way.

It works in file explorer 🤷‍♂️

**Comment by Jaiganeshkumaran** [comment]
@szaimen It works in File Explorer because it opens the image in a special way to enable Photos App to cycle through the photos in the folder.

**Comment by szaimen** [comment]
> @szaimen It works in File Explorer because it opens the image in a special way to enable Photos App to cycle through the photos in the folder.

Thanks for the insights. Then could we do the same like file explorer?

**Comment by Jaiganeshkumaran** [comment]
I don’t really know how it works but we should be able to implement it.

**Comment by yaichenbaum** [comment]
@gave92 Do you have any ideas on this?

**Comment by gave92** [comment]
@yair100 Yup, PR #1062 should fix this.
*Edit*: it fixes this only if you select multiple pictures, then you can cycle through the pictures that were selected.

**Comment by yaichenbaum** [comment]
@gave92 The issue here is it should automatically allow that even without opening all the pictures.

**Comment by gave92** [comment]
@yair100 I know, I think we could do it using the code in #1062 (like if you click on a picture it looks for other pictures in the folder and open all those) but I don't like this solution much. PR #1062 simulates what explorer does when you select some files, right click and select open.

**Comment by yaichenbaum** [comment]
@gave92 That would work but I am worried about performance issues when opening a photo in a directory with thousands of photos.

**Comment by gave92** [comment]
@yair100 Yeah totally agree. I'm not sure how explorer handles that.

**Comment by yaichenbaum** [comment]
This has been addressed with #1081, big thanks to @ADeltaX for digging into this to figure it out.
