### ISSUE TITLE
enhancement to the highlighting of an item in the left sidebar

### ISSUE THREAD

**Issue by szaimen** [files-community/files-uwp#525]
**Is your feature request related to a problem? Please describe.**
if I open a folder inside e.g. the documents folder, wasn't the idea to still highlight the documents section on the left side? instead the local disc C: is highlighted. 

**Describe the solution you'd like**
when I open a folder in e.g. the documents folder, the documents element should still be highlighted

**Comment by yaichenbaum** [comment]
@duke7553

**Comment by SOI7** [comment]
Gotta add another feedback about the left pane highlights: 
When you open the app (which shows Home as the first page) and then open another folder from the Favorites, Home is still highlighted and you result with two highlighted folders at the same time. Going back to Home and then to the folder solves the issue

**Comment by yaichenbaum** [comment]
@SOI7 That is an issue with the WinUI Navigation Menu, it will hopefully be fixed with an update to WinUI.

**Comment by yaichenbaum** [comment]
@szaimen This issue should be resolved with v0.7.6, for some reason OneDrive is still not getting highlighted correctly but we are investigating this in order to fix it.

**Comment by szaimen** [comment]
@yair100 when will 0.7.6 be available through the store? I would like to test this out! I am still running 0.7.5 and no update is available through the store...

**Comment by yaichenbaum** [comment]
@szaimen As soon as it gets past certification, this time the update is taking a little longer since we added a new capability to the app.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is resolved with the latest updates.
