### ISSUE TITLE
Highlight navigation bar when hovering over it

### ISSUE THREAD

**Issue by szaimen** [files-community/files-uwp#534]
**Is your feature request related to a problem? Please describe.**
I think the navigation bar isn't discoverable enough since 0.7.3

**Describe the solution you'd like**
like you show that a folder is selectable in the navigation bar, you could also highlight the whole navigation bar when hovering over it to make for the user visible that you can click on the navigation bar to edit the path

**Comment by xPoppyx** [comment]
I think it should be a little smaller too

**Comment by yaichenbaum** [comment]
@szaimen How about changing the cursor when the mouse is moved over the navigation bar?

**Comment by szaimen** [comment]
> @szaimen How about changing the cursor when the mouse is moved over the navigation bar?

Yes, that could work but only if combined with the highlighting imo...

**Comment by yaichenbaum** [comment]
Do you have a concept for how this could look?

**Comment by szaimen** [comment]
Maybe something like this: (just highlight the whole cliclable area when hovering over it)
![image](https://user-images.githubusercontent.com/42591237/78789447-70faa900-79ad-11ea-8d4e-24c2b8a50b91.png)

**Comment by yaichenbaum** [comment]
@szaimen Thank you for the concept, that looks really good! I am going to keep this issue open for some time to give a chance for others to give their take on this but I am fairly certain we will end up going with this design.

**Comment by generalguy41** [comment]
I think at the very least it should have a reveal effect, maybe not necessarily a full solid colour. Just to show it's clickable. Maybe test a couple of designs and get feedback in this thread.

**Comment by SOI7** [comment]
> I think at the very least it should have a reveal effect, maybe not necessarily a full solid colour. Just to show it's clickable. Maybe test a couple of designs and get feedback in this thread.

Oh yes, reveal on the navbar would be really cool, like in the old Microsoft Edge

**Comment by szaimen** [comment]
> > I think at the very least it should have a reveal effect, maybe not necessarily a full solid colour. Just to show it's clickable. Maybe test a couple of designs and get feedback in this thread.
> 
> Oh yes, reveal on the navbar would be really cool, like in the old Microsoft Edge

Actually my proposal was meant only as reveal effect and wouldn't be visible all the time: only if you hover with your mouse over it...

**Comment by XPoppyX** [comment]
@yaichenbaum
