### ISSUE TITLE
only show the scroll bar in the path if the folder name is too long

### ISSUE THREAD

**Issue by szaimen** [files-community/files-uwp#549]
**Is your feature request related to a problem? Please describe.**
see the scroll bar if the window is too narrow

**Describe the solution you'd like**
when the window is too narrow I would not show directly the scroll bar. Instead I would first hide the path in a drop-down menu a bit like nextcloud is doing that and only show the current folder that is open. 

**show current folder and only 3-points for parent directories:**
![image](https://user-images.githubusercontent.com/42591237/78772956-d0978b00-7992-11ea-86f5-379fa04bb759.png)

**parent-directories in drop-down menu:**
![image](https://user-images.githubusercontent.com/42591237/78773055-f1f87700-7992-11ea-8068-f4671f54dbef.png)

And only if the window is so narrow that not even the dropdown-menu and the current foldername fits into the navigation bar, I would show the scroll bar.

**Comment by yaichenbaum** [comment]
Closing this issue as there hasn't been many request for such a change.
