### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by yuyoyuppe** [files-community/files-uwp#550]
Great software, some feedback:
- would be nice to have an ability to hide Desktop/Downloads/etc. altogether
- initially the app doesn't have permission to access drives, so it doesn't show any of them, perhaps it would be nice to suggest granting the permission on first start
- favorite directories

**Comment by yaichenbaum** [comment]
1. We plan on an option to unpin favorites.
2. We plan on adding a dialog for this, however I should point out that the next version of Windows will no longer require you to give access for the file system.
3. Can you elaborate what you mean by this?

**Comment by yuyoyuppe** [comment]
Thanks for the answers!

>Can you elaborate what you mean by this?

basically have a quick access panel with bookmarked directories like we have in browsers.

**Comment by yaichenbaum** [comment]
> basically have a quick access panel with bookmarked directories like we have in browsers.

You can already pin directions to the Quick Access pane on the sidebar.

**Comment by yaichenbaum** [comment]
This issue has been resolved with the latest release in the Microsoft Store v0.10.0.
