### ISSUE TITLE
Use esc / tablet mode back button to go back

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/files-uwp#564]
**Is your feature request related to a problem? Please describe.**
I often use esc key to go back, in Files UWP that doesn't seem to be possible. Moreover in tablet mode the back button closes the app

**Describe the solution you'd like**
Implement esc/tablet mode back button to go back

**Describe alternatives you've considered**
None

**Additional context**
Not needed

**Comment by Jaiganeshkumaran** [comment]
Tablet mode support has been implemented in v0.9.0

**Comment by MarcAnt01** [comment]
@yair100 can this be opened? Esc key is not working

**Comment by yaichenbaum** [comment]
You can already use the `Back` key.

**Comment by MarcAnt01** [comment]
> You can already use the `Back` key.

Yes, but I'd like to use esc, like I do in some apps

**Comment by yaichenbaum** [comment]
There are no plans to support the `Esc` key.

**Comment by MarcAnt01** [comment]
> There are no plans to support the `Esc` key.

Can I ask why? Are there any drawbacks?

**Comment by yaichenbaum** [comment]
The `Esc` key is used for other functions throughout the app and it can cause potential conflicts.
