### ISSUE TITLE
Crashes when creating a folder or file with a restricted name

### ISSUE THREAD

**Issue by jcardama** [files-community/files-uwp#630]
**Describe the bug**
When trying to create a folder or file with a reserved name, it crashes.

List of names:
- CON
- AUX
- PRN
- LST
- COM0 - COM9
- LPT0 - LPT9
- NUL

**To Reproduce**
1. Go to desktop
2. Right click
3. New -> Folder
4. Type a name of the ones mentioned above
5. UWP Crashes

**Expected behavior**
An error message should pop showing you the following message as it does on explorer.exe when trying to use a reserved name: "The specified name is invalid."

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909 18363.752
 - App version: [v0.7.5.0]

**Additional context**
- The names seems to be case insensitive.
- It happens with folders and files.

**Comment by diligamer** [comment]
Windows bug.

**Comment by diligamer** [comment]
I think the error should be `The file or folder name chosen is a reserved device file name kept for backwards compatibility with older devices. Please name your file or folder something else.`
