### ISSUE TITLE
Drag File/Folder To A Previous Directory In Path To Move

### ISSUE THREAD

**Issue by eraychumak** [files-community/files-uwp#634]
**Is your feature request related to a problem? Please describe.**
Cannot move a file/folder to a previous directory within the current path.

**Describe the solution you'd like**

Example of windows file explorer:

![image](https://user-images.githubusercontent.com/44278658/79837098-d9cc2300-83a8-11ea-8ed7-e280778f5312.png)

Current result of Files UWP:

![image](https://user-images.githubusercontent.com/44278658/79837275-1009a280-83a9-11ea-858d-1b06bcfefa3a.png)

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by yaichenbaum** [comment]
This has been implemented with #1507.
