### ISSUE TITLE
Sharp corner when one isn't on the first tab (visual nitpick)

### ISSUE THREAD

**Issue by Darhagonable** [files-community/files-uwp#635]
This is just a visual nitpick but if you look at this:
(first one: when being on the first tab
second one: how I would like it to look when the first tab is not active
 third one: is how it looks currently when the first tab isn't active)
![image](https://user-images.githubusercontent.com/14127357/79977130-057d0500-849e-11ea-9e08-f9f5e7a8bb70.png)
I think the corner should be rounded since most other corners are rounded like that.
Just note that the corner should not be rounded when first tab is active or hovered.

**Comment by yaichenbaum** [comment]
@Darhagonable Thank you for opening this issue, due to performance costs with adding a round corner to large ui elements https://docs.microsoft.com/en-us/windows/uwp/design/style/rounded-corner#rounded-corners-and-performance, we will not be making this change.
