### ISSUE TITLE
Add string for "New tab" that appears in path

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#637]
**Screenshots**
![Anotación 2020-04-22 084342](https://user-images.githubusercontent.com/61259627/79983254-7b20ab00-8475-11ea-88c2-a8a4196634b1.png)

**Desktop:**
 - OS Version: Windows 10 1909
 - App version: [v0.7.7]

**Comment by yaichenbaum** [comment]
The issue of it not being localized on the tab is fixed with #640. I wasn't able to get it localized for the navigation bar, but I might of missed something.

**Comment by xPoppyx** [comment]
I will change the title since the tab header can already translate, and it only remains to be able to translate the path
