### ISSUE TITLE
Folder size is not displayed in the properties dialog

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#645]
![Anotación 2020-04-22 151419](https://user-images.githubusercontent.com/61259627/80023731-fb620300-84ab-11ea-921b-62e129114355.png)

**Comment by yaichenbaum** [comment]
Because of limitations with Windows NT filesystem (ntfs) folder sizes aren't returned as part of the standard query. This isn't specific to the properties dialog either.

**Comment by xPoppyx** [comment]
Then it is possible, but in another way?

**Comment by yaichenbaum** [comment]
It is possible, but we haven't gotten around to it yet.

**Comment by duke7553** [comment]
@xPoppyx We certainly could return this information in the Properties dialog, but it isn't part of the standard item query data. Meaning, we'd have to recursively calculate this manually.
