### ISSUE TITLE
Experimental double tap to rename files is disabling other rename methods

### ISSUE THREAD

**Issue by Faisalnk4045** [files-community/files-uwp#651]
*select a folder
*right click on it
*click on rename
*List view layout mode
instead of renaming the folder name it's opening the selected folder
Note to mention, my 'double tap to rename files' is disabled.

**Comment by xPoppyx** [comment]
in my case, when renaming a file or folder I have to manually refresh to see the change

**Comment by Chaoticoz** [comment]
Experiencing the same issue:
Disabling "Double tap to rename" stops renaming from working all together: 

![crUPmAvSdI](https://user-images.githubusercontent.com/6023076/80262551-0f655a80-868e-11ea-8bd5-67d2d39dd389.gif)

**Comment by yaichenbaum** [comment]
There are no plans to patch this issue as it's only a temporary work around for a different issue.
