### ISSUE TITLE
The app crashes when you right-click on a unformatted file

### ISSUE THREAD

**Issue by xPoppyx** [files-community/files-uwp#652]
_I don't know if "unformatted file" is the correct term, I use google translator_
![crash](https://user-images.githubusercontent.com/61259627/80111456-e938a100-854d-11ea-8f70-06a0e004f81d.gif)

**Comment by yaichenbaum** [comment]
Can you include a sample file?

**Comment by xPoppyx** [comment]
http://www.mediafire.com/file/08sa2di4ykedb7u/TEST1/file

**Comment by xPoppyx** [comment]
this no longer happens
