### ISSUE TITLE
Cannot see full long name when renaming files in grid view

### ISSUE THREAD

**Issue by xPoppyx** [files-community/files-uwp#657]
![renaming3](https://user-images.githubusercontent.com/61259627/80131944-fdd66280-8568-11ea-9e1b-dd420d2fba12.gif)

![renaming2](https://user-images.githubusercontent.com/61259627/80131658-8f91a000-8568-11ea-8ebd-4d0739a1a6bb.gif)

--------------------------------------------------------

Another thing is that after renaming you need to manually refresh to see the change.
![renaming4](https://user-images.githubusercontent.com/61259627/80132334-805f2200-8569-11ea-81df-034dc96c947a.gif)

**Comment by yaichenbaum** [comment]
@xPoppyx Can you confirm if these issues are fixed in `master`?

**Comment by xPoppyx** [comment]
Still the same, I also just realized that when reaching the end of the name advancing letter by letter, the following file is selected (as seen in the gif) , this also happens in v0.8.2
![rename](https://user-images.githubusercontent.com/61259627/82765429-febb1800-9de4-11ea-9e48-bf88c17840f5.gif)

**Comment by tsvietOK** [comment]
@yaichenbaum I could recommend only use of rename dialog. There is no way to increase height of separate item in folder, because "ItemsWrapGrid sizing all its items based on the first item's size (by default) " [source](https://github.com/microsoft/microsoft-ui-xaml/issues/2444#issuecomment-629223778)

**Comment by yaichenbaum** [comment]
I don't want to add back in the rename dialog, I think we will keep this issue open and try to find a workaround.

**Comment by xPoppyx** [comment]
is it possible to do something like this? changing the size of the icon / thumbnail and the textbox depending on how long the name is, up to a certain limit of course, and with the possibility of scrolling in the textbox, not with the mouse wheel, but when selecting (as in the gif above) or with the arrow keys

![Anotación 2020-05-24 181400](https://user-images.githubusercontent.com/61259627/82766131-6c1d7780-9dea-11ea-9a37-5d20907b6737.png)
