### ISSUE TITLE
Concept design for navigation bar

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#664]
updated:
![concepto files uwp blanco](https://user-images.githubusercontent.com/61259627/80230527-0b025880-8620-11ea-89c0-f8775d764e9a.png)

![concepto files uwp oscuro](https://user-images.githubusercontent.com/61259627/80230537-0dfd4900-8620-11ea-9468-02eac030dbfd.png)

**Comment by yaichenbaum** [comment]
I like this idea...

**Comment by R3voA3** [comment]
I like it too, it looks very clean.

**Comment by GavinYou082** [comment]
I like the design for navigation bar. I think adding another button for opening new windows besides the existing one would be a better solution. Using a flyout means you have to click twice every time when you want a new tab.

**Comment by xPoppyx** [comment]
@GavinYou082 
 > Using a flyout means you have to click twice every time when you want a new tab.

Sorry, I forgot to clarify that, it is supposed to be with the right-click

![concepto files uwp 2](https://user-images.githubusercontent.com/61259627/80209650-6de3f780-8600-11ea-9b6e-e6c8416d970d.png)

**Comment by GavinYou082** [comment]
@xPoppyx That's nice!

**Comment by SOI7** [comment]
I approve everything, but why would you remove the Up button?

**Comment by xPoppyx** [comment]
@SOI7 Well, I thought it was not very useful since you can do exactly the same in the navigation bar, but if it is useful for users then it is not necessary to remove it.

**Comment by yaichenbaum** [comment]
I don't think there is a need for the plus button to show the context menu, there will be a different context menu when right clicking on the tab strip that gives that option, most of the time when a user clicks the plus button they want a new tab.
I also like how on the current design, the address bar blends in with the design and looks like a regular header, but if you click on it then you get more functionality. I think always highlighting it will take away from the clean design.
Another option issue is that you removed a lot of the buttons from the current design that are core functionality for many users.

**Comment by SOI7** [comment]
> @SOI7 Well, I thought it was not very useful since you can do exactly the same in the navigation bar, but if it is useful for users then it is not necessary to remove it.

The function is different, the navigation buttons return you to the previous folder you opened, while the Up button returns the parent folder

**Comment by yaichenbaum** [comment]
Another thing I would like to add is that we should only show the search box when the user wants to search, the rest of the time it stays hidden and gives the app a cleaner look.

**Comment by SOI7** [comment]
> Another thing I would like to add is that we should only show the search box when the user wants to search, the rest of the time it stays hidden and gives the app a cleaner look.

Was thinking the same, switching from a button to a box when you start searching

**Comment by xPoppyx** [comment]
I'll see what I can do :)

**Comment by xPoppyx** [comment]
What do you think?
![Anotación 2020-04-23 215738](https://user-images.githubusercontent.com/61259627/80223063-c5409280-8615-11ea-9e5b-42ea60b0bc1d.png)

**Comment by R3voA3** [comment]
Very nice. So CTRL+F will auto-focus the search box?

**Comment by SOI7** [comment]
> What do you think? @yaichenbaum
> ![Anotación 2020-04-23 215738](https://user-images.githubusercontent.com/61259627/80223063-c5409280-8615-11ea-9e5b-42ea60b0bc1d.png)

It looks good, but I have mixed feelings about possible overlaps between the navbar and the eventual searchbox (unless you make the searchbox shift the navbar margin). On the other hand, I'm a big fan of condensing the current two lines, because it helps with not wasting space, which is a issue most UWPs have

**Comment by yaichenbaum** [comment]
> Very nice. So CTRL+F will auto-focus the search box?

@R3voA3 When search is implemented we will add that shortcut as well.

> What do you think? @yaichenbaum

@xPoppyx I like it!

> It looks good, but I have mixed feelings about possible overlaps between the navbar and the eventual searchbox (unless you make the searchbox shift the navbar margin). On the other hand, I'm a big fan of condensing the current two lines, because it helps with not wasting space, which is an issue most UWPs have

@SOI7 A concept we are thinking about is having the search box float down underneath the navigation bar.

**Comment by SOI7** [comment]
> @SOI7 A concept we are thinking about is having the search box float down underneath the navigation bar.

A "push" to the left would feel more natural imho, but we'll see later when Search will be a thing

**Comment by xPoppyx** [comment]
something like this, but to the left
![search-final2](https://user-images.githubusercontent.com/61259627/80224536-d2f71780-8617-11ea-8ba6-87d8ff7feca6.gif)

**Comment by yaichenbaum** [comment]
I think it would be a little more subtle then that but we will explore it at the time.

**Comment by xPoppyx** [comment]
Will we wait to receive more feedback?

**Comment by yaichenbaum** [comment]
I think your latest idea is perfect, see #676 about our priorities right now.

**Comment by diligamer** [comment]
Here's a better idea that makes it closer to explorer 
![image](https://user-images.githubusercontent.com/32780515/81410479-76344a80-9149-11ea-8299-f67cea996d51.png)
This moves the ellipsis menu to the context menu for no item selected along with the new menu, this will make space for the ribbon and a search box.

**Comment by xPoppyx** [comment]
@diligamer the previous concept was similar, but they don't want to remove those buttons

**Comment by diligamer** [comment]
The ribbon needs to be brought back.

**Comment by yaichenbaum** [comment]
There are no plans to bring back the ribbon, the goal for Files UWP is to rethink what a file explorer app should be. We feel that there are better ways to provide features and to keep the design simple for more users.

**Comment by diligamer** [comment]
I feel like there is a scatter mess of buttons, and a ribbon would clean that up. It would also expose some options that are only in settings.

**Comment by xPoppyx** [comment]
- Slightly darker properties text in list view

![Anotación 2020-05-15 210958](https://user-images.githubusercontent.com/61259627/82106797-51b01380-96f1-11ea-842c-9876fc331d51.jpg)

**Comment by Senko-Dev** [comment]
I now have VS and will start work on the change.

**Comment by yaichenbaum** [comment]
@Senko-Dev This design concept is very good but it has not yet been approved, feel free to open a pull request so we can continue the discussion.

**Comment by tsvietOK** [comment]
@yaichenbaum We should extend design concept on how window look, when it has smallest available width.
Now it looks like:
![image](https://user-images.githubusercontent.com/20501502/82491858-ee0d5800-9aed-11ea-8ef7-2bf6512812d9.png)
I have some draft example
When changing window width, some elements hiding by window border.
Normal width:
![image](https://user-images.githubusercontent.com/20501502/82492095-52c8b280-9aee-11ea-8a6a-ceac992589db.png)
Small width:
![image](https://user-images.githubusercontent.com/20501502/82492117-59572a00-9aee-11ea-9047-fcbdce98837a.png)
So, first way to fix it is increase minimal window size, second way is place path bar to new line when window has small width.

**Comment by yaichenbaum** [comment]
@tsvietOK You brought up a great point, I think it's best to leave the navigation bar how it currently is (we can make the text size a little smaller). This would prevent the issue of controls getting cut off when the window is sized small.
In order to improve the tabs experience, what do you think of collapsing the sidebar to be compact?

**Comment by tsvietOK** [comment]
@yaichenbaum I think it is a good idea, moreover there is a different [variants](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#adaptive-behavior) how it could looks like when window has small size.

**Comment by yaichenbaum** [comment]
I still think we can use the proposed design for large sized Windows.

**Comment by tsvietOK** [comment]
@yaichenbaum What do you mean? Do we use large sized design now?

**Comment by yaichenbaum** [comment]
By large size, I meant including the nav buttons and textbox on the same line.

**Comment by XPoppyX** [comment]
What if the path returns to the top position when the window is small?

**Comment by yaichenbaum** [comment]
We want to thank you for your feedback and concepts. We will be closing this issue but we will keep your feedback and ideas in mind as we continue working on the app.
