### ISSUE TITLE
Add support for recycle bin

### ISSUE THREAD

**Issue by seohyun1108** [files-community/files-uwp#669]
**Describe the bug**
I changed the default file explorer to Files UWP. However, I can not open to Recycle Bin. Also, sometimes, Files UWP closed unexpectedly.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 build 19613]
 - App version: [v0.7.7.0]

**Comment by yaichenbaum** [comment]
Thank you for opening this issue, we don't have support for recycle bin yet but we will work on that in the future. Do you have any more details about the crashes?

**Comment by seohyun1108** [comment]
Thank You!

**Comment by yaichenbaum** [comment]
@seohyun1108 The latest update added a feature flag in the experimental settings page to turn on support for recycle bin, make sure to check it out and let us know of any issues.
