### ISSUE TITLE
Ability to resize the sidebar

### ISSUE THREAD

**Issue by XeZrunner** [files-community/files-uwp#672]
**Is your feature request related to a problem? Please describe.**
It isn't related to a problem.

**Describe the solution you'd like**
When hovering between the sidebar and content edge, the cursor should change into the horizontal resizing cursor and let us change the sidebar width. The application should also save this width so we don't have to keep adjusting the sidebar width every time.

**Describe alternatives you've considered**
Increase the default sidebar width, to match Fluent Design / Windows guidelines.

**Additional context**
[Here's a quick mockup done in Paint.](https://i.imgur.com/au7iSLE.png)

**Comment by chuchanpr** [comment]
Add option to collapse the side bar, for cleaner look

**Comment by yaichenbaum** [comment]
This has been implemented with #1512.
