### ISSUE TITLE
Improve Properties dialogs' user interface design

### ISSUE THREAD

**Issue by XeZrunner** [files-community/files-uwp#674]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
At this time, the properties dialogs' design appears to be the same as the original Windows File Explorer one. I suggest giving it an user interface design refresh.

**Describe alternatives you've considered**
[This concept on Reddit got 999 upvotes](https://www.reddit.com/r/Windows10/comments/fay6j2/redesigned_properties_dialog_concept/) and I was immediately reminded of it while using the app. It would match the futuristic Fluent Design guidelines. [Direct link to image (high resolution)](https://i.redd.it/jqmrzvwc7pj41.png)

**Additional context**
Not sure how popular this would be, but utilizing `ContentDialog`s or an overlay inside the app for the Properties dialogs would look clean.
This would remove the ability to open multiple Properties dialogs though. (Multiple selections could open a special multi-file properties dialog?)
An experimental toggle for this could be interesting.

**Comment by yaichenbaum** [comment]
The dialog already follows the fluent design guidelines.

![image](https://user-images.githubusercontent.com/39923744/80229690-cd510000-861e-11ea-9abf-dcd249a9fa55.png)

**Comment by XeZrunner** [comment]
> The dialog already follows the fluent design guidelines.
Sorry, my original title was worded incorrectly. 
I would love to see a more fresh, custom design of the Properties dialog. Right now, it looks identical to the Windows File Explorer, which, to me, feels a bit dated.
Definitely not supposed to be prirority.

**Comment by xPoppyx** [comment]
maybe something like this? not much difference but it's just to get an idea
![Captura de pantalla (195)](https://user-images.githubusercontent.com/61259627/80237350-97b21400-862a-11ea-9b95-072e9fb785a4.png)

**Comment by yaichenbaum** [comment]
A number of improvements have been made to improve the properties dialog design, make sure to update to the latest version of Files UWP to get the best experience.
