### ISSUE TITLE
First official preview (v0.9)

### ISSUE THREAD

**Issue by yaichenbaum** [files-community/files-uwp#676]
As we near the first official release of Files UWP by participating in the [2020 Launch event](https://uwpcommunity.com/launch), we are focusing on stability. A number of bug reports have been filed in the past few days, and we hope that together with the community we will be able to work through all of them before Launch.

We are expecting there to be an influx of issues and contributions after the app is publicly announced and both @duke7553 and myself will be spending more time on managing the issues and pull requests. 

We are going to be keeping an eye for active contributor's and if it makes sense, we will add them as contributor to the app, giving them rights to review and merge pull requests.
If anyone is interested in contributing and is not sure what needs to be done before Launch, take a look at the todo section of the [project board](https://github.com/duke7553/files-uwp/projects/1).

Looking forward to seeing this project move forward :rocket::rocket::rocket::rocket:

**Comment by yaichenbaum** [comment]
With just one month left before Launch, our focus is going to be on fixing some of the top bugs that have been reported. If anyone wants to be assigned an issue, just add a comment to the issue to let us know.

- https://github.com/duke7553/files-uwp/issues/679 Changes to files should refresh the directory
- https://github.com/duke7553/files-uwp/issues/221 Alert user trying to delete an open file
- https://github.com/duke7553/files-uwp/issues/660 Sometimes I can't open the first folder/file in grid view mode
- https://github.com/duke7553/files-uwp/issues/657 Cannot see full long name when renaming files in grid view
- https://github.com/duke7553/files-uwp/issues/678 If you select and deselect a folder or file, you can't open it

**Comment by xPoppyx** [comment]
take a look at this, it is about network locations: #642

**Comment by yaichenbaum** [comment]
@xPoppyx That is a really interesting find, if we make good progress on the list above and it looks like there is time before Launch, then I will add #642 to the list.
I want to be transparent, there is a really long way to go and v0.8.0 is only the official launch of the preview. The app will still be in a preview state for many more months.

**Comment by xPoppyx** [comment]
It is understandable, there is a lot to fix and add

**Comment by yaichenbaum** [comment]
@xPoppyx The app will only leave preview when we feel it's ready, it already replaces File Explorer 90% of the time for me but I understand that it still has a long way to go until it's that way for everyone else.

**Comment by Jaiganeshkumaran** [comment]
I want to be assigned to #221

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran Sure! Make a comment on that issue so I can assign it to you 😃

**Comment by yaichenbaum** [comment]
### Files UWP Preview is now officially available 🚀🚀🚀🚀
Ready more about the Files UWP over [here](https://medium.com/@yairai/launching-files-uwp-preview-ed7a43985130). 
Download Files UWP Preview from the Microsoft Store [here](https://microsoft.msafflnk.net/ZaPRR).
