### ISSUE TITLE
I'd like to be prompted to replace storage items during the Paste operation

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#686]
![replace](https://user-images.githubusercontent.com/61259627/80259511-c98ba080-8653-11ea-8f09-db7c463f6856.gif)

**Comment by yaichenbaum** [comment]
I think the dialog only shows when renaming files. I agree that this should show for pasting files as well.

**Comment by yaichenbaum** [comment]
Merging with #114.
