### ISSUE TITLE
Renaming an item twice crashes the app

### ISSUE THREAD

**Issue by Chaoticoz** [files-community/files-uwp#688]
**Describe the bug**
Renaming the same item twice opens the "Item already exists" dialog and then crashes the app

**To Reproduce**
1. Open any folder
2. Rename an item
3. Rename the same item again

**Screenshots**
![W7QwXqb6ej](https://user-images.githubusercontent.com/6023076/80262276-37a08980-868d-11ea-906a-d02999f865c8.gif)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909 18363.778
 - App version: 0.7.8.0

**Comment by yaichenbaum** [comment]
I believe this issue is related to #679.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
