### ISSUE TITLE
Cannot copy and paste

### ISSUE THREAD

**Issue by seohyun1108** [files-community/files-uwp#693]
**Describe the bug**
I cannot copy a folder to another location. Files UWP was closed unexpectedly. Also, sometimes, Files UWP close unexpectedly.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19613]
 - App version: [v0.7.8]

**Comment by yaichenbaum** [comment]
Possibly related to #679, can you confirm if this error is after renaming or creating new items?

**Comment by seohyun1108** [comment]
Files UWP was closed unexpectedly when I copy a folder or file to another location...

**Comment by duke7553** [comment]
@seohyun1108 Hello there. Thanks for reporting this feedback to us. Have you noticed any improvements in this area with the latest updates?

**Comment by duke7553** [comment]
Thanks again for your feedback. 

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
