### ISSUE TITLE
Cannot see .exe, .py, etc. files.

### ISSUE THREAD

**Issue by seohyun1108** [files-community/files-uwp#696]
**Describe the bug**
I cannot see these files. I cannot do programming.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2 19613]
 - App version: [v0.7.8]

**Comment by yaichenbaum** [comment]
Have you given the app permissions to access the file system?

**Comment by seohyun1108** [comment]
How can I give the app permissions?

**Comment by yaichenbaum** [comment]
@seohyun1108 Go to the settings app on Windows 10 > Privacy > File System, make sure to toggle the option for Files UWP.

**Comment by duke7553** [comment]
@seohyun1108 Did this settings toggle fix your issue?

**Comment by YourDailyLlama** [comment]
I recently installed this app and i'm meeting the same problem. The thing is, in the settings page for File System, Files UWP is not there and yes, i have 'Allow apps to access the file system' toggle on.

**Comment by duke7553** [comment]
@YourDailyLlama @seohyun1108 Thanks for reporting this. Can you confirm on the latest update that the items in this folder which are missing are NOT shortcut files?

**Comment by duke7553** [comment]
Thanks again for your feedback. 

_Since we didn't hear from you on this topic for 7+ days, we'll assume everything is worked out and close this feedback item soon. If you had more feedback to provide, please re-open this and help the owners by describing the current status and any steps taken to troubleshoot this._
