### ISSUE TITLE
"Date Modified" Format

### ISSUE THREAD

**Issue by xPoppyx** [files-community/files-uwp#700]
I have seen that the files modified before 7 days, are shown in X seconds ago, X minutes ago, X hours ago and X days ago.

What if instead of showing as "**X hours ago**" the normal date is displayed? Like **04/25/20 18:35** or depending on how you configure the date format in the app
![fecha-formato](https://user-images.githubusercontent.com/61259627/80294549-fa450600-8737-11ea-9201-64daab8ee450.png)

**Comment by seohyun1108** [comment]
me too
