### ISSUE TITLE
Explain the datetime options

### ISSUE THREAD

**Issue by lampenlampen** [files-community/files-uwp#718]
We should explain what the differences between the datetime options are (Tooltip or link to wiki page, ...).

**Comment by xPoppyx** [comment]
![Anotación 2020-04-28 130147](https://user-images.githubusercontent.com/61259627/80516690-d3fab280-8951-11ea-837d-516185287897.png)

**Comment by generalguy41** [comment]
@xPoppyx I'd say the second one to keep consistent.

**Comment by yaichenbaum** [comment]
I suggest keeping the design how it is, we can add a simple information icon that displays a teaching tip when you hover or click on it.

**Comment by yaichenbaum** [comment]
This issue has been resolved and will roll out to users with the next update.
