### ISSUE TITLE
Create new file

### ISSUE THREAD

**Issue by lampenlampen** [files-community/files-uwp#719]
At the moment you can only create a folder, a text file and a bitmap file.

We should change the two file options for a `Create file`-option, where you can specify the file extension.

**Comment by lorisobi** [comment]
I made a small **concept** of the file creation dialogue.
![New File](https://user-images.githubusercontent.com/28399150/80914914-0f7cee80-8d4f-11ea-9cef-568677bb239a.jpg)
If the list gets too long you could maybe use a list view with grouped headers

**Comment by lampenlampen** [comment]
I really love it.

1. **Filename**:
I wonder if we can include a option to specify the filename somehow. So instead of a 2-step action (creating a default file, name it accordingly) it is a 1-step action (both in 1 dialog).   
What about adding a textbox at the top for the filename?

2. **Folder**:
Can we somehow integrate the folder option? If not, we would need to "new"-buttons (file, folder) or a 2. dialog before this one.

**Comment by lorisobi** [comment]
![NewFile2](https://user-images.githubusercontent.com/28399150/80916400-b3b76300-8d58-11ea-95e7-6ef832388453.jpg)

Either a textbox on the top or like this when you click (but I think first one would be more user friendly)

**Comment by lampenlampen** [comment]
1. I would exclude shortcuts for now.
2. With this approach we can simply treat "folder" as a filetype and put it into the list.

I once saw a control, that would suit, but i don't remember where, so i do my best to describe it.
It is a control , which is divided into two parts. The 1. (left) part is a simple TextBox for the filename and the 2. (right) part displays the file extension (not editable). So as a whole it displays the filename + extension. The file extension is controlled by the selection on the list.

**Comment by lorisobi** [comment]
so like this?
![NewFile3](https://user-images.githubusercontent.com/28399150/80917197-bbc5d180-8d5d-11ea-806c-47a84fb0a4ff.jpg)

**Comment by lampenlampen** [comment]
Yeah

1. How about deleting the space between the textbox and the file extension box?
2. I would delete the down arrow.
3. attach the "recent, all"-window beneath the "new file"-window.
4. move the create button the the bottom.

**Comment by yaichenbaum** [comment]
What about a simple menu that fetches the options from the registry?

**Comment by lorisobi** [comment]
too simple 😂

**Comment by lampenlampen** [comment]
i really would like to have an option to specify a custom filetypes.
With explorer i have to create a textdocument, so i can then rename it to a markdown file.

**Comment by lorisobi** [comment]
yeah you're right, thats annoying. but maybe just put it in as first/last dropdown option

**Comment by lampenlampen** [comment]
For me personally the custom entries in the explorers "new"-menu do not bring any value.

The only option is use are the "folder" and the "textdocument" options.

I create all other entries (office, zip, bitmap) through the corresponding apps.

**Comment by lampenlampen** [comment]
You should be able to specify a custom entry. A AutoSuggestBox, where you enter custom entries. Or there is a settings option or a json file, where you can specify custom entries for the dropdown.

**Comment by yaichenbaum** [comment]
Merging with #507.
