### ISSUE TITLE
List View fonts are too large

### ISSUE THREAD

**Issue by fauzie811** [files-community/files-uwp#737]
**Is your feature request related to a problem? Please describe.**
The fonts are a bit too large in List View mode. It looks out of place.

**Describe the solution you'd like**
Make it the same size as the sidebar.

**Additional context**
![Files UWP - Preview 5_3_2020 5_29_32 AM](https://user-images.githubusercontent.com/318095/80893738-40353780-8cff-11ea-8353-63d7329bbebf.png)

**Comment by yaichenbaum** [comment]
This is really a question about striking the right balance between touch and mouse friendly. I currently like the size of each how they are but this should definitely be a discussion to see if others feel the same way.

**Comment by xPoppyx** [comment]
mm I also think it should be a little bit smaller

**Comment by fauzie811** [comment]
> This is really a question about striking the right balance between touch and mouse friendly. I currently like the size of each how they are but this should definitely be a discussion to see if others feel the same way.

If you're talking about the list items' height, then I agree with you. It is good as it is.

But here, I'm talking about the text size only. Which has nothing to do with touch or mouse friendliness.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. A solution for it is currently being reviewed as a PR (pull request) to our active development branch. We'll let you know once it's merged.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
