### ISSUE TITLE
Add an option to hide the recent list on the home page

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#748]

**Comment by duke7553** [comment]
Hi @Jaiganeshkumaran .

We're planning to eventually improve the homepage layout. Is there anything you can think of that would add value to the app experience if put on the homepage? (i.e. what changes should we make to the recent items list to make it more useful for you?)

**Comment by yarikvv** [comment]
It would be great if there could be an option to switch between recent places and pinned places on the home page.

**Comment by yaichenbaum** [comment]
Merging with #366.
