### ISSUE TITLE
Font size 

### ISSUE THREAD

**Issue by xumepoc** [files-community/files-uwp#772]
Is it possible to reduce the font size in the explorer? I know it uses the same size as the Windows 10 settings, but for the explorer it is a bit bigger which reduced the information which is displayed on it. A custom size slider in the settings would be perfect:) 

P.S. I love the program. Best UWP out there!!!!

**Comment by yaichenbaum** [comment]
Is there a specific area that you would like to use a smaller font?

**Comment by xumepoc** [comment]
Well in general. The best option is for the user to be able to set the font size so that it can fit his needs. 
Here is a screen shot of the normal File Explorer in Windows 10 and the UWP. I am ware that the font size in UWP applications is a big bigger, but you can also see how much less of information you can get at the same time comparing the two
![Annotation 2020-05-25 101713](https://user-images.githubusercontent.com/46034979/82788708-a2eaa080-9e71-11ea-83bf-46fd32ee271f.jpg)

![Annotation 2020-05-25 102215](https://user-images.githubusercontent.com/46034979/82788726-abdb7200-9e71-11ea-97bf-eda6a54380c1.jpg)

Again it is not a big issue, I just think it will improve the user experience.

**Comment by xPoppyx** [comment]
I reduced the font size a bit, ready for PR

![FONTSIZE](https://user-images.githubusercontent.com/61259627/83440649-4b20dc00-a413-11ea-8697-5e21649b08c3.jpg)

**Comment by yaichenbaum** [comment]
I don't know if we want to reduce the font size, perhaps we will add customization options but for now we will be keeping it how it is.

**Comment by xumepoc** [comment]
No problem for me :). I am closing the comment for now ;)
