### ISSUE TITLE
App crashes when accessing android device's drive

### ISSUE THREAD

**Issue by colinkiama** [files-community/files-uwp#779]
**Describe the bug**
App crashes whenever I try to access the drive of my android phone

**To Reproduce**
1. Plug-in phone
2. Click on phone under drive section
3. App crashes

**Expected behavior**
Root folder of the phone should be displayed

**Desktop**
 - OS Version: [e.g. Windows 10 1909 18363.778]
 - App version: [v0.8.0.0]

**Additional context**
App even crashes even when trying to copy items from my phone to the my PC's local drive (C:).

**Comment by duke7553** [comment]
Thank you for reporting this. I found out that this is a larger issue than I originally thought, as we have no way of enumerating the storage items from a phone's internal storage unless it has a path returned on the system. (Which it probably doesn't)

Hopefully, I can work with someone more talented than myself in this area soon.

**Comment by duke7553** [comment]
My initial thought is that we need to build a new way to access devices like this without being so dependent on their root path because those do not exist.
