### ISSUE TITLE
Add Recycle Bin to sidebar

### ISSUE THREAD

**Issue by jamiehoss** [files-community/files-uwp#785]
I was wondering if it might be possible to put the Recycle Bin in the left sidebar? That would be a really useful feature, Windows File Explorer gives an option like this by allowing the Recycle Bin to be pinned in Quick Access.

**Comment by yaichenbaum** [comment]
Thank you for opening this issue. Files UWP does not support recycle bin at the moment. If we add support for it in the future, there will definitely be a way to pin it to the sidebar.

**Comment by diligamer** [comment]
Maybe something like this 
![image](https://user-images.githubusercontent.com/32780515/82090922-22a09e80-96ff-11ea-9c5b-9bb3460451cd.png)

**Comment by yaichenbaum** [comment]
@jamiehoss The latest version (v0.9.1) added support for recycle bin, make sure to head to the experimental page settings in settings to turn on this feature.

**Comment by jamiehoss** [comment]
@yair100 trying it now and it works great, thanks a lot for implementing it! Keep up the great work, love the app.
