### ISSUE TITLE
Support drag to move to another tab

### ISSUE THREAD

**Issue by jayasio** [files-community/files-uwp#828]
**Is your feature request related to a problem? Please describe.**
One of the main uses of multiple tabs for me would be to move a file/set of files from one folder to another, in this case, tabs. 

**Describe the solution you'd like**
When I drag selected files/folders to another tab, the tab should automatically switch to the one the cursor is on top of. I should then be able to put it in, which cuts the files from the previous location and pastes into the new location. Perhaps alt + drag could be used to copy instead. (or if there's a standard implementation in the default explorer, that could be used)

**Additional context**
:) Great app!

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
