### ISSUE TITLE
I'd like to drag storage items into/outside the app

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [files-community/files-uwp#829]
**Describe the bug**
Drag and drop only works for moving files and not for uploading files to websites like OneDrive.

**Expected behavior**
File should be uploaded to the website.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro Insider Preview Build 19624.1000
 - App version: v0.8.2.0

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran By uploading to websites, do you mean that you want to be able to drag a file out of Files UWP into an app or website to load it?

**Comment by Jaiganeshkumaran** [comment]
> @Jaiganeshkumaran By uploading to websites, do you mean that you want to be able to drag a file out of Files UWP into an app or website to load it?

Yes. I want to be able to drag any file out of Files UWP to load it in a external app or website just like to built-in File Explorer.

**Comment by mister-hunter** [comment]
> > @Jaiganeshkumaran By uploading to websites, do you mean that you want to be able to drag a file out of Files UWP into an app or website to load it?
> 
> Yes. I want to be able to drag any file out of Files UWP to load it in a external app or website just like to built-in File Explorer.

Preferably also the ability to drop files and folders into Files UWP

**Comment by Alpakat2** [comment]
Yes! I am able to drag files out of Files UWP, but not in Files UWP. Would be nice to drag files into Files UWP, for ex. from the Desktop.
