### ISSUE TITLE
Search gets cropped in compact size

### ISSUE THREAD

**Issue by lorisobi** [files-community/files-uwp#830]
Searchbar in the Settings gets cropped in compact size (4k Screen)
![Anmerkung 2020-05-24 123018](https://user-images.githubusercontent.com/28399150/82751835-58f2b380-9dba-11ea-9c62-f4de28787bc3.jpg)

**Comment by R3voA3** [comment]
Can confirm, same issue on 1920x1080. The marging between the menu left of the search box and the box itself is too large, or minium window size should be increase slightly.

**Comment by lorisobi** [comment]
or it should minimize to a button , which expands, when you click it

**Comment by Jaiganeshkumaran** [comment]
> or it should minimize to a button , which expands, when you click it

The search box doesn't even work yet so that will be done after implementing search.

**Comment by yaichenbaum** [comment]
This issue has been fixed with v0.11.
