### ISSUE TITLE
Default right mouse contextual menu not available while file is selected.

### ISSUE THREAD

**Issue by xumepoc** [files-community/files-uwp#835]
**Describe the bug**
In Files UWP the default right mouse contextual menu not available while file is selected. This is how it is working in File Explorer, but in File Explorer you can "deselect" a file by clicking on an empty space around the file. This is very useful when you want to "paste" a copied file but you have clicked on a file by accident. 

**To Reproduce**
Copy a file.
Go to Files UWP
Click on a file
Try to open the default right mouse contextual menu in order to "Paste" the copied file. The contextual menu for clicked file will be opened every time.

**Expected behavior**
There should be a way to "deselect" a file in Files UWP in order to open the general right mouse contextual menu.
Also the default right mouse contextual menu should be opened when you right click outside of a file in Files UWP.

**Screenshots**
![Annotation 2020-05-25 105145](https://user-images.githubusercontent.com/46034979/82791538-9c125c80-9e76-11ea-8d90-89e794c55e01.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909 18363.567
 - App version: v0.8.2.0

**Comment by yaichenbaum** [comment]
@xumepoc Thanks for reporting this issue, it should be resolved with next v0.9. Please reopen this issue if you can reproduce this when you get the update.
