### ISSUE TITLE
Slightly darker text of file properties in list view

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#844]
My proposal is that the texts of the file properties in list view are a little darker, like in file explorer

**current:**
![Anotación 2020-05-31 153848](https://user-images.githubusercontent.com/61259627/83361247-557ca080-a355-11ea-9d9e-f2f3e9970c5f.png)

**proposal:**
![82106797-51b01380-96f1-11ea-842c-9876fc331d51](https://user-images.githubusercontent.com/61259627/83361271-8d83e380-a355-11ea-8c15-b177481e7988.jpg)

**Comment by yaichenbaum** [comment]
@xPoppyx Can you please fill out the issue template explaining the issue or proposal?

**Comment by xPoppyx** [comment]
updated

**Comment by xPoppyx** [comment]
@yaichenbaum I can do a PR of this if you want, now they are Gray and the headers are still Light Gray
![before](https://user-images.githubusercontent.com/61259627/83423238-b0b39f00-a3f8-11ea-999f-0bf88a1b6ba2.jpg)
![AFTER](https://user-images.githubusercontent.com/61259627/83423248-b4472600-a3f8-11ea-85b8-9f88606fa870.jpg)

**Comment by xPoppyx** [comment]
The problem is that when selecting an item, depending on the accent color, it does not look good.
![Captura de pantalla (224)](https://user-images.githubusercontent.com/61259627/83441748-08f89a00-a415-11ea-83c5-ec2cc29b05ce.png)

**Comment by yaichenbaum** [comment]
I think it's best to hold off given the accessibility issues this would cause.

**Comment by XPoppyX** [comment]
merging with #1170
