### ISSUE TITLE
Need .Msixbundle in Releases

### ISSUE THREAD

**Issue by Reset12138** [files-community/files-uwp#847]
If the .Msixbundle is given in every Releases, I can add it in [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by yaichenbaum** [comment]
I will update releases with the msixbundle shortly after they go live on the Microsoft Store.

**Comment by Reset12138** [comment]
> I will update releases with the msixbundle shortly after they go live on the Microsoft Store.

ok thank you

**Comment by yaichenbaum** [comment]
@Reset12138 The msix for v0.9.0 is now uploaded for the v0.9.0 release.

**Comment by Reset12138** [comment]
got it. Thanks for your reminding.



-------- 原始信息 --------
发件人： Yair Aichenbaum <notifications@github.com>
日期: 2020/5/27 02:34 (GMT+08:00)
收件人： files-community/files-uwp <files-uwp@noreply.github.com>
抄送： 谭源 <kentertan12138@Outlook.com>, Mention <mention@noreply.github.com>
主题： Re: [files-community/files-uwp] Need .Msixbundle in Releases (#847)


@Reset12138<https://github.com/Reset12138> The msix for v0.9.0 is now uploaded for the v0.9.0 release.

―
