### ISSUE TITLE
cvc 1

### ISSUE THREAD

**Issue by baileyaish123** [files-community/files-uwp#848]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by baileyaish123** [comment]
Duplicate of #

**Comment by baileyaish123** [comment]
hi

**Comment by Tsubajashi** [comment]
Your OS Version, and version of the App is very old. can you try updating them, and check if the issue persists?

**Comment by yaichenbaum** [comment]
Thanks for your feedback. We're having trouble understanding what you're requesting and need additional information to investigate this item. Please re-open when you've filled out the issue template to the best of your ability.
