### ISSUE TITLE
Can't build from visual studio

### ISSUE THREAD

**Issue by nodew** [files-community/files-uwp#852]
Error message
```
Cannot find a Resource with the Name/Key ButtonRevealBackground [Line: 10 Position: 37]
```
System info
```
System:  Windows 10 enterprise build 2004
Visual studio: Microsoft Visual Studio Enterprise 2019 Version 16.6.0
```

**Comment by duke7553** [comment]
@nodew Can you please provide more information about how you've tried to solve the problem. (e.g. cleaning and rebuilding)

**Comment by yaichenbaum** [comment]
Closing this issue, please reopen if you have more information to help us debug the issue with building the application.
