### ISSUE TITLE
Occasional crash when switching viewmode

### ISSUE THREAD

**Issue by SOI7** [files-community/files-uwp#857]
**Describe the bug**
Sometimes, when I switch viewmode (doesn't matter which one), the app crashes

**To Reproduce**
Simply switch viewmode consecutively 

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909
 - App version: v0.9.0

**Additional context**
It may be related to loading thumbnails after switching viewmode

**Comment by xPoppyx** [comment]
I was testing and it only happens between the grid views

**Comment by RomanKornev** [comment]
Can confirm it crashes

**Comment by AnuthaDev** [comment]
@duke7553 This might be of interest: https://devblogs.microsoft.com/oldnewthing/20140120-00/?p=2043

**Comment by yaichenbaum** [comment]
@SOI7 This issue may be fixed with the v0.10.2 update.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our stable branch and should be available from the Microsoft Store. Please subscribe to our releases to be notified when fixes like this are available.
