### ISSUE TITLE
Flickering UI refresh every second

### ISSUE THREAD

**Issue by RomanKornev** [files-community/files-uwp#871]
**Describe the bug**
App flickers every second in some folders

**To Reproduce**
1. Go to app's log directory
2. UI flashes every second

**Expected behavior**
UI should not flash every second

**Screenshots**
![2020-05-27 22 59 08](https://user-images.githubusercontent.com/5807561/83066599-f9243300-a06d-11ea-8b6a-925f9878b909.gif)

**Desktop (please complete the following information):**
- OS: Windows 10 x64 1909 18363.836
- App version: v0.9.0 Beta

**Comment by RomanKornev** [comment]
Crashed right after recording this

**Comment by yaichenbaum** [comment]
This is do to a task that is watching for changes to files, we will work on improving this in the future, but this is necessary to prevent crashes when renaming files.

**Comment by RomanKornev** [comment]
It only appears that way on some folders, not sure why

**Comment by Jaiganeshkumaran** [comment]
> It only appears that way on some folders, not sure why
Because some other app keeps modifying the folder.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
