### ISSUE TITLE
Port it to macOS via Uno Platform

### ISSUE THREAD

**Issue by lextm** [files-community/files-uwp#874]
**Is your feature request related to a problem? Please describe.**
Finder is not a very convenient file explorer to use, so there are tons of attempts to write a good file explorer for Mac. Files UWP can be one of them.

**Describe the solution you'd like**
Uno Platform enables UWP apps to port to several platforms, including macOS, so Files UWP can run on macOS if converting to a Uno app.

**Addition information**
I already forked this project and started to investigate the feasibility. So far many parts can be ported over, while some parts are still missing on Uno (like https://github.com/unoplatform/uno/issues/3256).

It is going to be a long term effort to finish the port.

**Comment by yaichenbaum** [comment]
@lextm Make sure to keep us updated on the progress, we have no plans on our end to port it but we will be happy to link to your fork when it's ready. Please comment or open another issue when you get it working on macOS 🙂

**Comment by lextm** [comment]
@yair100 Sure. It will remain in my own fork for a while, as a few Uno bugs have already been identified and investigated on their side. As soon as I have something working on a Mac, will report back and possible merge some changes here.
