### ISSUE TITLE
Behavior Changes | Crash | 

### ISSUE THREAD

**Issue by Battler624** [files-community/files-uwp#875]
First off I am amazed by the work you've put into this, soon enough I might switch to this permanently but before that a few things must be done. This is compared to regular files explorer that comes with windows

There is a chance to crash every time I create a new folder, it seems the bug is related to the refresh that happens the moment it is created (it either refreshes and doesn't crash or crashes, haven't seen it refresh and crash).

Regarding the click, wait a second, click for renaming, I noticed that if I click away and then click on the file/folder name again I still the ability to change the name but this doesn't happen if i click another file/folder.

again, regarding the (re)naming behavior, I noticed that it lacks the dots for long file names and there is a minor annoyance when changing files names that happens if the filename is too large the box doesn't scale to fit them but instead goes to the very end (I don't like this behavior). 

There is a bug with deleting folder names, they save with no name but if you enter them it reverts to the old name (it shouldn't save with no name).

Finally, allow delete (keyboard button) to delete with prompt (sending to bin) and give us the shift+del with a prompt (for permanently deleting)

I made 2 videos quickly using to highlight everything in this post because I'm bad at explaining but hopefully you got the intent.

https://youtu.be/UeVFRYhYxv8
In this video you can see the new file/folder crash bug, the renaming behavior (that I believe to be bad)

https://youtu.be/zAdCTIcjzTI
In this video you see the 3 dots (column not long enough for full file name), renaming makes the column bigger (for easier file renaming, and only for that file), the lack of a name bug and the behavior differences between files and FilesUWP in regards to the above and file deletion.

One minor nitpick, can we rename the column to the left of the name that only contains icons? (merge it with the name column)

Quick edit: I know this is all pre-release stuff, i'm just pointing the things out, if i'm helpful thats great if not well theres that, so just ignore.

**Comment by duke7553** [comment]
Thank you for taking the time to open this feedback item. In order to best address this in a transparent way, we usually expect reporters to open each feedback topic (e.g. feature request, bug, question, discussion item) as its own ticket. Please review each topic suggested here, and add your own take on an already open issue, or open a new one. 

Closing this now.
