### ISSUE TITLE
Enter key does not work to confirm delete action

### ISSUE THREAD

**Issue by generalguy41** [files-community/files-uwp#877]
**Describe the bug**
To delete a file using the Delete keyboard shortcut displays the popup to delete the file, but pressing enter to confirm just changes the focus to the directory.

**To Reproduce**
1. Go to any directory.
2. Click on a file.
3. Press 'Delete' or 'Shift+Delete' to delete the file.
4. Press one of:
   1. 'Enter' to confirm. See that focus has shifted to the contents of the directory.
   2. Arrow keys. See that you cannot change focus from the 'Delete' button to something like the 'Cancel' button or the 'Permanently delete' checkbox. This does work with 'Tab', however.
   3. 'Space' button. Same as 'Enter'.

**Expected behavior**
Pressing any of the above keys will apply the expected action.

**Desktop:**
 - OS Version: [e.g. Windows 10 2004 19631.1]
 - App version: [v0.9.0.0]

**Comment by yaichenbaum** [comment]
This issue should be fixed with #878.
