### ISSUE TITLE
Display file Directory instead of full path in properties dialog

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#881]
**Before:**
![Captura de pantalla (221)](https://user-images.githubusercontent.com/61259627/83331981-c4c79700-a266-11ea-811f-e2aad0404151.png)

**After:**
![Captura de pantalla (220)](https://user-images.githubusercontent.com/61259627/83331984-c5f8c400-a266-11ea-8fe9-d88b87ae6515.png)

**Comment by duke7553** [comment]
@xPoppyx I'm kind of divided on this because the full path can be useful for some users.

**Comment by yaichenbaum** [comment]
We can technically provide a feature flag for this, I am in favor of just showing the path since the file name is already displayed but this should be left up for discussion.

**Comment by Phil4102** [comment]
What about a "show full path" button when hovering over it?

**Comment by tsvietOK** [comment]
We could add a button or context menu "Copy path"

**Comment by Cyberdroid1** [comment]
We can create an option in settings whether to show complete path or the directory of the file. That would also be useful

**Comment by yaichenbaum** [comment]
There is a difference with the file name and the path, mainly that the path is made up of folders while the file is a file name. In this case we should just keep them separate to create a division between the two.

**Comment by yaichenbaum** [comment]
Changes to resolve this issue will roll out with the next update.
