### ISSUE TITLE
Translation is not consistent

### ISSUE THREAD

**Issue by Joni135** [files-community/files-uwp#897]
If I use the application in german, the translation is not consistent.

**Steps to reproduce the behavior:**
1. Install app in german
2. Parts of the app are not translated

**Missing translations:**
If you look at the "Geändert" section in a folder, you can see that if the file was edited just a couple hours ago, the text says for example 23 hours ago. What should be standing there is: vor 23 Stunden.
Also missing is the translation of "the new tab" button in the home-menu.

![grafik](https://user-images.githubusercontent.com/62477623/83538742-7fb99400-a4f6-11ea-8df6-16d442297d68.png)
The dates are fine, but the _x_ minutes ago is not translated.

![grafik](https://user-images.githubusercontent.com/62477623/83538927-b8596d80-a4f6-11ea-98c6-c4c91fe8b707.png)
The "new tab" button is not translated.

OS: Windows 10 Home 1909 [Build 18363.836]
App version: 0.9.1.0

**Comment by yaichenbaum** [comment]
@Joni135 Whoever did the original translation for German hasn't updated the translations for some time, there is nothing that we can do about it ourselves but if you know German, feel free to translate the app yourself and open a pull request 🙂
