### ISSUE TITLE
App doesn't show or crashes when moving an object to Recycle Bin

### ISSUE THREAD

**Issue by Cyberdroid1** [files-community/files-uwp#899]
Today, I found the feature of Recycle Bin in the app and then went on to use it. With the Files app open on the side of my desktop, I dropped one of my shortcuts to the bin and when i checked into the recycle bin of the app, there was nothing but the file explorer was showing the deleted shortcut. Next, I cut a folder from the desktop through the app and then pasted it in the recycle bin of the app, the app got stuck for a few mins with high disk usage but then crashed unexpectedly 

I understand that it is an experimental feature. Thus, I didn't give a bad rating. I expect the problem to be fixed as soon as possible.

(The Microsoft Store Version app)
 - OS Version: [Windows 10 2004]
 - App version: [v0.9.1.0]

**Comment by yaichenbaum** [comment]
@Cyberdroid1 I am happy you found the experimental feature we just added, this is still a work in progress and your feedback will help us improve it further.
cc @gave92

**Comment by gave92** [comment]
@Cyberdroid1 thanks for reporting this.
I can confirm that the shortcuts do not appear, I opened an issue regarding this [here](https://github.com/dahall/Vanara/issues/129).
Regarding the crash could you post here the contents of the "debug.txt" file (and possibly "debug_fulltrust.txt") that you find at `%LocalAppData%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`?

**Comment by Cyberdroid1** [comment]
[debug.txt](https://github.com/files-community/files-uwp/files/4727474/debug.txt)

The link for the file is given above. Please inform me if there is any sensitive info. The error happened yesterday only (twice). I did not find the debug_fulltrust.txt in the mentioned folder. Can you please tell where is it located?

**Comment by gave92** [comment]
@Cyberdroid1 debug.txt does not contains sensitive infos.
`debug_fulltrust.txt` may not be generated depending on the crash (if there is it's in the same place as debug.txt. I'll look into this.

**Comment by Cyberdroid1** [comment]
Ok, thanks

**Comment by Cyberdroid1** [comment]
Hello, today I tried to use the Recycle bin again. I right clicked on a file and clicked on move to Bin. The file disappeared from the path. Then I went on to check the recycle bin of the app but it wasn't there. Then I opened the recycle bin of file explorer but there also the file was missing. But soon the app crashed.

**Comment by gave92** [comment]
Thanks for the feedback. Do you mean that:
- you right clicked on a file in the app
- you selected "Delete" from the context menu
- you accepted the delete dialog without checking the "Permanently delete" option?
If the app crashed please post the `debug.txt` again.

**Comment by Cyberdroid1** [comment]
i had recently tried to tweak the Terminal Applications option and had opened the terminal.json file and added the id for fluent terminal. But then the app started to crash at startup. then i set the file back to its original state but still it failed to start. Thus i reinstalled the app. 

Now i tried to right-click a file in the files app, and click on delete. The dialog box to whether permanently uninstall came but i left it unchecked and clicked delete. Then a black dialog box came up but it remained empty and nothing came up. I closed it and tried again. Still the same thing.
 
Anyways, i am posting the debug.txt file after the reinstall.
[debug.txt](https://github.com/files-community/files-uwp/files/4736154/debug.txt)

**Comment by Cyberdroid1** [comment]
Also, the file never got deleted. The Recycle bin feature is failing badly. Though the empty recycle bin feature worked perfectly as intended.

**Comment by Cyberdroid1** [comment]
I also noted one thing. The recycle bin feature worked for empty folders but a box appears when trying to delete a filled folder, a strange black dialog box appears.

**Comment by Cyberdroid1** [comment]
![image](https://user-images.githubusercontent.com/51435948/83878040-22714d00-a759-11ea-8cd7-69d89a6547cf.png)

Here is the image of the strange black dialog box.
Hope it helps...

**Comment by gave92** [comment]
It looks to me that the issue is not with the recyclebin feature itself but rather with simply deleting folders.

Could you try to reinstall the app again and *not* enable the recycle bin feature? Does the black box still appear when you delete a filled folder? Thanks!

@yair100 What do you think?

**Comment by Cyberdroid1** [comment]
Hello, I tried what you said. But rhe black box still appears. Can you please share what the black box is meant to do? I am a bit curious 😉

**Comment by yaichenbaum** [comment]
This might have something to do with Files UWP not supporting file shortcuts.

**Comment by Cyberdroid1** [comment]
Wow, a small bug led to such a big conclusion. Maybe that's why the shortcuts on my desktop don't appear here in the Desktop tab of the app.

So the app doesn't support showing the shortcut of the deleted file? Because the files in the recycle bin of file explorer do appear in the recycle bin of the app.
