### ISSUE TITLE
Open with ...

### ISSUE THREAD

**Issue by mister-hunter** [files-community/files-uwp#922]
**Is your feature request related to a problem? Please describe.**
As a junior developer in college, I need need to open folders with Visual Studio or Visual Studio Code every day. I would like to see the 'open with' feature that is already present in the normal file explorer.

**Describe the solution you'd like**
I would like it when you right-click (or your non-primary mouse button) on a folder or file, there is an extra option 'open with'. A small popup will appear with the programs installed and supported for said folder or file. Either a list with the programs or the icons of the programs would work.

**Describe alternatives you've considered**
There are two ways around this. Either use the 'open in terminal' and use that to open said file or folder with the program you want. Or use the normal file explorer, but if I were to do that, why would I be here 🙂

**Additional context**
Concept art:

![right-click](https://user-images.githubusercontent.com/49814847/83881971-bd5e2d00-a741-11ea-8530-48b187476573.png)

![right-click-hover](https://user-images.githubusercontent.com/49814847/83882741-da473000-a742-11ea-955b-b7dcd825702b.png)

![right-click-click](https://user-images.githubusercontent.com/49814847/83884476-3743e580-a745-11ea-901f-a7a5601dfdc3.png)

**Comment by Jaiganeshkumaran** [comment]
This feature will be available after merging #699.

**Comment by mister-hunter** [comment]
Grand!
