### ISSUE TITLE
Refresh after renaming

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#924]
**Grid view and Tiles view:** You need to manually refresh to see the change after renaming.

**List view:** when you rename an item you can see the new name immediately without manually refreshing, but you cannot interact with the item, so you need to refresh anyway

**Comment by tsvietOK** [comment]
@xPoppyx Can you confirm this bug still exists?

**Comment by xPoppyx** [comment]
tested with the most recent changes:

still the same
![RENAME](https://user-images.githubusercontent.com/61259627/83979401-0b0e9d00-a8dc-11ea-882c-742b219d9f60.gif)

**Comment by tsvietOK** [comment]
![Rename](https://user-images.githubusercontent.com/20501502/83979564-fbad4500-a917-11ea-82b2-1d45eecebd4a.gif)

**Comment by xPoppyx** [comment]
What exactly did you test?

**Comment by tsvietOK** [comment]
Renaming file

**Comment by xPoppyx** [comment]
I meant if you tested the same thing manually refreshing or an added auto-refresh

**Comment by tsvietOK** [comment]
I am just trying to reproduce your bug on current master brunch without any changes. For me it is working fine without manual refresh.

**Comment by xPoppyx** [comment]
and in the microsoft store version (v0.9.1)?

**Comment by tsvietOK** [comment]
Hmm, your right, store version has this bug.

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
