### ISSUE TITLE
Need documentation on contributing

### ISSUE THREAD

**Issue by samtholiya** [files-community/files-uwp#925]
I was trying to build the repo with visual studio 2019. 
Steps I followed:
1. Forked the repo
2. Click on Clone download and choose open in visual studio
3. Select File (Universal Windows)
4. No run button found.. on the toolbar (Why there is no run button here)

**Comment by Jaiganeshkumaran** [comment]
If you don't see the run button try resetting the toolbar in Visual Studio.

**Comment by lampenlampen** [comment]
You need to select the `Files.Package`-project.

![files_run](https://user-images.githubusercontent.com/26199386/83943403-17bbc400-a7fc-11ea-9577-e55aee220dc4.png)

If you still don't see the `Local Machine`-button, you can click `Debug` on the menubar and then `Start Debugging`.

**Comment by samtholiya** [comment]
Thanks this solved my issue
