### ISSUE TITLE
Right-click -> rename opens file

### ISSUE THREAD

**Issue by mister-hunter** [files-community/files-uwp#927]
**Describe the bug**
Right-clicking to rename a file opens the file

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any folder with files
2. Right-click
3. Click rename
4. See the window for the file being opened

**Expected behaviour**
Allow renaming the file

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS Version: Win 10 Version 10.0.18363 Build 18363
 - App version: [v0.9.1.0]

**Additional context**
n/a

**Comment by xPoppyx** [comment]
in list view and "double tap to rename files" disabled? if so, that's the problem, see in: #651

**Comment by mister-hunter** [comment]
Ah, apologies, my mistake

**Comment by yaichenbaum** [comment]
This issue should be resolved with #2142.
