### ISSUE TITLE
Properties dialog: black background in transparent images

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#929]
in the properties dialog, images with a transparent background appear with a black background, looks terrible depending on the image
![Anotación 2020-06-06 184752](https://user-images.githubusercontent.com/61259627/83955928-4c447580-a826-11ea-9bff-1453fa1f64a3.png)
![Anotación 2020-06-06 184813](https://user-images.githubusercontent.com/61259627/83955929-4d75a280-a826-11ea-8a42-d1dbefd18083.png)

**Comment by Darhagonable** [comment]
Seems like they were set to ResizeThumbnail :P

**Comment by duke7553** [comment]
Thank you for creating this feedback item. A solution for it is currently being reviewed as a PR (pull request) to our active development branch. We'll let you know once it's merged.
