### ISSUE TITLE
The appication triggers UAC on opening any file

### ISSUE THREAD

**Issue by FibYar** [files-community/files-uwp#934]
**Describe the bug**
When I try to open any file (even text ones) then Windows (UAC) asks me to allow this action.

**To Reproduce**
1. Create any file (for example E:\temp\test.txt) in classic Windows Explorer or "Files UWP".
2. Try to open this file in "Files UWP" with doubleclick.
3. You see that UAC triggers.

**Expected behavior**
I expect that UAC do not triggers on any files that do not require admin permissions (such as some exes) and I would expect that file just opens with default program.

**Screenshots**
![IMG_20200607_183719](https://user-images.githubusercontent.com/12131583/83973374-ad378080-a8ee-11ea-9fca-64ae249bd9ae.jpg)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1909 18363.836]
 - App version: [v0.9.1]

**Additional context**
If I choose "No" in UAC dialog, then file opens just right. If I choose "Yes", then the file do not opens.

**Comment by xPoppyx** [comment]
I guess you have "takeown" added in the registry

**Comment by FibYar** [comment]
> 
> 
> I guess you have "takeown" added in the registry
Could you please explain what exactly does that means? I have a lot of "takeown" in registry. But I did not add them myself. Is it bad?

**Comment by xPoppyx** [comment]
Well, when I added takeown, that dialog also appeared when I wanted to open any file, when I removed it, it no longer appeared. 

Delete the **TakeOwnership** folder from:: 
HKEY_CLASSES_ROOT\*\shell\   
HKEY_CLASSES_ROOT\Directory\shell\

Delete the **runas** folder from:: 
HKEY_CLASSES_ROOT\*\shell\
HKEY_CLASSES_ROOT\Drive\shell\

**Comment by FibYar** [comment]
> 
> Delete the **TakeOwnership** folder from::
> HKEY_CLASSES_ROOT*\shell\
> HKEY_CLASSES_ROOT\Directory\shell\
> 
> Delete the **runas** folder from::
> HKEY_CLASSES_ROOT*\shell
> HKEY_CLASSES_ROOT\Drive\shell\

Yes, it worked. Thanks for the help!

**Comment by MobiusBeta** [comment]
> Well, when I added takeown, that dialog also appeared when I wanted to open any file, when I removed it, it no longer appeared.
> 
> Delete the **TakeOwnership** folder from::
> HKEY_CLASSES_ROOT*\shell\
> HKEY_CLASSES_ROOT\Directory\shell\
> 
> Delete the **runas** folder from::
> HKEY_CLASSES_ROOT*\shell
> HKEY_CLASSES_ROOT\Drive\shell\

Thanks a lot!!
