### ISSUE TITLE
Russian perssistent language

### ISSUE THREAD

**Issue by Suburbanno** [files-community/files-uwp#935]
I'm having problems with the language, I can not change the language to English, I have already reinstalled the application and it persists in Russian, where is the option to change the language?

**Screenshots**
![image](https://user-images.githubusercontent.com/13632826/83975323-b06c4580-a8c9-11ea-881c-2799ada2108b.png)

 - OS Version: [Windows 10 2004]
 - App version: [v0.9.1]

**Comment by yaichenbaum** [comment]
At the moment the app defaults to the system language, as providing an option to override that comes with it's own set of difficulties.

**Comment by Suburbanno** [comment]
Russian was as second option of applications for language in Windows, probably that was the reason, fixed!
