### ISSUE TITLE
Can not run .bat files

### ISSUE THREAD

**Issue by xumepoc** [files-community/files-uwp#948]
**Describe the bug**
In Files UWP it is not possible to run .bat files. When you double click or use the contextual menu "Open", nothing happens.

**To Reproduce**
1. Create a .bat file
2. Try to run it from inside Files UWP

**Expected behavior**
The .bat file should be executed.

**Desktop (please complete the following information):**
 - OS Version: Windows 1909 18363.836
 - App version: [v0.9.1.0]

**Comment by Jaiganeshkumaran** [comment]
It does work for me. Could you install v0.9.2 and try again?

**Comment by xumepoc** [comment]
I am having the same experience on v 0.9.2 For some .bat files it does run but for bat file which starts .exe file it seems it doesn't work. 

![mAAecbUFqd](https://user-images.githubusercontent.com/46034979/84391909-45d94380-ac02-11ea-86fe-9c5454e4c386.gif)

**Comment by Jaiganeshkumaran** [comment]
Some of your .bat files may need admin privileges. The latest version has added the option to run as administrator.

**Comment by xumepoc** [comment]
That doesn't seems to be the issues, because even if I run them with Admin privileges' they are not executed. Also using Windows Explorer they are run without Admin privileges' anyway.

**Comment by xumepoc** [comment]
This seems to be fixed now :) My batch files are executing. Thank you!!!
