### ISSUE TITLE
Allow to hide default library folders in sidebar

### ISSUE THREAD

**Issue by TailyFair** [files-community/files-uwp#949]
**Is your feature request related to a problem? Please describe.**
I never use Pictures, Videos and Music library folders and they add clutter in sidebar.

**Describe the solution you'd like**
Give option to choose which default library folders would appear in sidebar.
Maybe additional settings page with toggles to which library folder would be visible in side bar.
Or maybe even add option to choose custom path to these folders ?

**Comment by yaichenbaum** [comment]
@TailyFair Thank you for your feedback, I am working on it and if all goes well, it will be available with the next update.

**Comment by yaichenbaum** [comment]
This has been addressed with #951.
