### ISSUE TITLE
update re-pinned library icons without reopening the app

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#953]
when you re-pin any library folder, it is shown with a folder icon, and you must reopen the app to see the icon it should have.

when you re-pin:
![Anotación 2020-06-08 232427](https://user-images.githubusercontent.com/61259627/84102727-404fe380-a9df-11ea-8376-ee8dfe2609c2.png)

after reopening the app:
![Anotación 2020-06-08 232445](https://user-images.githubusercontent.com/61259627/84102733-40e87a00-a9df-11ea-828a-062972757adf.png)

**Comment by yaichenbaum** [comment]
@Richard-HM Thank you so much for testing this feature, I am already working on a fix and it should be ready soon.

**Comment by yaichenbaum** [comment]
This has been implemented, thank you for finding this issue.
