### ISSUE TITLE
Have a choice window when pasting and already existing file

### ISSUE THREAD

**Issue by xumepoc** [files-community/files-uwp#956]
Hi apologies if this is already requested.

When you try to paste a file that is already in the folder, instead of asking the user whether to overwrite the existing file or to keep them both (adding the new file with ***-Copy) the Files UWP does the latter automatically. That makes it quite time consuming to overwrite the existing file with the new: you have to delete the old file, wait for the refresh, find the new file and rename it.

In case a file already exists in the folder, on paste there should be a choice window with the options:
- Replace existing file
- Skip the file
- Keep both
- Compare files (optional)

**Comment by yaichenbaum** [comment]
Thank you for your feedback, an option for resolving conflicts when transferring files is planned as part of #114. Make sure to add your feedback to #114 so we can keep it in mind when developing the feature.
