### ISSUE TITLE
Add shortcuts page inside settings

### ISSUE THREAD

**Issue by TailyFair** [files-community/files-uwp#957]
**Is your feature request related to a problem? Please describe.**
There is no way inside app to know what shortcuts are available

**Describe the solution you'd like**
Shortcuts page inside settings with list of available shortcuts

**Describe alternatives you've considered**
Show shortcut in tool-tip when hovering on button.

**Comment by Jaiganeshkumaran** [comment]
What do you mean by shortcuts?

**Comment by XPoppyX** [comment]
@Jaiganeshkumaran  Keyboard shortcuts

**Comment by Jaiganeshkumaran** [comment]
For items in the right click context menu, they can be shown right next to the label like what some apps do.

**Comment by XPoppyX** [comment]
> Show shortcut in tool-tip when hovering on button.

@TailyFair I Added keyboard shortcuts to the tooltip of buttons in the navigation bar and new tab button: #964

**Comment by TailyFair** [comment]
> 
> 
> > Show shortcut in tool-tip when hovering on button.
> 
> 
> 
> @TailyFair I Added keyboard shortcuts to the tooltip of buttons in the navigation bar and new tab button: #964 
> 
> 

This is great ! Did not expected this to be addressed this quickly!

**Comment by yaichenbaum** [comment]
This issue should be resolved with #964.
