### ISSUE TITLE
Startup options require multiple clicks to change

### ISSUE THREAD

**Issue by SOI7** [files-community/files-uwp#958]
I have to click multiple times on the Startup options to change them

![test2](https://user-images.githubusercontent.com/50930970/84135586-75dde680-aa4a-11ea-93b0-cc7509c9eceb.gif)

App Version: 0.9.2
OS version: Windows 10 2004

**Comment by TailyFair** [comment]
Experiencing same issue. Also app eventually crashes.

App version: 0.9.2
OS version: Windows 10 1909

**Comment by Richard-HM** [comment]
fixed: #932
