### ISSUE TITLE
Add ctrl + c, ctrl + x, ctrl + v shortcuts for copy and pasting

### ISSUE THREAD

**Issue by jakehandwork** [files-community/files-uwp#961]
I would like to copy and paste files throughout the app. Even better if I can copy them from somewhere else and paste them to the app (from desktop to app) and vice-versa.

Ctrl +c, ctrl + v, and ctrl + x should all work as they do in other file apps and everywhere else. Instead of needing to right click to access that menu.

Let me know if this is already a thing and I'm just dumb.

**Comment by XPoppyX** [comment]
The app already supports these shortcuts, the problem is that they do not respond well, it is as if it required a specific timing

**Comment by chuchanpr** [comment]
There is no window to show the functions are happening, would be great to see this

**Comment by chuchanpr** [comment]
@yair100 @XPoppyX @duke7553 - copying and pasting files (larger) is confusing as there is no context menu showing the function is happening. Are we implementing #114 anytime soon?

**Comment by yaichenbaum** [comment]
@chuchanpr It is on our list of things to do but we are underpowered compared to the amount of work there is to do, if someone want's to jump in and work on#114 it would help things move faster.

**Comment by yaichenbaum** [comment]
Merging with #9.
