### ISSUE TITLE
Preferences and Files and Folders settings do not get saved

### ISSUE THREAD

**Issue by jakehandwork** [files-community/files-uwp#962]
When going to the settings and toggling any setting under Preferences or Files and Folders, these do not stay toggled when you back out. Further than that, 'Show hidden files, folders and drives' and 'Show drive letters' are disabled and I'm not sure what setting enables them.

**Comment by yaichenbaum** [comment]
> When going to the settings and toggling any setting under Preferences or Files and Folders, these do not stay toggled when you back out.

This was fixed with a recent pull request.

> Further than that, 'Show hidden files, folders and drives' and 'Show drive letters' are disabled and I'm not sure what setting enables them.

These options are not yet implemented.
