### ISSUE TITLE
Desktop (in navigation pane) shows "Onedrive>Desktop"

### ISSUE THREAD

**Issue by andyfmidd** [files-community/files-uwp#967]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.5.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by andyfmidd** [comment]
oh dear: all the details got dropped....
1) Goto Home.
2) click on Desktop in Nav panel

Path shown as D:>Onedrive>Desktop

Windows Insider build 19640 release 200530-1731
App ver: 0.9.2

**Comment by andyfmidd** [comment]
"user too close to keyboard" - misunderstood "close and comment", as referring to the comment, rather than the issue.

**Comment by generalguy41** [comment]
Do you have your desktop synced to OneDrive? That's likely why, since I believe the app will use the default location for whatever your desktop is mapped to. You can find out by right clicking your desktop icon in explorer > Properties > Location.

**Comment by yaichenbaum** [comment]
@andyfmidd This will happen if your device is setup to sync your desktop folder with OneDrive.
