### ISSUE TITLE
Add QuickLook integration

### ISSUE THREAD

**Issue by artikweb** [files-community/files-uwp#969]
**Is your feature request related to a problem? Please describe.**
It's not a problem, just an improvement. There's a popular app called QuickLook (https://github.com/QL-Win/QuickLook) that mimics the Quick Look functionality from MacOs and it'd be awesome if you could integrate pressing the space-bar on a file to trigger QL. 

**Describe the solution you'd like**
Pressing space-bar with a file selected, triggers QuickLook to show a preview of said file. 

**Describe alternatives you've considered**
Nothing other than using the normal WIndows File Explorer. 

**Additional context**
It'd look something like this:
![image](https://user-images.githubusercontent.com/6955982/84209702-b8390f00-aaae-11ea-918a-344cbd6e12fc.png)

**Comment by yaichenbaum** [comment]
Files UWP should already be integrated with QuickLook, can you check if you see a QuickLook item when right clicking on a file or folder?

**Comment by artikweb** [comment]
Oh wow I had no idea! But no, there's no "Quicklook" item and pressing space-bar does nothing. I'm using the Windows Store version of Quicklook, could that be the problem?

**Comment by generalguy41** [comment]
I have the store version (0.9.2.0) and QuickLook is still working for me.

**Comment by TailyFair** [comment]
For me QuickLook does not work as well. 
![image](https://user-images.githubusercontent.com/27275873/84232050-23f39a00-aaf8-11ea-8130-13bab0611eac.png)
Does this feature has to be enabled somehow?

**Comment by FelixZacher** [comment]
@yair100 So the issue is, that with #840 (i think, but didn't tested it) this https://github.com/files-community/files-uwp/blob/1749252c749300610adc03b286fd723bcb85fe7a/Files.Launcher/Program.cs#L226
argument is never called. So the app does not check anymore, if QuickLook is available. Since we store this information `quicklook_enabled` in the local settings, this information persists app restarts, so for older users this was true, even if the app didn't check anymore.

**Comment by seriaati** [comment]
Hope this will work soon 😐

**Comment by gave92** [comment]
@lampenlampen I think this issue is a bug introduced by the changes to the full-trust process to add support to the recycle bin. The `StartupTasks` is called too early while the full-trust process is not yet running. I'll see what to do.

**Comment by yaichenbaum** [comment]
This issue has been fixed with #1061 and will roll out to users when v0.11 is released.
