### ISSUE TITLE
Close the property windows cause the program closed

### ISSUE THREAD

**Issue by wagsoft** [files-community/files-uwp#973]
**Describe the bug**
Close the property windows cause the program closed.

**To Reproduce**
right click on one file and chose the property.  then close the property windows. and the program close.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 19041.265 Chinese version

**Comment by Jaiganeshkumaran** [comment]
The app doesn't really close however the app gets minimized. You can restore the app by using Alt+Tab.

**Comment by wagsoft** [comment]
thx, there isn't such issue now. maybe beacuse of a reboot.

**Comment by wagsoft** [comment]
Great.
