### ISSUE TITLE
Move from "totally black" dark theme to "dark grey"

### ISSUE THREAD

**Issue by Serarg95** [files-community/files-uwp#975]
I think Microsoft is moving from totally black (#00000) dark themes to dark grey themes. It gives a cleaner and lightest feeling to the user.

I propose a dark theme that uses similar colours to the leaked new Windows 10X File Explorer. I attach the image below:.

We can see it too in modern apps like "Your Phone", Edge and very probably in next Windows inbox apps coming with W10X.
![image](https://user-images.githubusercontent.com/66536926/84240851-e9413000-aafe-11ea-8f3f-e6e2efbdc026.png)

**Comment by yaichenbaum** [comment]
Is there a specific brush you think would look good for the background?

**Comment by Serarg95** [comment]
> Is there a specific brush you think would look good for the background?

Yes! I like the grey tones that "Your Phone" app uses in Dark mode. 
! 
![image](https://user-images.githubusercontent.com/66536926/84359434-e874d080-abc8-11ea-9170-d8239c0eaa13.png)

**Comment by yaichenbaum** [comment]
@Serarg95 Do you know the name of the brush?

**Comment by yaichenbaum** [comment]
After exploring the options here, we decided to continue with the existing colors as they follow the current guidelines. If someone is interested, they can try adding another theme option and if we like it we will merge it in.
