### ISSUE TITLE
App crashes when creating and naming a folder on a OneDrive

### ISSUE THREAD

**Issue by Mikodzi** [files-community/files-uwp#979]
**Describe the bug**
When creating a folder on my OneDrive and when I'm starting to type a name, the app crashes.

**To Reproduce**
1. Go to OneDrive from the sidebar
2. Click on Create Folder
3. When you see a window with the name option, start typing a name

**Expected behavior**
It creates a folder with you custom name in a OneDrive

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Enterprice 1809 17763.1158
 - App version: 0.9.2.0

**Comment by yaichenbaum** [comment]
This issue seems to be fixed in the latest release, make sure to update to the latest version to get the best experience.
