### ISSUE TITLE
Unable to enable hidden files

### ISSUE THREAD

**Issue by AbelTheGeorge** [files-community/files-uwp#981]
I wanted to enable the hidden files,folders and drive option in the settings but im not able to... im sure its not a bug but im not sure how to fix it. Is this option implemented in this preview? Thanks 

1. Go to the app
2. Click on settings
3. Scroll down to files and folders

**Screenshots**
![image](https://user-images.githubusercontent.com/63577249/84285054-9dbc6f80-ab5a-11ea-9982-c63ed2e8dc3c.png)

Desktop 
 - Windows 10 1909
 - App version: [v0.9.2.0]

**Comment by duke7553** [comment]
Duplicate of #177
