### ISSUE TITLE
Option to hide system folders in the sidebar

### ISSUE THREAD

**Issue by acid1232** [files-community/files-uwp#984]
I don't need an access to folders like Pictures, Music, Videos etc. It takes space for folders that I actually need. 
![image](https://user-images.githubusercontent.com/43500097/84288982-3abede80-ab42-11ea-9741-368f449e956a.png)

**Comment by yaichenbaum** [comment]
[v0.10 ](https://github.com/files-community/files-uwp/releases/tag/v0.10) Has been released and should be available for beta testers in a couple of hours.
