### ISSUE TITLE
Some Settings Section values get reset each time the app is opened.

### ISSUE THREAD

**Issue by prathisahrudh** [files-community/files-uwp#990]
The Settings menu seems to be bugged.
Appearance Section works perfectly but other sections in the settings menu even after setting a option get reset to their original values each time the app is opened , 
Eg: one drive Option is shown in the files menu even if the setting for it is turned off, The app crashes at times when clicking on the "on startup" section .

**Comment by yaichenbaum** [comment]
[v0.10 ](https://github.com/files-community/files-uwp/releases/tag/v0.10) Has been released and should be available for beta testers in a couple of hours.
