### ISSUE TITLE
Loop loading data in properties

### ISSUE THREAD

**Issue by hunterlan** [files-community/files-uwp#991]
**Describe the bug**
Endless load data + localization error.

**To Reproduce**
1. Go to my folder
2. Click on 'Properties' on my video
3. Endless load data

**Expected behavior**
See the information about file

**Screenshots**
![image](https://user-images.githubusercontent.com/38838841/84308299-ee39ca00-ab66-11ea-8f68-996e1eaa3a5a.png)

**Desktop:**
 - OS Version: [Windows 10 1809 17763.1282]
 - App version: [v0.9.2]

**Additional context**
This problem occur again after restarting the app and do same steps. 
I'm sorry, if same issue was created.

**Comment by Jaiganeshkumaran** [comment]
This occurs because Files UWP is trying to calculate the hash however it fails as it's a folder.

**Comment by hunterlan** [comment]
> This occurs because Files UWP is trying to calculate the hash however it fails as it's a folder.

However, it's not a folder. It's just video (.mp4).
