### ISSUE TITLE
Excellent Direction

### ISSUE THREAD

**Issue by aamman** [files-community/files-uwp#999]
I work with a lot of Photos and Video so this **feature** may be isolated to me. Sometimes I'll shoot sets of photos that I need to sort through. Right now on both file explorer and Files UWP i have to individually open each picture to see what I am looking at. The thumbnails often dont provide enough detail.

A **solution** to this already exists although dated. Windows XP had a [photo viewer ](https://user-images.githubusercontent.com/47088948/84348596-2e4e7c00-ab6a-11ea-8629-233222638140.png) in its file explorer that made it really easy to sort through sets of photos or even preview photos without having to open the photos app. Quick edits were possible such as rotating. It was a rudimentary feature but really made life easy. If such a feature were to make its way to Files UWP with additional features such as video playback it would be amazing.

I understand the complexity of implementing this. An **alternative** could be Mac OS like 'space bar to preview' solution (called Quick Look I believe). Although cumbersome for larger sets it could extend to multiple file types such as PDF, GIF and so on. Making it easier to view files at a glance. 

**Additionally**, I guess so far a missing element in the File UWP user experience is "at-a-glance". Where users of all skill levels can save a lot of time by quickly viewing and interacting with their files. It can be a complex solution like photo viewer in XP or a simpler hover balloon showing me size, file types etc. It is after all a file viewer that's supposed to look better than File Explorer but at the same time provide features missing in File Explorer.

Also the folders don't show a thumbnail preview of the files inside them. Maybe its not working for me but that can also be a great way for people to see what kind of files are in a folder as opposed to looking at a army of yellow folders. Recognition is faster than recall in such cases.

I hope this is coherent enough for you to make sense. I just found your app and it really is an upgrade so far even in beta!

Keep up the excellent work!

**Comment by Jaiganeshkumaran** [comment]
@aamman There's an app called QuickLook in the Microsoft Store which can be used to preview a file by pressing spacebar just like macOS's finder. Also, Windows File Explorer has an option known as preview pane. You can use that to view a preview a file.

**Comment by aamman** [comment]
@Jaiganeshkumaran QuickLook app doesnt work in Files UWP but its a great solution for me for now. I am aware of preview pane on file explorer but i suggested it as an addition to files uwp. Actually both these features would be great in the app.

Thanks for QuickLook its great

**Comment by Jaiganeshkumaran** [comment]
@aamman Files UWP does support QuickLook, however because of a bug in the latest version, it's no longer functioning for new users (#969).

**Comment by duke7553** [comment]
Thank you for creating this feedback item. This issue is currently resolved in our active development branch and will be shipped soon once we've validated that everything works properly. Please subscribe to our releases to be notified when this is available.
